### ISSUE TITLE
Carthage update stuck on High Sierra

### ISSUE THREAD

**Issue by Ashok28** [Carthage/Carthage#2165] opened 2017-09-21 08:41 UTC
Carthage always gets stuck after cloning/fetching all git repos. This happens on fresh install of High Sierra GM. 

* `carthage version`: 0.25.0
* `xcodebuild -version`:  Xcode 9.0
                                            Build version 9A235
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "realm/realm-cocoa" == 2.8.3
github "krzyzanowskim/CryptoSwift" == 0.6.9
github "marketplacer/keychain-swift" ~> 8.0
github "TakeScoop/SwiftyRSA" == 0.5
github "ReactiveX/RxSwift" ~> 3.0
github "RxSwiftCommunity/RxGesture" == 1.0.1
github "Polidea/RxBluetoothKit" == 3.0.13
github "robb/Cartography" == 1.1.0
github "Alamofire/Alamofire" ~> 4.0
github "dennisweissmann/DeviceKit" == 1.3.2
github "Skyscanner/SkyFloatingLabelTextField" == 3.1.0
github "apple/swift-protobuf" == 0.9.905
github "kaishin/Gifu" == 2.0
github "MoZhouqi/KMPlaceholderTextView" == 1.3.0
github "airbnb/lottie-ios" == 1.5.1
github "dzenbot/DZNEmptyDataSet" == 1.8.1
github "SwiftyBeaver/SwiftyBeaver" == 1.3.0
github "mixpanel/mixpanel-swift" == 2.1.9
github "Thomvis/BrightFutures" == 6.0.0
```

**Carthage Output**
```
*** Fetching Cartography
*** Fetching Alamofire
*** Fetching RxGesture
*** Fetching RxSwift
*** Fetching BrightFutures
*** Fetching KMPlaceholderTextView
*** Fetching realm-cocoa
*** Fetching lottie-ios
*** Fetching CryptoSwift
*** Fetching mixpanel-swift
*** Fetching SwiftyBeaver
*** Fetching DZNEmptyDataSet
*** Fetching keychain-swift
*** Fetching swift-protobuf
*** Fetching Gifu
*** Fetching DeviceKit
*** Fetching SkyFloatingLabelTextField
*** Fetching RxBluetoothKit
*** Fetching SwiftyRSA
*** Fetching Result
```

**Comment by ikesyo** [comment] 2017-09-22 17:15
Closing as a duplicate of #976.

**Closed by ikesyo** 2017-09-22 17:15 UTC
