### ISSUE TITLE
Update causes massive amount of memory / CPU usage , build works though

### ISSUE THREAD

**Issue by grangej** [Carthage/Carthage#1014] opened 2015-12-29 00:10 UTC
when using carthage update command I frequently see carthage consume all memory (14+gb) / 500 %  CPU usage.

Canceling and running carthage build works fine.

**Comment by ikesyo** [comment] 2015-12-29 00:47
This should be a dupe of #940 and #976.

**Closed by ikesyo** 2015-12-29 00:47 UTC
Labels: duplicate
