### ISSUE TITLE
PROPOSAL - Build platform for Cartfile entries

### ISSUE THREAD

**Issue by ivan-konov** [Carthage/Carthage#2398] opened 2018-03-29 23:26 UTC
Hello guys,

I have been having issues with questionable Carthage support from multiple frameworks because of the way they are configured for the different platforms. For example I need 1 to be run on macOS a bunch to run on iOS some only on watchOS some on both iOS & watchOS and none for tvOS and you don't want to wait for every possible platform to build for each dependecy. Also some dependencies might fail to build for a certain platform.

I would propose to have an addition to the Cartfile specification to add a platforms parameter for each dependency like that:

github "AFNetworking/AFNetworking" ~> 3.0 platforms: iOS, watchOS

Thanks!

**Comment by blender** [comment] 2018-03-30 08:32
Duplicate of #2294

**Closed by blender** 2018-03-30 08:32 UTC
