### ISSUE TITLE
Carthage stops installing Leanplum 2.0.2 release, with `no shared framework schemes` error

### ISSUE THREAD

**Issue by benmarten** [Carthage/Carthage#2084] opened 2017-07-28 20:24 UTC
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "Leanplum/Leanplum-iOS-SDK" == 2.0.2
```

**Carthage Output**
```
carthage update                                                                           13:18:38
*** Fetching Leanplum-iOS-SDK
*** Downloading Leanplum-iOS-SDK.framework binary at "Leanplum iOS SDK 2.0.2"
*** Skipped installing Leanplum-iOS-SDK.framework binary due to the error:
    "Failed to read file or folder at /private/var/folders/rs/s_q1py2d54q4g9bk1h7vg95r0000gn/T/carthage-archive.PEWFAZ/__MACOSX/Leanplum.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.file=/tmp/carthage-20170710-56241-9g56uj/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1100, NSLocalizedDescription=the DTSDKName key in its plist file is missing}"
*** Checking out Leanplum-iOS-SDK at "2.0.2"
*** xcodebuild output can be found in /var/folders/rs/s_q1py2d54q4g9bk1h7vg95r0000gn/T/carthage-xcodebuild.bGEzTs.log
*** Skipped building Leanplum-iOS-SDK due to the error:
Dependency "Leanplum-iOS-SDK" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Leanplum/Leanplum-iOS-SDK/issues/new
```

Using version 2.0.1 works as expected. We are not sure what has changed from 2.0.1 to 2.0.2 that broke the Carthage install. We use a .framework.zip file that is attached to the release.

I noticed that Carthage might not be able to download the framework file, as it appears it is empty with no actual content.
I compared the GitHub releases with: `curl -s https://api.github.com/repos/leanplum/Leanplum-ios-SDK/releases | jq`, but both releases 2.0.2 and 2.0.1 appear similar to me...

the download url's are:
```json
        "browser_download_url": "https://github.com/Leanplum/Leanplum-iOS-SDK/releases/download/1.2.21/Leanplum.framework.zip"
        "browser_download_url": "https://github.com/Leanplum/Leanplum-iOS-SDK/releases/download/1.2.22/Leanplum.framework.zip"
```

What is the best way to debug what issue Carthage is having?

**Comment by ikesyo** [comment] 2017-07-29 00:46
This is a duplicate of https://github.com/Carthage/Carthage/issues/1776#issuecomment-290451271.

**Closed by ikesyo** 2017-07-29 00:46 UTC
