### ISSUE TITLE
when network is not good, Fetching is too slow and maybe fail ,then update is fail...

### ISSUE THREAD

**Issue by xpf0000** [Carthage/Carthage#1889] opened 2017-04-18 03:40 UTC
I just want update one framwork , why Carthage  Fetch all?  can't it skip others??  just update i choosed one?

* `carthage version`: 0.20.1

**Cartfile**

github "ashleymills/Reachability.swift"
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON"
github "lkzhao/Hero"
github "robb/Cartography"
github "ninjaprox/NVActivityIndicatorView"
github "onevcat/Kingfisher"

**Carthage input**

carthage update Reachability.swift

**Carthage Output**
*** Fetching SwiftyJSON
*** Fetching Alamofire
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/Alamofire/Alamofire.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*) failed with exit code 128:
fatal: unable to access 'https://github.com/Alamofire/Alamofire.git/': Failed to connect to github.com port 443: Operation timed out

*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Fetching Hero
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/lkzhao/Hero.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*) failed with exit code 128:
fatal: unable to access 'https://github.com/lkzhao/Hero.git/': Operation timed out after 300028 milliseconds with 0 out of 0 bytes received

**Comment by ikesyo** [comment] 2017-04-28 17:41
This is a duplicate of #1081.

**Closed by ikesyo** 2017-04-28 17:41 UTC
Labels: duplicate
