### ISSUE TITLE
Add support for tuist/xcodegen projects

### ISSUE THREAD

**Issue by ollieatkinson** [Carthage/Carthage#2722] opened 2019-03-08 14:43 UTC
Similarly to how support is being added for [SwiftPM projects](https://github.com/Carthage/Carthage/pull/1945) how does the team feel for me adding support to Carthage for projects defined by [tuist](https://github.com/tuist/tuist) and [xcodegen](https://github.com/yonaskolb/XcodeGen).

You _could_ just commit the project files, but it's now becoming a lot more common to avoid committing them.

I would like your thoughts on if this is something you could be interested in me supporting in Carthage.

**Comment by ikesyo** [comment] 2019-03-08 16:45
This is a duplicate of #2684.

**Closed** 2019-03-08 16:47 UTC

**Comment by ollieatkinson** [comment] 2019-03-11 14:19
Fair enough @ikesyo.

What about adding support for Carthage pre-build hooks? This would mean if you want to add your own third party support you would require to program it yourself. Or is this an area you don't think Carthage should or would ever want to support.

**Comment by ollieatkinson** [comment] 2019-03-11 20:51
If this does not get solved inside of Carthage, I can work around the issue by doing the following:

```sh
carthage build --platform iOS --configuration Debug --no-build
cd Carthage/Checkouts/framework-built-with-tuist/
tuist generate
cd -
carthage build --platform iOS --configuration Debug
```
