### ISSUE TITLE
Using copy-frameworks for watch extension causes "A signed resource has been added, modified, or deleted" Xcode error

### ISSUE THREAD

**Issue by aventurella** [Carthage/Carthage#1272] opened 2016-04-14 12:55 UTC
- `0.16.2`
- `Xcode 7.3 | Build version 7D175`
- `--no-use-binaries`: Yes
- `watchOS 2.2`
- `iOS 9.3.1`

Under the watch extension's Build Phase, I have my Copy Carthage Frameworks phase added, in this case I am using XCGLogger and Unbox. In Xcode 7.2 this all worked just fine. In 7.3 however, when I attempt to run the application I get an Xcode dialog error stating:

`A signed resource has been added, modified, or deleted`

Further inspection in the devices console reveals this message:

```
<Error>: 0x1f084000 __MobileInstallationInstallForLaunchServices_block_invoke222: 
Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code 
signature of /<long_path>/temp.mCHHfg/extracted/Watch.app/PlugIns/Watch Extension.appex/Frameworks/XCGLogger.framework : 0xe8008017 
(A signed resource has been added, modified, or deleted.)" 
UserInfo={LibMISErrorNumber=-402620393, 
LegacyErrorString=ApplicationVerificationFailed, 
FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], 
NSLocalizedDescription=Failed to verify code signature of /long/path/temp.mCHHfg/extracted/Watch.app/PlugIns/Watch Extension.appex/Frameworks/XCGLogger.framework : 0xe8008017 
(A signed resource has been added, modified, or deleted.), 
SourceFileLine=142}

Apr 14 05:43:15 Dev-AppleWatch streaming_zip_conduit[214] <Warning>: 
__dispatch_source_read_socket_block_invoke:299: Failed to install application 
at file:///var/mobile/Media/PublicStaging/Watch.app/ : Error 
Domain=LaunchServicesError Code=0 "(null)" 
UserInfo={Error=ApplicationVerificationFailed, 
ErrorDetail=-402620393, ErrorDescription=Failed to verify code signature of 
/<long_path>/temp.mCHHfg/extracted/Watch.app/PlugIns/Watch Extension.appex/Frameworks/XCGLogger.framework : 0xe8008017 
(A signed resource has been added, modified, or deleted.)}
```

If I remove the Input on the Copy Carthage Frameworks Build Phase, aka:
`$(SRCROOT)/../Carthage/Build/watchOS/XCGLogger.framework`

And retry the build, it does successfully run though it's process. The app understandably crashes as it's missing a framework, but I don't get the original error about the resource.

I either 

1) missed something important in looking over the Xcode Release notes for 7.3 re: how frameworks are to be embedded in watch extensions
2) missed similar information in the carthage docs
3) never understood any of it to begin with and have just been luckily fumbling my way though it until Apple **fixed** whatever it was in 7.3 (this is a real possibility that I do not discount.)

I have however noticed that upon Xcode releases, Apple usually **fixes** SOMETHING that tends to make things that were going well, go not so well.. hahahaha

Things I have done:
- Rebuilt the frameworks under Carthage 0.16.2
- Deleted all derived data
- Cleared the carthage caches dir and rebuilt everything as well.

I have other frameworks in the project that are built within Xcode, and it's only the carthage ones that fail when being copied to the watch. The phone is fine.

**Comment by aventurella** [comment] 2016-04-16 22:43
Getting an idea from this issue:
https://github.com/Carthage/Carthage/issues/755

Specifically `MSchmidt commented on Sep 16, 2015`

I manually archived XCGLogger and added it to the embedded frameworks build phase for the WatchOS extension. I then removed the `carthage copy-frameworks` script build phase, and attempted to re-run the project on the device. No issues.

Did apple change something in Xcode 7.3 that required copy-frameworks to be updated?

**Comment by aventurella** [comment] 2016-04-16 23:31
The plot thickens!

If I run `carthage copy-frameworks` just not during Xcode's build I can use the framework just fine if I place the resultant stripped framework in the Embed Frameworks in the Watch Extension Target.

```
env VALID_ARCHS=armv7k \
TARGET_BUILD_DIR=/tmp \
FRAMEWORKS_FOLDER_PATH=frameworks \
SCRIPT_INPUT_FILE_COUNT=1 \
SCRIPT_INPUT_FILE_0=/Path/To/Tests/CarthageTest/Carthage/Build/watchOS/XCGLogger.framework \ 
carthage copy-frameworks
```

So it's stripping out the i386 architecture just fine.

**Comment by aventurella** [comment] 2016-04-18 20:06
Another step...

So when I keep copy-frameworks on  the Watch Extension, and also explicitly "embed" the same framework (which I think overwrites the architecture stripping). That will also work, no error. 

The build steps also show an additional signing step that takes place when using Embed Frameworks.

**Comment by aventurella** [comment] 2016-04-19 14:42
Hmmmm... no matter wha I try, it all comes down to: 

If I use copy-frameworks to copy a watchOS 2.2 framework for testing on device, I get the signed resource has been added modified or deleted error in xcode.

If I use copy-frameworks, but ALSO use embed frameworks (which I assume overwrites the result of copy-frameworks since it comes after in the build phases)  It works. (assuming I have cleaned the build forlder) I know it's the non-copy-frameworks version of the Frameworks as a `lipo -info` shows me it still has i386 in it.

I thought maybe it was related to the codesign in xcode using --timestamp=none, but I altered carthage to include that option, and it was still a no-go.

There is a bitcode strip step in the "embed frameworks" build phase in the logs that I don't think I see duplicated in the Carthage code, dunno if that should have any bearing on things.

**Comment by madhavajay** [comment] 2016-04-20 14:29
Hi @aventurella I am having the exact same problem, I can confirm that leaving everything as it was, including my Carthage Copy Frameworks and a custom strip build script in place and simply adding the Framework to the Embed Frameworks for the WatchApp Extension ONLY works. I also tried Xcode 7.3.1 GM without any changes and that didn't fix the issue.

**Comment by aventurella** [comment] 2016-04-20 16:16
My only workaround for now was to just use Carthage as my **download the things** tool with `--no-build` and I just plop the various Xcode Projects into my workspace. Then I build each one in Xcode and do the Embed/Linking thing. Xcode at least doesn't try to rebuild them each time as they are not modified.

**Comment by mdiep** [comment] 2016-04-22 21:17
@aventurella Does that mean you have this all sorted out? If so, would you kindly close the issue?

(I haven't yet found the time to read through this whole thread.)

**Comment by aventurella** [comment] 2016-04-23 00:14
@mdiep it's only sorted out in that I am just not having Carthage do any builds and relying solely on Xcode. So it's just more working around the problem than anything.

**Comment by madhavajay** [comment] 2016-04-23 07:58
Yeah not being able to use Carthage isnt really a solution to this problem with Carthage. :P

**Comment by mdiep** [comment] 2016-05-12 02:24
I don't have a watch project handy to test or debug this in any meaningful way. If you put together and share an example project that demonstrates the issue, that would make it a lot easier to investigate.

**Comment by pakmee** [comment] 2017-01-23 18:22
Anyone found a solution to this? Switched to carthage and my world went t*ts up :-(

**Comment by aventurella** [comment] 2017-01-23 20:03
@pakmee I don't have carthage build anything anymore.

I still use it to sync the deps, but now I just drag them into the Xcode project:

![xcode_carthage_deps](https://cloud.githubusercontent.com/assets/75315/22220466/af45ed0e-e163-11e6-923b-4660620cd772.png)

And have Xcode just build them.

- No copy-frameworks build phase to maintain
- Xcode deals with it all just fine
- No frameworks path to adjust
- You have to spend the build time ANYWAY when you have Carthage perform the build. Xcode doesn't rebuild the frameworks for the target since they don't change after the first time.

Anyway, once I started using carthage purely to download the deps (no building), all my problems went away. In fact, everything became simpler since I no longer have to tweak  framework paths  or ad copy-frameworks build phase.

**Comment by pakmee** [comment] 2017-01-23 20:50
@aventurella Thanks for this! I'll give that a shot . So you basically checkout from Carthage and drag the project in .

**Comment by aventurella** [comment] 2017-01-23 20:51
@pakmee yup..

```carthage update --no-build```

Then just drag the Xcode projects into your workspace and let Xcode deal with it all.

**Comment by ikesyo** [comment] 2017-08-09 14:46
Is this still an issue?

**Comment by ikesyo** [comment] 2017-10-19 00:23
Closing this due to inactivity.

**Closed by ikesyo** 2017-10-19 00:23 UTC
