### ISSUE TITLE
Carthage fails to install binary frameworks when OmniGraffle is installed

### ISSUE THREAD

**Issue by NikolaiRuhe** [Carthage/Carthage#3224] opened 2021-08-13 17:13 UTC
I've encountered a bug when installing binary frameworks. The frameworks were downloaded correctly but just did not show up in `Carthage/Build/iOS/`.

After hours of debugging I found the culprit in an older version of [OmniGraffle](https://www.omnigroup.com/omnigraffle) being installed (6.6.2 in my case). In it's Info.plist it registered a UTType of `com.omnigroup.foreign-types.apple-framework` with a file extension of `framework`. This prevented carthage to find apple frameworks in unzipped downloads (resulting in zero hits).

Deleting OmniGraffle solves the problem. A better solution would be to fix the test in carthage, though. The problem surfaces in `func filesInDirectory` (in `CarthageKit/Project.swift`). The filter predicate could be extended to something like:

```
let omniGroupAppleFramework = "com.omnigroup.foreign-types.apple-framework" as CFString
return UTTypeConformsTo(identifier as CFString, typeIdentifier as CFString)
    || (typeIdentifier == kUTTypeFramework as String && UTTypeConformsTo(identifier as CFString, omniGroupAppleFramework))
```

I could provide a pull request if there's interest.

Here's some additional information:

```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -E -C5 'uti:\s+com.omnigroup.foreign-types.apple-framework'

--------------------------------------------------------------------------------
type id:                    com.omnigroup.foreign-types.apple-framework (0x11d78)
bundle:                     OmniGraffle (0x1fcc)
uti:                        com.omnigroup.foreign-types.apple-framework
localizedDescription:       "Base" = ?, "de" = ?, "en" = ?, "es" = ?, "fr" = ?, "it" = ?, "ja" = ?, "LSDefaultLocalizedValue" = "ProjectBuilderDocumentType", "nl" = ?, "ru" = ?, "zh-Hans" = ?
flags:                      active  imported  untrusted (0000000000000001)
conforms to:                com.apple.package
tags:                       .framework
--------------------------------------------------------------------------------

plutil -p /Applications/OmniGraffle.app/Contents/Info.plist

[...]
    7 => {
      "UTTypeConformsTo" => "com.apple.package"
      "UTTypeDescription" => "ProjectBuilderDocumentType"
      "UTTypeIdentifier" => "com.omnigroup.foreign-types.apple-framework"
      "UTTypeTagSpecification" => {
        "public.filename-extension" => [
          0 => "framework"
        ]
      }
    }
[...]
```

**Comment by hamoody0706** [comment] 2021-08-14 11:52
> I've encountered a bug when installing binary frameworks. The frameworks were downloaded correctly but just did not show up in `Carthage/Build/iOS/`.
> 
> After hours of debugging I found the culprit in an older version of [OmniGraffle](https://www.omnigroup.com/omnigraffle) being installed (6.6.2 in my case). In it's Info.plist it registered a UTType of `com.omnigroup.foreign-types.apple-framework` with a file extension of `framework`. This prevented carthage to find apple frameworks in unzipped downloads (resulting in zero hits).
> 
> Deleting OmniGraffle solves the problem. A better solution would be to fix the test in carthage, though. The problem surfaces in `func filesInDirectory` (in `CarthageKit/Project.swift`). The filter predicate could be extended to something like:
> 
> ```
> let omniGroupAppleFramework = "com.omnigroup.foreign-types.apple-framework" as CFString
> return UTTypeConformsTo(identifier as CFString, typeIdentifier as CFString)
>     || (typeIdentifier == kUTTypeFramework as String && UTTypeConformsTo(identifier as CFString, omniGroupAppleFramework))
> ```
> 
> I could provide a pull request if there's interest.
> 
> Here's some additional information:
> 
> ```
> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -E -C5 'uti:\s+com.omnigroup.foreign-types.apple-framework'
> 
> --------------------------------------------------------------------------------
> type id:                    com.omnigroup.foreign-types.apple-framework (0x11d78)
> bundle:                     OmniGraffle (0x1fcc)
> uti:                        com.omnigroup.foreign-types.apple-framework
> localizedDescription:       "Base" = ?, "de" = ?, "en" = ?, "es" = ?, "fr" = ?, "it" = ?, "ja" = ?, "LSDefaultLocalizedValue" = "ProjectBuilderDocumentType", "nl" = ?, "ru" = ?, "zh-Hans" = ?
> flags:                      active  imported  untrusted (0000000000000001)
> conforms to:                com.apple.package
> tags:                       .framework
> --------------------------------------------------------------------------------
> 
> plutil -p /Applications/OmniGraffle.app/Contents/Info.plist
> 
> [...]
>     7 => {
>       "UTTypeConformsTo" => "com.apple.package"
>       "UTTypeDescription" => "ProjectBuilderDocumentType"
>       "UTTypeIdentifier" => "com.omnigroup.foreign-types.apple-framework"
>       "UTTypeTagSpecification" => {
>         "public.filename-extension" => [
>           0 => "framework"
>         ]
>       }
>     }
> [...]
> ```

**Comment by tmspzz** [comment] 2021-09-16 07:41
Duplicate of: 
- https://github.com/Carthage/Carthage/issues/3084
- https://github.com/Carthage/Carthage/issues/3093

**Closed by tmspzz** 2021-09-16 07:41 UTC
