### ISSUE TITLE
carthage update performs unnecessary rebuilds

### ISSUE THREAD

**Issue by thedjinn** [Carthage/Carthage#1527] opened 2016-10-12 13:41 UTC
* `carthage version`: 0.18-19-g743fa0f
* `xcodebuild -version`: 8A218a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
git "git@url.to.private.repo/first.git" "master"
git "git@url.to.private.repo/second.git" "master"
git "git@url.to.private.repo/third.git" "master"
git "git@url.to.private.repo/fourth.git" "master"
```

**Carthage Output**
```
*** Fetching fourth
*** Fetching third
*** Fetching second
*** Fetching first
*** Checking out first at "1e7352877c39681fbb2131b4062eb2cd1e435fad"
*** Checking out second at "ab4bca7b94b4144020ed5447b9a865675ac62440"
*** Checking out third at "70267e42d584094ae4ae501c9e4fe73c984f5cda"
*** Checking out fourth at "4468dac2264d1b851e9b1b6ce1dc181997f61a95"
*** xcodebuild output can be found in /var/folders/lz/7yskq99x0w7gf3_xphcbg1800000gn/T/carthage-xcodebuild.raDdtj.log
*** Building scheme "First" in First.xcodeproj
*** Building scheme "Second" in Second.xcodeproj
*** Building scheme "Third" in Third.xcodeproj
*** Building scheme "Fourth" in Fourth.xcodeproj
```

I have several projects with Cartfiles that look like the example above (the repository names have been redacted). There are no other (nested) dependencies. When I push commits to only one of the repositories and then run `carthage update` all four repositories are being rebuilt, thus making the command take a lot of time and waste my precious battery time. I think it is preferred to have Carthage compare the commit hashes and only rebuild if necessary.

**Comment by ikesyo** [comment] 2016-10-12 14:51
This is a duplicate of #1222 and #1489.

**Closed by ikesyo** 2016-10-12 14:51 UTC
