### ISSUE TITLE
`carthage update <dependency>` fetches & builds all Cartfile dependencies

### ISSUE THREAD

**Issue by poolqf** [Carthage/Carthage#1112] opened 2016-02-10 16:55 UTC
Hi all!

I am having an issue related with #972 . Trying to update a single dependency, updates all the dependencies that are listed in the Cartfile.

Carthage version: 0.13.0

So, having the following Cartfile

```
github "Alamofire/Alamofire" ~> 3.1.4
github "Quick/Nimble" "v3.0.0"
github "Quick/Quick" "v0.8.0"
github "AliSoftware/OHHTTPStubs" ~> 4.7.0
github "Hearst-DD/ObjectMapper" ~> 1.0.1
github "redbooth/RealmResultsController"
github "Haneke/HanekeSwift" "v0.10.1"
github "ReactiveCocoa/ReactiveCocoa" "v4.0.0-RC.1"
```

If I run `carthage update RealmResultsController --platform iOS --no-use-binaries`. This is the output that I get is:

```
*** Fetching ReactiveCocoa
*** Fetching HanekeSwift
*** Fetching RealmResultsController
*** Fetching ObjectMapper
*** Fetching OHHTTPStubs
*** Fetching Quick
*** Fetching Nimble
*** Fetching Alamofire
*** Fetching Result
*** Fetching realm-cocoa
*** Checking out Alamofire at "3.1.4"
*** Checking out HanekeSwift at "v0.10.1"
*** Checking out Nimble at "v3.0.0"
*** Checking out ObjectMapper at "1.1.1"
*** Checking out OHHTTPStubs at "4.7.0"
*** Checking out Quick at "v0.8.0"
*** Checking out realm-cocoa at "v0.98.0"
*** Checking out Result at "1.0.1"
*** Checking out ReactiveCocoa at "v4.0.0-RC.1"
*** Checking out RealmResultsController at "0.4.1"
*** xcodebuild output can be found in /var/folders/2f/0p0vhkdj52187rq9xbl877t40000gn/T/carthage-xcodebuild.6tpser.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Haneke" in Haneke.xcworkspace
...
...
```

**Comment by mdiep** [comment] 2016-02-10 17:07
This is a duplicate of #1081 and will be fixed in the next release.

**Closed by mdiep** 2016-02-10 17:07 UTC

**Comment by poolqf** [comment] 2016-02-10 17:11
Sorry, as it was closed I did not see it :+1:
