### ISSUE TITLE
Unable to install Carthage on OS X 10.11 via HomeBrew

### ISSUE THREAD

**Issue by damianesteban** [Carthage/Carthage#843] opened 2015-10-13 01:44 UTC
I recently upgraded to El Capitan (I did a clean install) and much to my dismay I was unable to install Carthage.  I received the following error code:

```
Swift.toString:1:33: note: 'toString' has been explicitly marked unavailable here
@available(*, unavailable) func toString<T>(x: T) -> String

** INSTALL FAILED **

The following build commands failed:
     CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
     CompileSwift normal x86_64 /tmp/carthage20151012-15214-1agwp4x/Carthage/Checkouts/Box/Box/Box.swift
     CompileSwift normal x86_64 /tmp/carthage20151012-15214-1agwp4x/Carthage/Checkouts/Box/Box/MutableBox.swift
(3 failures)
make: *** [installables] Error 65
```

Is this Homebrew related or Carthage related?

**Comment by ikesyo** [comment] 2015-10-13 02:41
This is a duplicate of #807, #818 and #825.

**Closed by ikesyo** 2015-10-13 02:41 UTC
Labels: duplicate

**Comment by jpoe123** [comment] 2016-06-06 17:59
Is this issue closed? I am still running into the same issues with El Capitan 10.11
