### ISSUE TITLE
dependency graph resolution

### ISSUE THREAD

**Issue by HHuckebein** [Carthage/Carthage#1097] opened 2016-02-04 08:25 UTC
We've been building a project setup where the main project as well as all modules depend on a "Foundation" modul.
Furthermore we have a BaseDataModul and a SubBaseDataModul. 
The dependencies are as follows (Cartfile)
- main (Foundation, BaseModul, SubBaseModule)
- BaseDataModul (Foundation)
- SubBaseModul (BaseDataModul, Foundation)
All Cartfiles require to load the head of a branch

git "repo_url" "branch_name"

When ever I try to build the project by

`carthage update --platform iOS --no-use-binaries`

I get carthage complaints

> Could not pick a version for git "repo url", due to mutually incompatible requirements:
	"70d5358e9994305a96832e9fc60e24be5b324376"
	"branch"

But the commit id displayed is the head of the "branch".
I've build a sample project with almost nothing in it and I ran into the same issue.
Could you tell if this setup should work?

Update: Just found out that 0.11.0 and 0.12.0 behave differently
The same test with 0.11.0 worked fine.

**Comment by mdiep** [comment] 2016-02-04 15:35
This is a duplicate of #1080. We're working on a fix.

**Comment by ikesyo** [comment] 2016-02-05 14:28
Closed by #1100.

**Closed by ikesyo** 2016-02-05 14:28 UTC
