### ISSUE TITLE
Installing carthage El Capitan

### ISSUE THREAD

**Issue by lucatorella** [Carthage/Carthage#818] opened 2015-10-01 18:50 UTC
When I try to install Carthage I get the following error

```
Last 15 lines from /Users/myuser/Library/Logs/Homebrew/carthage/01.make:
    /bin/ln -sfh /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/UninstalledProducts/Runes.framework /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/BuildProductsPath/Release/Runes.framework

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /tmp/carthage20151001-11081-iumll0/Carthage/Checkouts/Runes
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Runes -O -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -target x86_64-apple-macosx10.9 -g -module-cache-path /Users/myuser/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -application-extension -I /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/BuildProductsPath/Release -F /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/BuildProductsPath/Release -c -j4 /tmp/carthage20151001-11081-iumll0/Carthage/Checkouts/Runes/Source/Operators.swift /tmp/carthage20151001-11081-iumll0/Carthage/Checkouts/Runes/Source/Optional.swift /tmp/carthage20151001-11081-iumll0/Carthage/Checkouts/Runes/Source/Array.swift -output-file-map /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/Objects-normal/x86_64/Runes-Mac-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/Objects-normal/x86_64/Runes.swiftmodule -Xcc -I/Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/Runes-generated-files.hmap -Xcc -I/Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/Runes-own-target-headers.hmap -Xcc -I/Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/Runes-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/Runes-project-headers.hmap -Xcc -I/Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/BuildProductsPath/Release/include -Xcc -I/Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/DerivedSources/x86_64 -Xcc -I/Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/Objects-normal/x86_64/Runes-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/myuser/Library/Developer/Xcode/DerivedData/Carthage-egskaemtsyqhozbwpiddscsaqeen/Build/Intermediates/ArchiveIntermediates/carthage/IntermediateBuildFilesPath/Runes.build/Release/Runes-Mac.build/unextended-module-overlay.yaml -Xcc -working-directory/tmp/carthage20151001-11081-iumll0/Carthage/Checkouts/Runes

** INSTALL FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /tmp/carthage20151001-11081-iumll0/Carthage/Checkouts/Box/Box/Box.swift
	CompileSwift normal x86_64 /tmp/carthage20151001-11081-iumll0/Carthage/Checkouts/Box/Box/MutableBox.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)
make: *** [installables] Error 65
```

I've homebrew 0.8 and El Capitan.

**Comment by mdiep** [comment] 2015-10-02 00:15
This is a duplicate of #807, which has an explanation. :smile:

**Closed by mdiep** 2015-10-02 00:15 UTC
