### ISSUE TITLE
Carthage update ignores platform specified

### ISSUE THREAD

**Issue by agordeev** [Carthage/Carthage#2688] opened 2019-01-20 13:47 UTC
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "ReactiveX/RxSwift"
```

**Carthage Output**
<img width="323" alt="screenshot 2019-01-20 at 16 45 46" src="https://user-images.githubusercontent.com/2883524/51440013-b99b4900-1cb9-11e9-8a3f-5e91c52194ad.png">

**Actual outcome**
I run `carthage update --platform iOS`, but Carthage produced builds for all the platforms

**Expected outcome**
Carthage produce builds only for the specified platform

**Comment by ikesyo** [comment] 2019-01-20 13:51
I think that the frameworks are from prebuilt binaries, so actually those are not built but downloaded. But that will not be an ideal behavior.

**Comment by ikesyo** [comment] 2019-01-20 14:11
This is a duplicate of https://github.com/Carthage/Carthage/issues/1596.

**Closed** 2019-01-20 16:00 UTC
