### ISSUE TITLE
Carthage versions newer than 0.25.0 does not include ARM dSYM information

### ISSUE THREAD

**Issue by demosten** [Carthage/Carthage#2329] opened 2018-01-19 15:50 UTC
* `carthage version`: every version newer than 0.25.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`?  NO
* Are you using `--no-use-binaries`? NO (reproducible with YES too)
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO (reproducible with YES too)

This took me LONG time to discover because it issue is hidden and cannot be easily discovered. 
As a result I did NOT get Fabric crash symbolications.

Here is how to reproduce:
You can use my Cartfile - the repo is public

**Cartfile**
```
github "demosten/SKCrashlyticsTest" "ea23579e6bbbe642f4fdc8dd89227b99b9a3e53d"
```

**Carthage Output**
```
$ carthage update --platform ios --use-ssh
Please update to the latest Carthage version: 0.27.0. You currently are on 0.25.0
*** Checking out SKCrashlyticsTest at "ea23579e6bbbe642f4fdc8dd89227b99b9a3e53d"
*** xcodebuild output can be found in /var/folders/60/y02t9f0j08j2_fvzj43881gr0000gp/T/carthage-xcodebuild.MrpxTJ.log
*** Building scheme "SKCrashlyticsTest" in SKCrashlyticsTest.xcodeproj

$ dwarfdump Carthage/Build/iOS/SKCrashlyticsTest.framework.dSYM/
----------------------------------------------------------------------
 File: Carthage/Build/iOS/SKCrashlyticsTest.framework.dSYM/Contents/Resources/DWARF/SKCrashlyticsTest (x86_64)
----------------------------------------------------------------------
.debug_info contents:

0x00000000: Compile Unit: length = 0x00000124  version = 0x0004  abbr_offset = 0x00000000  addr_size = 0x08  (next CU at 0x00000128)
... and so on ...
----------------------------------------------------------------------
 File: Carthage/Build/iOS/SKCrashlyticsTest.framework.dSYM/Contents/Resources/DWARF/SKCrashlyticsTest (arm64)
----------------------------------------------------------------------
.debug_info contents:

0x00000000: Compile Unit: length = 0x00000124  version = 0x0004  abbr_offset = 0x00000000  addr_size = 0x08  (next CU at 0x00000128)
... and so on ...
$ 


NOW WE UPGRADE CARTHAGE TO ANY LATER VERSION (in this case the latest 0.27.0)
=======================
$ carthage version
0.27.0
$ carthage update --platform ios --use-ssh
*** Checking out SKCrashlyticsTest at "ea23579e6bbbe642f4fdc8dd89227b99b9a3e53d"
*** xcodebuild output can be found in /var/folders/60/y02t9f0j08j2_fvzj43881gr0000gp/T/carthage-xcodebuild.tM6caf.log
*** Building scheme "SKCrashlyticsTest" in SKCrashlyticsTest.xcodeproj

$ dwarfdump Carthage/Build/iOS/SKCrashlyticsTest.framework.dSYM/
----------------------------------------------------------------------
 File: Carthage/Build/iOS/SKCrashlyticsTest.framework.dSYM/Contents/Resources/DWARF/SKCrashlyticsTest (x86_64)
----------------------------------------------------------------------
.debug_info contents:

0x00000000: Compile Unit: length = 0x00000124  version = 0x0004  abbr_offset = 0x00000000  addr_size = 0x08  (next CU at 0x00000128)
... and so on ...

----------------------------------------------------------------------
 File: Carthage/Build/iOS/SKCrashlyticsTest.framework.dSYM/Contents/Resources/DWARF/SKCrashlyticsTest (arm64)
----------------------------------------------------------------------
.debug_info contents:
< EMPTY >
$

```
Please note the **< EMPTY >** debug info for `arm64`. 

When you have older processor family selected you also get builds for `i386` and `arm` with the same results `i386` has symbols, `arm` does not

**Comment by mdiep** [comment] 2018-01-19 17:57
This is a duplicate of #2280.

**Closed by mdiep** 2018-01-19 17:57 UTC
