### ISSUE TITLE
Caught signal triggered by the Swift runtime! Illegal instruction

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#1844] opened 2017-03-22 10:09 UTC
* `carthage version`:  0.19.1
* `xcodebuild -version`:  Xcode 8.2.1 Build version 8C1002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "ElaWorkshop/TagListView" == 1.1.0
```

**Carthage Output**
```
Caught signal triggered by the Swift runtime!
Illegal instruction

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.
```

I download and run the demo project for TagListView. I don't have any error or crash.

**Comment by ikesyo** [comment] 2017-03-22 10:38
This might be a duplicate of #1787.

**Comment by sasojadrovski** [comment] 2017-03-22 12:00
@TofPlay, the same thing happened to me, and even worse, as soon as the build was done processing on iTunes Connect, I got an email saying that the binary is invalid.

In order to solve this, use version 0.18.1. That did the trick for me.

I hope that this will help you :)

**Comment by TofPlay** [comment] 2017-03-22 13:22
@sasojadrovski Ok. Thanks for that tip 😊

**Comment by TofPlay** [comment] 2017-03-22 14:18
@sasojadrovski downgrade to 0.18.1 work fore me too 👍  😋

**Comment by sasojadrovski** [comment] 2017-03-22 14:19
@TofPlay, Glad to hear that :)

**Comment by ikesyo** [comment] 2017-04-28 16:08
I think this can be closed now.

**Closed by ikesyo** 2017-04-28 16:08 UTC
