### ISSUE TITLE
Dependency has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by hailcl** [Carthage/Carthage#1849] opened 2017-03-28 03:52 UTC
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 8.2.1 Build version 8C1002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? both yes/no

**Cartfile**
```
github "hailcl/ZSSRichTextEditor"

```
**Carthage Output**
```
*** Fetching ZSSRichTextEditor
*** Checking out ZSSRichTextEditor at "5.3.1"
*** xcodebuild output can be found in /var/folders/cb/n_ccw95n7zs11l87f9w98s7h0000gn/T/carthage-xcodebuild.D4C8aA.log
*** No cache found for ZSSRichTextEditor, building with all downstream dependencies
*** Skipped building ZSSRichTextEditor due to the error:
Dependency "ZSSRichTextEditor" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/hailcl/ZSSRichTextEditor/issues/new

**Comment by ikesyo** [comment] 2017-03-28 04:26
Looks like you fixed the root cause: https://github.com/hailcl/ZSSRichTextEditor/commit/9f789f3b18b0e980be117eeee93572b716e24455. Closing.

**Closed by ikesyo** 2017-03-28 04:26 UTC
