### ISSUE TITLE
xcodebuild timed out while trying to read *.xcworkspace

### ISSUE THREAD

**Issue by eMdOS** [Carthage/Carthage#2119] opened 2017-08-15 20:33 UTC
* `carthage version`: 0.24.0
* `xcodebuild -version`: 9M202q
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? YES
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO

**Cartfile**
```
github "eMdOS/Motu" ~> 0.2
```

**Carthage Output**
```
*** Fetching Motu
*** Checking out Motu at "v0.2.1"
*** xcodebuild output can be found in /var/folders/b1/s1qpsmd1073dygf_gghr9ytw0000gn/T/carthage-xcodebuild.CYPzkU.log
xcodebuild timed out while trying to read Motu.xcworkspace 😭
```

**Comment by jdhealy** [comment] 2017-08-15 20:49
Most likely. this is the same issue with Xcode 9.0β5 (Build version 9M202q) as https://github.com/Carthage/Carthage/issues/2104.

<a href="https://github.com/Carthage/Carthage/issues/2104#issuecomment-321401132">
Noted workaround:

<blockquote>One way around it is to set all the team IDs to "none" ... but def' a bug.</blockquote>
</a>

**Comment by ikesyo** [comment] 2017-08-15 23:37
Closing this as a duplicate of #2104.

**Closed by ikesyo** 2017-08-15 23:37 UTC
