### ISSUE TITLE
Carthage update specific framework

### ISSUE THREAD

**Issue by Beniamiiin** [Carthage/Carthage#2988] opened 2020-05-15 18:57 UTC
Executing `carthage update Alamofire` I expect that carthage will update only Alamofire, but first of all, it fetches and checkouts all frameworks and after it updates Alamofire. Is it possible to avoid fetching all frameworks and fetch only Alamofire?

**Comment by ikesyo** [comment] 2020-05-15 23:14
Duplicate of #1081.

**Closed by ikesyo** 2020-05-15 23:14 UTC
