### ISSUE TITLE
MacOS Sierra supports?

### ISSUE THREAD

**Issue by SethCody** [Carthage/Carthage#1504] opened 2016-09-26 13:58 UTC
* `carthage version`: 0.18
* `xcodebuild -version`: Xcode8
* Are you using `--no-build`?No
* Are you using `--no-use-binaries`?No
* Are you using `--use-submodules`?No
When i try to import ReactiveSwift,i can't find the methods of it,but just two varies about version.

**Comment by mdiep** [comment] 2016-09-26 14:02
Please add your `Cartfile` and the output of `carthage update`.

**Comment by ikesyo** [comment] 2016-09-26 14:28
This is a duplicate of #1503 and https://github.com/ReactiveCocoa/ReactiveSwift/issues/41 and should be closed. Please reopen the latter issue if you still have a problem instead.

**Closed by ikesyo** 2016-09-26 14:28 UTC
