### ISSUE TITLE
make error!!!

### ISSUE THREAD

**Issue by zdiovo** [Carthage/Carthage#828] opened 2015-10-06 03:41 UTC
My OS is OSX 10.11
** INSTALL FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
make: *** [installables] Error 65

How to finished it?

**Comment by ikesyo** [comment] 2015-10-06 03:49
This is a duplicate of #807, please see that thread instead.

**Closed by ikesyo** 2015-10-06 03:49 UTC
Labels: duplicate
