### ISSUE TITLE
Not able to compile facebook-ios-sdk using Xcode9 build tools

### ISSUE THREAD

**Issue by spandana-batchu** [Carthage/Carthage#2139] opened 2017-08-29 05:01 UTC
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 9.0 beta 6 (9M214v)
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`?  Yes
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
github "facebook/facebook-sdk-swift" "master"
github "facebook/facebook-ios-sdk" "sdk-version-4.26.0"
```

**Carthage Output**
```
*** Building scheme "FBSDKLoginKit-Dynamic" in FacebookSDK.xcworkspace

Caught signal triggered by the Swift runtime!
Illegal instruction

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new
```

**Comment by mdiep** [comment] 2017-08-29 12:05
This is a duplicate of #2099.

**Closed by mdiep** 2017-08-29 12:05 UTC
