### ISSUE TITLE
No lookup simbols

### ISSUE THREAD

**Issue by ManuRodriguezSebastian** [Carthage/Carthage#2295] opened 2017-12-18 11:01 UTC
* `carthage version`: 0.27.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON"
github "marketplacer/keychain-swift"
github "realm/realm-cocoa"
github "ashleymills/Reachability.swift" "v3"
```

**Carthage Output**
```
carthage bootstrap
*** Checking out Alamofire at "4.6.0"
*** Checking out Reachability.swift at "v3"
*** Checking out SwiftyJSON at "4.0.0"
*** Checking out keychain-swift at "8.0.3"
*** Downloading realm-cocoa.framework binary at "v3.0.2"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out realm-cocoa at "v3.0.2"
*** xcodebuild output can be found in /var/folders/pj/zb4rvnn526xcf6gx70cp4lbw0000gn/T/carthage-xcodebuild.6U657Y.log
*** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
*** Building scheme "KeychainSwift-macOS" in KeychainSwift.xcodeproj
*** Building scheme "KeychainSwift-tvOS" in KeychainSwift.xcodeproj
*** Building scheme "KeychainSwift" in KeychainSwift.xcodeproj
*** Building scheme "KeychainSwift-watchOS" in KeychainSwift.xcodeproj
*** Building scheme "ReachabilityMac" in Reachability.xcodeproj
*** Building scheme "ReachabilityTV" in Reachability.xcodeproj
*** Building scheme "Reachability" in Reachability.xcodeproj
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "SwiftyJSON macOS" in SwiftyJSON.xcworkspace
*** Building scheme "SwiftyJSON tvOS" in SwiftyJSON.xcworkspace
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "SwiftyJSON watchOS" in SwiftyJSON.xcworkspace
```
When I use some of these frameworks (Alamofire, SwiftyJSON, Realm...) I can use it in my project, but if I want see in the Xcode console, the following message appears:

```
Printing description of response:
expression produced error: error: Couldn't lookup symbols:
  __T09Alamofire12DataResponseVMa
``` 

What could be the error or what am I doing wrong?

**Comment by ManuRodriguezSebastian** [comment] 2017-12-18 14:46
In version 0.23.0 this error has been fixed, in the previous version is not solved. This error appear only in physical device, not in simulator.

**Comment by blender** [comment] 2018-02-09 13:32
Duplicate of #2280

**Closed by blender** 2018-02-09 13:32 UTC
Labels: duplicate
