### ISSUE TITLE
on update only build platforms of base project

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#730] opened 2015-09-02 14:00 UTC
If i have an `iOS` only build target in my main project, it would be nice if carthage update (by default) only built `iOS` targets as opposed to all shared targets.

**Comment by jlawton** [comment] 2015-09-02 21:21
That strikes me as a reasonable default, assuming there are only iOS targets in all of the project files in the top repo. But I think a better solution might be to have a line like `platform iOS` that we can add to a Cartfile. I prefer the explicit nature of it. I think there has been talk of additions to the Cartfile syntax in the past (See #262, #356).

**Comment by jeeftor** [comment] 2015-09-03 00:48
I guess I was assuming carthage could take a look at the project file itself and determine what build targets are present and then only choose to build those targets.  I guess perhaps that goes kind of against the whole carthage principal because its more or less independent of Xcode - but perhaps having a "default" platform inside the `Cartfile` would be worth while.

Lately i've been making most of my frameworks have both an OS X and an iOS target and in doing so i've noticed an exponential inquired in my `carthage update` times if i forget to specify the platform option.

**Comment by AtomicCat** [comment] 2015-09-05 17:20
This should probably be specified in the top level Cartfile. For example, we've got 4 shared frameworks that build for iOS, MacOS, and WatchOS.

On my iOS only app, I get 12 framework builds which is a huge time waste. However, we do have other iOS apps with a WatchOS app, so in that case I'd want to only drop one of the architectures.

**Comment by jeeftor** [comment] 2015-09-07 10:36
Agree`d

**Comment by mdiep** [comment] 2015-12-15 02:29
This is a duplicate of #356.

**Closed by mdiep** 2015-12-15 02:29 UTC
