### ISSUE TITLE
Carthage always build every target even has no code update.

### ISSUE THREAD

**Issue by ufosky** [Carthage/Carthage#1623] opened 2016-12-02 07:53 UTC
* `carthage version`:  0.18.1
* `xcodebuild -version`: Xcode 8.1
Build version 8B62
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

Every time I run `carthage update --platform iOS` , it always build every target. What I expect is just build the updated repositories.

**Comment by ikesyo** [comment] 2016-12-02 08:05
This is a duplicate of #975. Closing.

**Closed by ikesyo** 2016-12-02 08:05 UTC
Labels: duplicate
