### ISSUE TITLE
[Feature Request] Support for transitive dependencies in Binary only dependencies

### ISSUE THREAD

**Issue by abishek3876** [Carthage/Carthage#2609] opened 2018-10-09 04:23 UTC
Currently there is no way to specify transitive dependencies on a binary-only carthage dependency. Ideally, binary only dependencies should have complete feature parity with other kinds of dependencies and there should be a way to provide transitive dependencies similar to the others.

**Actual outcome**
There's no way to provide transitive dependencies for binary frameworks.

**Expected outcome**
There should be a way to provide the transitive dependencies for binary dependencies as well.

**Comment by ikesyo** [comment] 2018-10-09 08:08
Duplicate of #1937.

**Closed by ikesyo** 2018-10-09 08:08 UTC
