### ISSUE TITLE
Recursive fetching bug?

### ISSUE THREAD

**Issue by AndrewSB** [Carthage/Carthage#1374] opened 2016-06-27 22:22 UTC
* `carthage version`: 0.16.2
* `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes 
* Are you using `--use-submodules`? no

**Cartfile**
```
github "AndrewSB/Library" "master"
github "ReactiveX/RxSwift"
github "Haneke/HanekeSwift"
github "xmartlabs/Eureka" ~> 1.5
github "souzainf3/RNLoadingButton-Swift" "master"
github "anon/IHaveManySubDependencies" "master"
github "Codeido/PMAlertController" "master"
github "Ben-G/Validated" "master"
github "ruipfcosta/RxMediaPicker" "master"
github "devxoul/Then" >= 1.0.3```
```

`anon/IHaveManySubDependencies` looks like:
```
github "ReactiveX/RxSwift"
github "leonereveel/Moya" "multipart-upload"
github "hkellaway/Gloss" "master"
github "tonymillion/Reachability" "master"
github "Square/Valet" >= 2.2.1
github "Ben-G/Validated" "master"
github "proxyco/RxBluetoothKit" "master"
```

**Carthage Output**
```
*** Fetching RxMediaPicker
*** Fetching Then
*** Fetching Validated
*** Fetching PMAlertController
*** Fetching RNLoadingButton-Swift
*** Fetching Library
*** Fetching Eureka
*** Fetching HanekeSwift
*** Fetching RxSwift
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching Valet
*** Fetching Result
*** Fetching ReactiveCocoa
*** Fetching Alamofire
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Fetching RxBluetoothKit
*** Fetching Validated
*** Fetching Reachability
*** Fetching Gloss
*** Fetching Moya
*** Checking out Alamofire at "3.4.1"
*** Checking out Eureka at "1.6.0"
*** Checking out Gloss at "b3b21797ebc69225ec716a8cf3163d6d4e1945da"
*** Checking out HanekeSwift at "v0.10.1"
*** Checking out Library at "e3e127cb6094325f02452e4ff90e211a4e02bda3"
*** Checking out PMAlertController at "2c80111cd67c8aef1f9e1e96aa9d92c3c43378c1"
*** Checking out Reachability at "c4d225a479379f9998dbd5b55070427373d20574"
*** Checking out Result at "0.6.0-beta.6"
*** Checking out ReactiveCocoa at "v4.2.0"
*** Checking out RNLoadingButton-Swift at "067f77c66e2ade38e507ef07ecf6d78b391a55e2"
*** Checking out RxSwift at "2.4"
*** Checking out Moya at "bd143097616777c315321596f1af2623b91d89f7"
*** Checking out RxBluetoothKit at "0c7bca3e302a71d2e155759391d85ac653aad76e"
*** Checking out RxMediaPicker at "d40993aa469c077529404b4041e4b06b14063961"
*** Checking out Then at "1.0.3"
*** Checking out Valet at "2.2.1"
*** Checking out Validated at "25418067d90835317aabbe66a0bad2106f3a1d51"
*** Checking out IHaveManySubDependencies at "3591556df3398d421e2a2acfd44bd49640a6fcf0"
... (Builds dependencies)
```

**Comment by AndrewSB** [comment] 2016-06-27 22:23
Not sure why Carthage goes into a fetch loop

**Comment by NachoSoto** [comment] 2016-06-28 00:07
I wonder if this is related to https://github.com/Carthage/Carthage/issues/1360#issuecomment-228575995.

**Comment by blender** [comment] 2016-06-28 16:15
I also have this behaviour.

**Comment by mdiep** [comment] 2016-06-29 02:28
I think Carthage may be trying to fetch refs that no longer exist. When a ref doesn't exist locally, Carthage tries to fetch it. So if the resolver is trying older and older versions, it may find versions that were pinned to a branch that no longer exists. In that case, it will try a fetch again.

Carthage needs to only fetch a given dependency once per execution.

**Comment by blender** [comment] 2016-06-30 10:40
I don't know if it's related but I'm also seeing this behaviour, carthage is trying to fetch the same framework a stunning amount of times.

```
...
*** Fetching ResearchKit
*** Fetching HockeySDK-iOS
*** Fetching HanekeSwift
*** Fetching KeychainAccess
*** Fetching SnapKit
*** Fetching CoreStore
*** Fetching Tyro
*** Fetching Swiftz
*** Fetching Alamofire
*** Fetching GCDKit
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
*** Fetching Swiftz
....
```

**Comment by mdiep** [comment] 2016-06-30 12:55
This is a duplicate of #733.

> If you see this, it's because Carthage is trying to resolve your dependencies, but can't find versions that work together. It's going further back in history to try to find versions that work together (and then mistakenly fetching again).

**Closed by mdiep** 2016-06-30 12:55 UTC
