### ISSUE TITLE
Submodules are not being re-fetched from Carthage's cache - take 2

### ISSUE THREAD

**Issue by fabiomassimo** [Carthage/Carthage#1221] opened 2016-03-28 17:53 UTC
From previously closed issue #320 . I'm not encountering the same issue.

From Cartfile:

```
github "OAuthSwift/OAuthSwift" "master"
```

Even after I have deleted the Carthage/ folder and the Carthage's Cache, the issue keeps showing up.
Although, the project is properly checkout in `Carthage/Checkout` folder and running `carthage build` works as expected.

The command I'm running is:

`carthage update --platform iOS --use-submodules --no-use-binaries`

**Comment by mdiep** [comment] 2016-03-28 22:47
This is a duplicate of #1191 and will be fixed in the next release. (Should be soon, but I want to get everything updated for Swift 2.2 first.)

**Closed by mdiep** 2016-03-28 22:47 UTC
