### ISSUE TITLE
carthage update is getting old commit

### ISSUE THREAD

**Issue by fulldecent** [Carthage/Carthage#1246] opened 2016-04-07 15:38 UTC
* `carthage version`: 0.15.2
* `xcodebuild -version`: Xcode 7.3 / Build version 7D175
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
git "../SimpleMultiplier" "master"
```

**Carthage Output**
```
*** Checking out SimpleMultiplier at "a0f68a28aeb57e2c4f8b6ef2191170a88c2dd7fc"
*** xcodebuild output can be found in /var/folders/9z/ycyddbld1zgcx86xbqz2ywxm0000gp/T/carthage-xcodebuild.oig3A6.log
*** Building scheme "SimpleMultiplier" in SimpleMultiplier.xcodeproj
*** Building scheme "SimpleMultiplier" in SimpleMultiplier.xcodeproj
```

------

I had run `carthage update` before and it fetched the git and everything worked great. Then I added a commit to that repository.

In the folder `SimpleMultiplier`, if I run `git log master` it produces:

> commit 152ba80148944e5a3fa7b8620a78ee83952f026a
> Date:   Thu Apr 7 10:59:11 2016 -0400
> ...
> commit a0f68a28aeb57e2c4f8b6ef2191170a88c2dd7fc
> Date:   Thu Apr 7 10:37:30 2016 -0400

I was expecting `carthage update` to get the latest version. Instead, carthage continues to use the old `a0f68a2` commit.

**Comment by ikesyo** [comment] 2016-04-07 15:41
This should be a duplicate of #968 and/or #1191. Closing.

**Closed by ikesyo** 2016-04-07 15:41 UTC
Labels: bug, duplicate

**Comment by fulldecent** [comment] 2016-04-07 15:51
Yes, thank you for pointing in the right direction.
