### ISSUE TITLE
GitHub API request failed: DoesNotExist

### ISSUE THREAD

**Issue by vishal91** [Carthage/Carthage#1424] opened 2016-08-09 06:58 UTC
* `carthage version`**: 0.16** 
* `xcodebuild -version`**: Xcode 7.3.1 , Build version 7D1014**
* Are you using `--no-build`? **: NO**
* Are you using `--no-use-binaries`? **: NO**
* Are you using `--use-submodules`? **: NO** 

**Cartfile**
```
github "SwiftBond/Bond" ~> 4.0
github "ReactiveX/RxSwift" ~> 2.0
github "SnapKit/SnapKit" ~> 0.15.0
```

**Carthage Output**
```
carthage bootstrap --platform ios    
*** No Cartfile.resolved found, updating dependencies
*** Fetching SnapKit
*** Fetching RxSwift
*** Fetching Bond
*** Checking out Bond at "v4.3.1"
*** Checking out RxSwift at "2.6.0"
GitHub API request failed: DoesNotExist
```
I was having issues with generating ipa for App store submission, generating generic Archive so removed and installed carthage again.

**Comment by ikesyo** [comment] 2016-08-09 07:16
That is a duplicate of #1258 and already fixed in [0.16.1](https://github.com/Carthage/Carthage/releases/tag/0.16.1) or later (by #1262). Please update to a newer version. Closing.

**Closed by ikesyo** 2016-08-09 07:16 UTC
Labels: duplicate
