### ISSUE TITLE
Carthage strips symbols from dSYM files

### ISSUE THREAD

**Issue by naan** [Carthage/Carthage#2280] opened 2017-12-05 23:21 UTC
* `carthage version`:  0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No

**Cartfile**
N/A

Since Xcode 9, (this is my guess, I can't really tell exactly when this started happen) when I build a framework with Carthage for macOS, dSYM file gets empty even tho Xcode builds it correctly.

Here's what's happening in my log:

- Xcode create dSYM file using `dsymutil` (Default value of `DEBUG_INFORMATION_FORMAT` for release build is `DWARF with dSYM file`
- Xcode then strip symbol (Default value of `STRIP_INSTALLED_PRODUCT` for release build is `Yes`)
- Then Carthage tries to create a dSYM file from the stripped framework, which generates empty dSYM file. (inside of `createDebugInformation` function??)

However, iOS version of framework has a correct dSYM file even the framework itself is stripped. 

I haven't changed any related settings when I updated my project to Xcode 9, but I did change Xcode's recommended changes which might effect something here.

To avoid this, I have to disable `STRIP_INSTALLED_PRODUCT` to create correct dSYM file, then strip the symbol with a separate script.

**Comment by abrindam** [comment] 2018-01-03 05:37
+1, I am seeing what appears to be the same issue.

When I use Carthage to build frameworks for Mac, I do get a dSYM file but it's very small and doesn't seem to allow for debugging. I can't step into sources, and in Xcode, Debug -> Debug Workflow -> Shared Libraries shows "Debug Symbols" as "no" for any framework built by Carthage.

I reverted to Carthage 0.25 and the problem went away.

I strongly suspect this is caused by the changes from PR #2158 which switched to using "archive" instead of "build" to build frameworks. The "archive" command seems to strip the debug symbols before the dSYM can be created, as described by OP.

Unfortunately, I just convinced my team that breaking up our code into frameworks is the way to go, and now we can't debug anything because of this issue. So there is a minor torches and pitchforks situation. So any help would be greatly appreciated! :-)

**Comment by abrindam** [comment] 2018-01-03 05:38
#2295 may also be a dup of this?

**Comment by horse304** [comment] 2018-01-08 01:02
I got the same issue, and after a bit of debug, my suspect is:
- since v26 Carthage, the way build framework is change from "xcodebuild build" -> "xcodebuild archive"
- The binary build by "xcodebuild archive" will stripped debug symbols in binary file
- Then when create universal binary using "lipo -create" the universal binary will missing debug symbols for armv7, arm64
- Using "dsymutil" to generate dSYM from universal binary will cause missing debug symbols for armv7, arm64

**Comment by albert-so** [comment] 2018-01-08 21:24
👍 This affects my organization also

**Comment by mdiep** [comment] 2018-01-10 18:16
Pull requests welcome. ☺️

**Comment by abrindam** [comment] 2018-01-10 22:58
There seems to be some discrepancies here as to which platforms are affected.

The original report by @naan states this affects MacOS only.

My report confirms it affects MacOS and I made no statement on iOS.

However, @horse304 and @huy-le both claim this affects iOS, and @horse304's comment seem to even imply this does NOT affect MacOS.

Before anyone tries to tackle a fix, we should clarify the report first, since what it affects will likely influence the solution.

Can everyone please double-check and clarify their reports? I will do my own testing on iOS as well.

**Comment by abrindam** [comment] 2018-01-11 04:40
OK, I did some extensive testing, and it appears the issue does affect both MacOS and iOS.

However, for iOS, it only affects the slice of the dSYM for device builds (arm7/arm64). Simulator dSYMs (i386/x86_64) still contain valid debug info. For this reason, a cursory inspection of the "fat" iOS dSYM generated appears to have valid debug information, making it seem like this issue only affects MacOS (as seen by @naan). However, if you thin the dSYM with lipo, you will see that for arm7/arm64 there is no debug info (which, with the benefit of further understanding, is exactly what @horse304 was saying).

Hopefully this resolves the confusion in which platform this affects.

**Comment by abrindam** [comment] 2018-01-11 04:58
Moving on from the confusion, it makes sense that the simulator is not affected because that slice is not built with `xcodebuild archive` but rather with `xcodebuild build`. iOS device builds and all MacOS builds, on the other hand, do use `archive` and are affected.

As theorized by multiple people above, the `archive` command strips symbols when `build` does not. As far as I can understand, most projects have `STRIP_INSTALLED_PRODUCT` as true, but do not have `DEPLOYMENT_POSTPROCESSING` set to true, so a `build` operation does not strip. However, `DEPLOYMENT_POSTPROCESSING` seems to be magically true when you use `archive`, leading to stripping.

With that understanding, I came to an additional realization: with the `archive` change, the frameworks that Carthage builds are now stripped of symbols. Previously, it seems they were not and were expected to be stripped during the copy frameworks process of the consuming application. So I think a fundamental question is, is this something we want?

The above question is important because I think there are two reasonable ways to fix this issue. 

One option is to go in the direction of attempting to disable the stripping process of the `archive` operation, probably by passing additional flags to `xcodebuild`. If we did this, then the produced framework would unstripped, and the dSYM generation would succeed.

The second option is to simply use the dSYM generated by the `archive` operation, rather than having Carthage create one itself post-build. This is nice because it's one less thing for Carthage to do, but it leaves the produced framework stripped, which is a change from how things used to be.

If we can determine a strategy, I'd be happy to attempt a pull request.

@mdiep, @ikesyo, et al, thoughts?

**Comment by mdiep** [comment] 2018-01-19 17:57
I'm not sure how to fix this off the top of my head. If someone who is affected could find an approach that works and open a PR, that'd be ✨.

**Comment by abrindam** [comment] 2018-01-19 18:17
@mdiep As I said above, I believe either of my approaches would solve this problem, and I'd happily work on a PR for either one. But I'd like to know which one would be preferred. I guess if you don't have a preference, I'll flip a coin.

**Comment by isidrogc** [comment] 2018-01-22 19:55
Thanks, @abrindam for your commitment. I personally would vote for your option #1. Merely because I need the produced framework unstripped and the DSYM as it was.

**Comment by abrindam** [comment] 2018-01-22 21:10
Glad you said that, because option 1 is way easier to implement!

I've opened PR #2334.

**Comment by rudedogg** [comment] 2018-03-11 18:59
Thanks, https://github.com/Carthage/Carthage/pull/2361 fixes this for me. For others, you'll need to build from source until a new release is published

**Comment by blender** [comment] 2018-03-19 20:46
Fixed in 0.29.0

**Closed by blender** 2018-03-19 20:46 UTC

**Comment by sp0cket** [comment] 2018-03-21 16:01
Still occurring in 0.29.0

**Comment by blender** [comment] 2018-03-21 16:05
@sp0cket can you elaborate? 

`carthage build --no-skip-current` should not be striping anything, I just verified with Alamofire.

**Comment by sp0cket** [comment] 2018-03-21 16:44
Hi @blender, I just executed this command `carthage build --no-skip-current --platform ios`with Cartfile.resloved:

```
github "Alamofire/Alamofire" "4.7.0"
github "Moya/Moya" "10.0.1"
github "SnapKit/SnapKit" "4.0.0"
github "realm/realm-cocoa" "v3.3.0"
github "ReactiveX/RxSwift" "4.1.2"
...
```

And Run an app that use frameworks in Xcode. Open `Debug`>`Debug Worlkflow`>`Shared Libraries`

Name | Debug Symbols
-|-
Alamofire | Yes
Moya | Yes
SnapKit | Yes
**Realm** | **No**
**RealmSwift** | **No**
**RxCocoa** | **No**
**RxSwift** | **No**

**Comment by blender** [comment] 2018-03-21 16:49
@sp0cket  did you use `--no-use-binaries` ? If the dSYMs are not included in the archive carthage is downloading then you won't have them
