### ISSUE TITLE
A shell task failed with exit code 128 (Carthage 0.8)

### ISSUE THREAD

**Issue by marcpalmer** [Carthage/Carthage#694] opened 2015-08-20 01:01 UTC
I know this has cropped up in many other places but I'm seeing it now on some repos and not others.

```
$ carthage update --verbose
*** Fetching CocoaLumberjack
A shell task failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git
```

This is with Cartfile declaration:
```
git "https://github.com/CocoaLumberjack/CocoaLumberjack.git" == 2.0.1
# Other variations tried that also fail
# github "CocoaLumberjack/CocoaLumberjack" == 2.0.1
# github "CocoaLumberjack/CocoaLumberjack" ~> 2.0
# github "CocoaLumberjack/CocoaLumberjack"
```

It does not appear that CocoaLumberjack has its own Cartfile therefore it is unlikely to be the transitive Cartfile with non-existent branch problem.

Most of my repos result in this git error. However the system is not totally broken, as I can successfully get Carthage to checkout and build a fork of ObjectiveSugar that I created (to add the project + scheme requirements for Carthage) - https://github.com/marcpalmer/ObjectiveSugar

Any ideas? Am I doing something wrong? Note that the error is "instantaneous" — it does not appear to go the network and there is nothing related to "CocoaLumberjack" under ./Carthage

Version proof:
```
$ carthage version
0.8.0
$ git version
git version 2.5.0
```

**Comment by marcpalmer** [comment] 2015-08-20 01:14
Having the --verbose fix for git commands would likely help debug this a lot. Is it on master?

**Comment by furyu-ikeda-sho** [comment] 2015-08-20 01:14
This might be a dupe of #407 and #642. Removing `~/Library/Caches/org.carthage.CarthageKit` would help.

**Comment by marcpalmer** [comment] 2015-08-20 01:18
Removing CarthageKit did fix this problem.

This issue appears to be very common. Is there a plan to remove the support burden by fixing this? At the very most hideous, a fix that detects error 128 from the git task and flushes the cache folder automatically and tries again... if a smarter solution cannot be found.

**Comment by marcpalmer** [comment] 2015-08-20 11:10
Thanks for escalating it @ikesyo

**Closed** 2015-08-20 20:09 UTC
Labels: bug
