### ISSUE TITLE
Scheme tvOS is not currently configured for the build action

### ISSUE THREAD

**Issue by hectormatos2011** [Carthage/Carthage#1409] opened 2016-07-28 22:58 UTC
* `0.17.2`: 
* `Xcode 7.3.1 Build version 7D1014`: 
* Are you using `--no-build`? Nope!
* Are you using `--no-use-binaries`? Yep!
* Are you using `--use-submodules`? Nope!

**Cartfile**
```
github "SnapKit/SnapKit" == 0.19.1
github "n8armstrong/CalendarView" >= 1.0
github "SwiftyBeaver/SwiftyBeaver" == 0.4.1
github "Alamofire/Alamofire" == 3.2.1
github "AgileBits/onepassword-app-extension" "add-framework-support"
github "adjust/ios_sdk" 
github "KrakenDev/PrediKit" "swift2.1"
github "zendesk/zendesk_sdk_ios"

# A dependency for CalendarView
# (supplying version here that matches CV's podspec entry for SM)
github "akosma/SwiftMoment" ~> 0.3
github "dekatotoro/SlideMenuControllerSwift" == 2.0.6
github "kishikawakatsumi/KeychainAccess" == 2.3.4
```

**Carthage Output**
```
$ carthage bootstrap --no-use-binaries --platform ios
*** Checking out Alamofire at "3.2.1"
*** Checking out CalendarView at "1.1.2"
*** Checking out ios_sdk at "web-bridge4.8.0"
*** Checking out KeychainAccess at "v2.3.4"
*** Checking out onepassword-app-extension at "d98b056dbce81b34d321616c9724753034da1554"
*** Checking out PrediKit at "f0d6c68fa50dc70bf409025f05bab742bde981ef"
*** Checking out SlideMenuControllerSwift at "2.0.6"
*** Checking out SnapKit at "0.19.1"
*** Checking out SwiftMoment at "v0.3"
*** Checking out SwiftyBeaver at "0.4.1"
*** Checking out zendesk_sdk_ios at "1.6.2.1"
*** xcodebuild output can be found in /var/folders/vy/frkgkqq960dbl6x8815fl4g00000gp/T/carthage-xcodebuild.8hVLtC.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
2016-07-28 15:50:28.689 xcodebuild[83848:3612719] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SimplePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-28 15:50:28.694 xcodebuild[83848:3612719] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUFullIssueNavigator.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-28 15:50:28.695 xcodebuild[83848:3612719] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
/Users/hectormatos/Development/Xcode/LevelUp/Carthage/Checkouts/Alamofire/Source/ParameterEncoding.swift:247:29: warning: 'init(start:end:)' is deprecated: it will be removed in Swift 3.  Use the '..<' operator.
/Users/hectormatos/Development/Xcode/LevelUp/Carthage/Checkouts/Alamofire/Source/Request.swift:487:17: warning: keyword 'protocol' does not need to be escaped in argument list
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/hectormatos/Development/Xcode/LevelUp/Carthage/Checkouts/CalendarView/CalendarView/Carthage/Checkouts/SwiftMoment/SwiftMoment.xcworkspace -scheme SwiftMoment tvOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
2016-07-28 15:50:41.889 xcodebuild[84117:3613504] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SimplePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-28 15:50:41.892 xcodebuild[84117:3613504] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUFullIssueNavigator.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-28 15:50:41.893 xcodebuild[84117:3613504] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
xcodebuild: error: Scheme SwiftMoment tvOS is not currently configured for the build action.
```

**Comment by ikesyo** [comment] 2016-08-02 23:41
`SwiftMoment tvOS` target is added since v0.5 and does not exist in v0.3 which you use: https://github.com/akosma/SwiftMoment/commit/cf8da2d0743c8ba201e4eead04252386615b8408. Looks like this is a duplicate of https://github.com/Carthage/Carthage/issues/704#issuecomment-133852029, somehow you have a scheme which does not have the corresponding build target. Removing `SwiftMoment/SwiftMoment.xcodeproj/xcuserdata/$USER.xcuserdatad/xcschemes/SwiftMoment tvOS.xcscheme` might fix the issue.

Closing.

**Closed by ikesyo** 2016-08-02 23:41 UTC
