### ISSUE TITLE
Must specify two-factor authentication OTP code.

### ISSUE THREAD

**Issue by st3fan** [Carthage/Carthage#2096] opened 2017-08-03 13:22 UTC
Since a week or so, Carthage is spewing a ton of errors about *Must specify two-factor authentication OTP code.*.

We have never seen these before and it is not isolated to a single install, most of our team here is now getting these.

This may not be Carthage related directly. Maybe it is something that happened in a recent macOS update or in a Git update. But right now we have no good way to get past this.

The bigger question here is: why does Carthage need to authenticate? All the dependencies that we depend on are public, and can be checked out anonymous. Why does it even try 2FA or OTP?

* `carthage version`: 0.24
* `xcodebuild -version`: Xcode 8.3.3
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "getsentry/sentry-cocoa"             "3.2.1"
github "Alamofire/Alamofire"                ~> 4.0
github "sleroux/Deferred"                   "Swift3.0"
github "SnapKit/SnapKit"                    "3.1.2"
github "rs/SDWebImage"                      "3.7.4"
github "swisspol/GCDWebServer"              "3.3.2"
github "kif-framework/KIF"                  "v3.5.1"
github "adjust/ios_sdk"                     "v4.10.2"
github "AgileBits/onepassword-extension"    "new/carthage+ios10"
github "iziz/libPhoneNumber-iOS"            "0.9.2"
github "mozilla/readability"                "master"
github "jrendel/SwiftKeychainWrapper"       "3.0.1"
github "DaveWoodCom/XCGLogger"              "Version_4.0.0"
github "cezheng/Fuzi"                       "1.0.1"
github "SwiftyJSON/SwiftyJSON"              "3.1.4"
github "farhanpatel/JSONSchema.swift"       "master"
github "google/EarlGrey"                    "1.11.0"
github "Leanplum/Leanplum-iOS-SDK"          "2.0.1"
github "skyline75489/SwiftRouter"           "2.0.0"
```

**Carthage Output**
```
*** Skipped downloading SwiftRouter.framework binary due to the error:
	"Must specify two-factor authentication OTP code."
*** Checking out SwiftRouter at "2.0.0"
*** Skipped downloading Leanplum-iOS-SDK.framework binary due to the error:
	"Must specify two-factor authentication OTP code."
*** Checking out Leanplum-iOS-SDK at "2.0.1"

... and so on ...
```

**Comment by ikesyo** [comment] 2017-08-03 13:34
Is this a duplicate of #920? Also https://help.github.com/articles/caching-your-github-password-in-git/ will be a help.

> The bigger question here is: why does Carthage need to authenticate? All the dependencies that we depend on are public, and can be checked out anonymous. Why does it even try 2FA or OTP?

We are using GitHub APIs to detect/download binary frameworks attached to GitHub Releases and authenticated requests will avoid rate limit.

**Comment by mdiep** [comment] 2017-08-04 01:26
If you can do `git clone https://github.com/{some-private-repo}`, then this should go away.

**Closed by mdiep** 2017-08-04 01:26 UTC

**Comment by cliftonlabrum** [comment] 2017-10-09 20:30
@mdiep Do you mean to say we should put `git clone https://github.com/{some-private-repo}` for each repository in our **Cartfile**?

**Comment by mdiep** [comment] 2017-10-09 23:25
No, Carthage uses the authentication token that's available from `git`. If you can `git clone` a private repository over HTTPS, then Carthage can use the authenticated GitHub API.

**Comment by evgeniyd** [comment] 2017-11-15 07:49
@mdiep do you mean if `git` has an ability to clone repos, these messages may be ignored? This is my output:

    $ carthage bootstrap
    *** Skipped downloading unbox.framework binary due to the error:
    	"Must specify two-factor authentication OTP code."
    *** Checking out unbox at "2.1.1"
    *** Cloning unbox
    *** Skipped downloading Nuke.framework binary due to the error:
    	"Must specify two-factor authentication OTP code."
    *** Checking out Nuke at "4.1.2"
    *** Cloning Nuke
    *** Skipped downloading Result.framework binary due to the error:
    	"Must specify two-factor authentication OTP code."
    *** Checking out Result at "3.0.0"
    *** Cloning Result
    *** xcodebuild output can be found in /var/folders/kw/qs5mrnkd3g1c9nykh5_3p1sr0000gq/T/carthage-xcodebuild.V8n7hu.log
    *** Building scheme "Nuke iOS" in Nuke.xcodeproj
    *** Building scheme "Nuke macOS" in Nuke.xcodeproj
    *** Building scheme "Nuke watchOS" in Nuke.xcodeproj
    *** Building scheme "Nuke tvOS" in Nuke.xcodeproj
    *** Building scheme "Result-Mac" in Result.xcodeproj
    *** Building scheme "Result-iOS" in Result.xcodeproj
    *** Building scheme "Result-watchOS" in Result.xcodeproj
    *** Building scheme "Result-tvOS" in Result.xcodeproj
    *** Building scheme "Unbox-iOS" in Unbox.xcodeproj
    *** Building scheme "Unbox-OSX" in Unbox.xcodeproj
    *** Building scheme "Unbox-watchOS" in Unbox.xcodeproj
    *** Building scheme "Unbox-tvOS" in Unbox.xcodeproj

However, I can clone repos with `git` no problem.
