### ISSUE TITLE
Couldn't Generate Swift Representation

### ISSUE THREAD

**Issue by AndrewSB** [Carthage/Carthage#921] opened 2015-11-13 23:54 UTC
I recently switched from just dragging in my frameworks into XCode to using the recommended  copy-frameworks method in the README, but now whenever I click into a framework (by command clicking into a class name for example), I am greeted by this screen

<img width="780" alt="screen shot 2015-11-13 at 3 51 40 pm" src="https://cloud.githubusercontent.com/assets/3814772/11160428/7ea034cc-8a1e-11e5-90f8-02c787fb58aa.png">
I also can't debug code, if I try to do go a stack trace while in a breakpoint XCode crashes.

Searched around, wasn't really finding anything talking about this, any idea what it could be?

**Comment by NachoSoto** [comment] 2015-11-16 01:01
Thanks!

This is a duplicate of #832.

**Closed by NachoSoto** 2015-11-16 01:01 UTC

**Comment by byAmmerix** [comment] 2016-01-18 07:57
I have the same problem as @AndrewSB and tried to bypass the problem by using ```--no-use-binaries``` as mentioned in #832. However the error still occurs: 
<img width="312" alt="error message" src="https://cloud.githubusercontent.com/assets/7319168/12385864/9af2bc46-bdc0-11e5-8fc1-8c9bf5e29c11.png">

Carthage Version: 0.11.0
Build Phases:
<img width="882" alt="build phase 1" src="https://cloud.githubusercontent.com/assets/7319168/12385865/9af4261c-bdc0-11e5-9c3f-5b716470f2d8.png">
<img width="881" alt="build phase 2" src="https://cloud.githubusercontent.com/assets/7319168/12385863/9af22a7e-bdc0-11e5-940f-4bb6cd93bbd3.png">

Any idea how to fix this?

**Comment by AndrewSB** [comment] 2016-01-18 08:30
@byAmmerix try deleting your `Carthage/` directory and rerunning with `--no-use-binaries`. It's possible that one of the libraries you're using persisted from a non-`--no-use-binaries` update.

**Comment by byAmmerix** [comment] 2016-01-18 08:55
@AndrewSB I deleted ```Carthage/``` and executed ```carthage bootstrap --no-use-binaries```. Still the same problem: ```Couldn't Generate Swift Representation```.

**Comment by AndrewSB** [comment] 2016-01-18 09:04
@byAmmerix What libraries are you using? I'd image the problem stems from one specific library. What I'd recommend doing is adding your libraries one by one, and seeing after which one `SourceKit` breaks

**Comment by byAmmerix** [comment] 2016-01-18 09:29
@AndrewSB I'am only using Alamofire.

**Comment by AndrewSB** [comment] 2016-01-18 09:32
Are you installing the library as recommended? 
1. In linked libraries and frameworks
2. Copy in build phases

?

**Comment by byAmmerix** [comment] 2016-01-18 09:47
I hope 😄
Linked Libraries and Frameworks:
<img width="752" alt="linked libraries and frameworks" src="https://cloud.githubusercontent.com/assets/7319168/12387942/27b62294-bdd0-11e5-976e-7e759bc90476.png">
Build Phases:
<img width="766" alt="build phase" src="https://cloud.githubusercontent.com/assets/7319168/12387943/27b916b6-bdd0-11e5-8f6d-8abdb97103ff.png">

**Comment by AndrewSB** [comment] 2016-01-18 09:59
I'm out of ideas, would recommend creating an issue on Alamofire because this seems specific to them

**Comment by byAmmerix** [comment] 2016-01-18 12:00
I deleted the Derived Data folder and it also happens with other libraries. 
I created a new test project with the same configuration and everything is working fine.

**Comment by AndrewSB** [comment] 2016-01-18 12:08
Derived Data, totally forgot about that 🙄, I have a [script](https://github.com/AndrewSB/dotfiles/blob/master/zsh/functions/dderived) that runs every hour to delete it.

Glad you were able to figure it out 😊
