### ISSUE TITLE
Should be possible to build only new/updated dependencies.

### ISSUE THREAD

**Issue by zdavison** [Carthage/Carthage#432] opened 2015-04-21 16:18 UTC
Currently running `carthage update` will build all dependencies regardless of if you actually need to do that, this can slow down development when you really only need to rebuild a single dependency. 

Unless I'm being silly, and I can rebuild a single dependency already?

In addition to this, it's often not necessary to rebuild the dependencies of a dependency, eg:

If I'm building dependency A that depends on B,C,D,E, and I make changes to A, I don't really need to build B,C,D,E again. Some more granular control over this would be great, but I'm not sure what's possible right now.

I suppose I could build the dependency manually and update the Carthage'd product by hand, which would work for now.

**Comment by jspahrsummers** [comment] 2015-05-03 21:47
Xcode should be saving intermediate artifacts and reusing them, so the actual time spent _building_ should be minimal.

If you're seeing Carthage spend a lot of time on dependencies that don't need to be rebuilt, I'd suspect one of two things:

 1. We're spending too much time invoking `xcodebuild` repeatedly for projects that don't need rebuilding
 1. Xcode isn't reusing its artifacts as expected, for some reason

We'd have to investigate to see which it is, and I'm not sure how we would apply a fix for either. :confused:

**Comment by Thomvis** [comment] 2015-05-05 08:31
In my experience both things are true. Carthage seems to build every dependency all over again (for me) when calling `carthage update`. I'd assumed this was the intended behavior.

The second point becomes clear if you compare compile time when building with `carthage update` versus including the dependency's project in the main project and adding it as a target dependency. In the latter case, the dependency compiles way faster, probably because it is able to do incremental compilation & reuse its artefacts. This also makes development on a dependency while working on the main project (as described in the README section titled "Automatically rebuilding dependencies") nearly unusable. Would love to have a fix for this, let me know if I can help!

**Comment by zdavison** [comment] 2015-05-05 09:30
I have a project structure that includes a framework that is infrequently updated and versioned that we build using `carthage`, but it contains a lot of other dependencies (also built using `carthage`), updating this framework takes a nontrivial amount of time (5+ minutes) to rebuild with `carthage update` because it rebuilds each dependency from scratch every time.

I'd imagine that we could compare the `Cartfile.resolved` version number against the `Cartfile` version number (or latest if none specified), and if they are the same just use the existing artifact in `Carthage/Build`? If for some reason you need to force a build (eg, a version has sneakily updated its contents without incrementing) you can just empty the contents of that directory.

**Comment by jspahrsummers** [comment] 2015-05-05 14:45
If you run carthage with `--verbose`, do you see actual build output from `xcodebuild`, or does it seem like it's skipping most work?

> I'd imagine that we could compare the `Cartfile.resolved` version number against the `Cartfile` version number (or latest if none specified), and if they are the same just use the existing artifact in `Carthage/Build`?

That won't work—it should be supported to modify files in `Carthage/Checkouts` and see the results of those changes after a rebuild.

**Comment by zdavison** [comment] 2015-05-05 15:04
@jspahrsummers I'd imagine you'd want to support both behaviours. We check in our `Carthage/Build` dirs, but not our `Carthage/Checkouts` (personally i perceived this dir as a temporary build artefact, and it's too big to commit really anyway). So if this folder is empty, we'd force a full checkout/rebuild? 

I just ran `carthage update` twice in a row to see what I'd get, and indeed, a lot of the work is being skipped, but some of it isn't, I haven't verified, but my hunch is that dependencies of dependencies are rebuilding. This could be because my `DerivedData` folder is relative, not shared? Since the build dir the ends up as a subpath of Checkouts, not among the rest (although this would then persist anyway and be caught by the next iteration of `xcodebuild`?)

**Comment by jspahrsummers** [comment] 2015-05-08 04:36
I can see how a relative DerivedData folder could cause issues, but I haven't investigated myself. Any particular reason for not sharing it globally?

**Comment by zdavison** [comment] 2015-05-11 12:55
Just local style, we can flip to a global version. My own opinion is that if DerivedData is a singleton for your project, having a globally shared DerivedData is a singleton for all of your projects...

**Comment by jspahrsummers** [comment] 2015-05-15 04:42
Hopefully this sort of thing can be addressed when we tackle #459. Thanks for discussing it!

**Closed by jspahrsummers** 2015-05-15 04:42 UTC
Labels: bug, build

**Comment by cybertk** [comment] 2015-06-11 00:36
@jspahrsummers We checked in `Carthage/Build` dir. The problem in this case is that everything in this dir changed after invoke `carthage update` even when there is nothing updated.  This behaviour blocked us to checked in `Carthage/Build` dir since it get changed every time. And we cannot identify which framework is actually updated.

It can be simply reproduced by run `carthage update` two times after you checked `Carthage/Build` into repo.

**Comment by jspahrsummers** [comment] 2015-06-13 22:40
@cybertk See https://github.com/Carthage/Carthage/issues/548#issuecomment-111757681.
