### ISSUE TITLE
carthage malloc error - pointer being freed was not allocated

### ISSUE THREAD

**Issue by chrisballinger** [Carthage/Carthage#2263] opened 2017-11-18 21:07 UTC
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`?  yes

**Cartfile**
```
github "CocoaLumberjack/CocoaLumberjack" ~> 3.3.0
github "robbiehanson/CocoaAsyncSocket" ~> 7.6.2
github "robbiehanson/KissXML" ~> 5.2.1
github "chrisballinger/libidn-framework" ~> 1.33.1
```

**Carthage Output**
```
carthage bootstrap --no-use-binaries --cache-builds
*** Checking out KissXML at "5.2.1"
*** Checking out libidn-framework at "1.33.1"
*** Checking out CocoaLumberjack at "3.3.0"
*** Checking out CocoaAsyncSocket at "7.6.2"
*** No cache found for CocoaAsyncSocket, building with all downstream dependencies
*** No cache found for CocoaLumberjack, building with all downstream dependencies
*** No cache found for KissXML, building with all downstream dependencies
*** No cache found for libidn-framework, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/gn/qq8g0ndx6lbcw_ggg8lx0y780000gn/T/carthage-xcodebuild.fbnvLT.log
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "CocoaLumberjack-tvOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-macOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjack-macOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-watchOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjack-watchOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-tvOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-iOS" in Lumberjack.xcworkspace
*** Building scheme "KissXML (iOS)" in KissXML.xcodeproj
*** Building scheme "KissXML (tvOS)" in KissXML.xcodeproj
carthage(47182,0x7fff8a869340) malloc: *** error for object 0x1106c0c68: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Here's the end of the xcodebuild logs:
```
** ARCHIVE SUCCEEDED **

/usr/bin/xcrun xcodebuild -project /Users/chrisbal/Documents/ChatSecure/ChatSecure-iOS/Submodules/XMPPFramework/Carthage/Checkouts/KissXML/KissXML.xcodeproj -scheme KissXML\ (tvOS) -configuration Release -derivedDataPath /Users/chrisbal/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/KissXML/5.2.1 -sdk appletvsimulator -destination platform=tvOS\ Simulator,id=D9ECCBA8-CDA5-411F-AE63-341CE18EBF2E -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/chrisbal/Documents/ChatSecure/ChatSecure-iOS/Submodules/XMPPFramework/Carthage/Checkouts/KissXML)User defaults from command line:
    IDEDerivedDataPathOverride = /Users/chrisbal/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/KissXML/5.2.1

Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator11.1

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, id:D9ECCBA8-CDA5-411F-AE63-341CE18EBF2E }

	Available destinations for the "KissXML (tvOS)" scheme:
		{ platform:tvOS, id:f0545a07bebacba60f65faa93c3d92ddb3ef367d, name:Apple TV }

	Ineligible destinations for the "KissXML (tvOS)" scheme:
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
```

Here's the simulator list:
```
$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
== Runtimes ==
iOS 10.2 (10.2 - 14C89) - com.apple.CoreSimulator.SimRuntime.iOS-10-2
iOS 11.1 (11.1 - 15B87) - com.apple.CoreSimulator.SimRuntime.iOS-11-1
tvOS 11.1 (11.1 - 15J580) - com.apple.CoreSimulator.SimRuntime.tvOS-11-1
watchOS 4.1 (4.1 - 15R844) - com.apple.CoreSimulator.SimRuntime.watchOS-4-1
== Devices ==
-- iOS 10.2 --
    iPhone 5 (9293316F-F019-419C-8E84-F0273D99D38D) (Shutdown)
    iPhone 5s (433A0256-24B4-4CB0-8963-02DEDB454A8A) (Shutdown)
    iPhone 6 (59BDC4AF-B589-47BA-B193-F33301579D6F) (Shutdown)
    iPhone 6 Plus (9100105B-D5C4-49BE-ACFC-BCBE7D07A2FA) (Shutdown)
    iPhone 6s (40FCCB68-D8D2-4EE0-89E4-7680B94189D7) (Shutdown)
    iPhone 6s Plus (4642872A-99D6-426D-896C-5B7FEB66CE99) (Shutdown)
    iPhone 7 Plus (909C525A-87E6-44BC-8167-5E694C09EB17) (Shutdown)
    iPhone SE 10.2 (F68B08C5-B6E0-4279-B110-FB57F3A16DE5) (Shutdown)
    iPad Air (BC54AB14-10BD-422B-8695-40876CB5A7CF) (Shutdown)
    iPad Air 2 (AA86435A-05DA-4D4B-BD80-6EA40AB35777) (Shutdown)
    iPad Pro (9.7 inch) (E40D394E-01F4-4BE9-9BA2-24F3132CE83E) (Shutdown)
    iPad Pro (12.9 inch) (0E32D5EF-5641-454A-A8C3-5941881E4D27) (Shutdown)
-- iOS 11.1 --
    iPhone 5s (2B277773-8C12-4FE3-81A0-CB0E8005E630) (Shutdown)
    iPhone 6 (655EDFAB-E19A-45AE-AD58-C1C2252A6F93) (Shutdown)
    iPhone 6 Plus (BF545DF4-2010-4B59-9771-D3EDFA4912AA) (Shutdown)
    iPhone 6s (4186F966-6175-4CC2-BF33-CA87ED89A871) (Shutdown)
    iPhone 6s Plus (4118EA18-D25F-4BE4-A9ED-A5C2BEF1B0ED) (Shutdown)
    iPhone 7 (56301F1C-2751-4BDD-833A-A0484DEA0987) (Shutdown)
    iPhone 7 Plus (184207FD-8A57-4BD5-AC28-8C621BDB1BF7) (Shutdown)
    iPhone 8 (1F39A887-88DA-489F-B952-B5888889E15E) (Booted)
    iPhone 8 Plus (4762ED04-9F9D-4B18-9B9A-D8F527605E08) (Shutdown)
    iPhone SE (94471155-3080-420C-B586-BE7C42C3F508) (Shutdown)
    iPhone X (48D3E4DF-6DEF-42EA-8171-090D1A1CD3C1) (Shutdown)
    iPad Air (44B5A685-0CB5-4CD5-919E-21BBA6AD5B70) (Shutdown)
    iPad Air 2 (2C720AEC-F129-4BCB-9E83-3743F90FA6C3) (Shutdown)
    iPad (5th generation) (0A1338F0-1339-41BE-AFE4-9CEDC0244C0A) (Shutdown)
    iPad Pro (9.7-inch) (6F1508E2-0F64-405F-AC9E-1DAB1E69460F) (Shutdown)
    iPad Pro (12.9-inch) (47949AFD-D798-4C87-8CCA-400BD7A4CF6F) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (93DBEB7D-78FA-43CD-8015-CF6B6337A364) (Shutdown)
    iPad Pro (10.5-inch) (DA218742-7830-4354-9DCE-6A82DCAC3180) (Shutdown)
-- tvOS 11.1 --
    Apple TV (D9ECCBA8-CDA5-411F-AE63-341CE18EBF2E) (Shutdown)
    Apple TV 4K (29A10C88-99DC-4395-A439-3DE97E95AE67) (Shutdown)
    Apple TV 4K (at 1080p) (BC5BD0D4-52B4-4633-929F-12F78AE4D4FE) (Shutdown)
-- watchOS 4.1 --
    Apple Watch - 38mm (79D22811-66F2-44F7-9425-CF4D9D4F8681) (Shutdown)
    Apple Watch - 42mm (FAED1993-99DD-4634-8E1A-25C65FDEED59) (Shutdown)
    Apple Watch Series 2 - 38mm (92AF9D72-9E2D-49F3-8963-B99E1424D148) (Shutdown)
    Apple Watch Series 2 - 42mm (67404D7D-D2A5-41E0-BAA1-CD3B65FAA4F9) (Shutdown)
    Apple Watch Series 3 - 38mm (879580D7-7EDC-44B5-BE60-E308C0F0B60A) (Shutdown)
    Apple Watch Series 3 - 42mm (7D94603F-C945-4EC7-B04F-F6E13A835300) (Shutdown)
== Device Pairs ==
5B1724E5-4726-49C7-944F-F99FD4B977BD (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (92AF9D72-9E2D-49F3-8963-B99E1424D148) (Shutdown)
    Phone: iPhone 7 (56301F1C-2751-4BDD-833A-A0484DEA0987) (Shutdown)
8B9E0071-1AB0-41F3-9234-7FC016B7C272 (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (67404D7D-D2A5-41E0-BAA1-CD3B65FAA4F9) (Shutdown)
    Phone: iPhone 7 Plus (184207FD-8A57-4BD5-AC28-8C621BDB1BF7) (Shutdown)
8BE292F1-D399-4EBF-AE74-6855EE5DC551 (active, disconnected)
    Watch: Apple Watch Series 3 - 38mm (879580D7-7EDC-44B5-BE60-E308C0F0B60A) (Shutdown)
    Phone: iPhone 8 (1F39A887-88DA-489F-B952-B5888889E15E) (Booted)
8B031739-D876-4978-BB8A-0AD9FF7281D8 (active, disconnected)
    Watch: Apple Watch Series 3 - 42mm (7D94603F-C945-4EC7-B04F-F6E13A835300) (Shutdown)
    Phone: iPhone 8 Plus (4762ED04-9F9D-4B18-9B9A-D8F527605E08) (Shutdown)
```

**Comment by tamasprezi** [comment] 2017-11-21 08:48
Same issue here but with the following setup:

- carthage version: 0.23.0 (also reproduced with 0.26.2)
- xcodebuild -version: Xcode 9.0 Build version 9A235
- macOS 10.12.6
- `$ carthage bootstrap --platform macOS --cache-builds --use-ssh`

**Cartfile:**

```
github "SwiftyJSON/SwiftyJSON" ~> 3.1
github "<private repo>" "<commit hash>"
github "openid/AppAuth-iOS" ~> 0.9
```

**Cartfile.private:**

```
github "Quick/Quick" ~> 1.1
github "Quick/Nimble" ~> 7.0
github "lvsti/NimbleMockSix" ~> 0.1.3
```

The annoying thing is that even though the configuration remains the same, it's not happening all the time.

**Comment by ikesyo** [comment] 2017-11-25 05:47
Looks like this has been addressed on the upstream: https://github.com/robbiehanson/KissXML/pull/93. Closing.

**Closed by ikesyo** 2017-11-25 05:47 UTC

**Comment by chrisballinger** [comment] 2017-11-25 21:05
shouldnt this not cause such a spectacular crash in carthage though?
