### ISSUE TITLE
Builds failing on travis because of a permissions error

### ISSUE THREAD

**Issue by codeOfRobin** [Carthage/Carthage#2211] opened 2017-10-12 14:51 UTC
* `carthage version`: 
0.26.0
* `xcodebuild -version`: 
Xcode 9.0 
Build version 9A235
* Are you using `--no-build`?
 No
* Are you using `--no-use-binaries`? 
No
* Are you using `--use-submodules`? 
No
* Are you using `--cache-builds`? 
No

**Cartfile**
```
github "robb/Cartography"
github "matthewpalmer/Locksmith"
github "onevcat/Kingfisher"
github "alikaragoz/MCSwipeTableViewCell" >= 2.1.4
github "AgileBits/onepassword-extension" "add-framework-support"
github "SVProgressHUD/SVProgressHUD"
github "skywinder/ActionSheetPicker-3.0"
github "Kayako/KayakoMessengeriOS" "0.2.3"
github "pinterest/PINCache"
github "pinterest/PINRemoteImage"
github "texturegroup/texture" "master"
github "codeOfRobin/Components-Personal" "master"
github "codeOfRobin/DestructuredDwifft" "master"
github "codeOfRobin/KREClient" "master"
github "codeOfRobin/PresenceBar" "master"
github "codeOfRobin/ParkedTextField" "master"
```

**Carthage Output**
```
Failed to check out repository into /Users/travis/build/kayako/Kayako-Five-iOS-App/Carthage/Checkouts/PINCache-Texture: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “PINCache-Texture” in the folder “Checkouts”." UserInfo={NSFilePath=/Users/travis/build/kayako/Kayako-Five-iOS-App/Carthage/Checkouts/PINCache-Texture, NSUnderlyingError=0x7f9515466d10 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
```

I'm not sure what'd cause this error 🤔 . Could someone help me debug it?

**Comment by ikesyo** [comment] 2017-10-12 16:55
At the first glance that seems to be just a permission issue. So could you please make it sure that directory permissions on your repository are correctly set up.

And also if you could provide a minimal reproducible case (sample repository), that will be help.

**Comment by codeOfRobin** [comment] 2017-10-12 16:56
Yeah, that's the thing. Works locally on my machine, seems to mess up on the CI, which is very confusing. Should I consider raising an issue on https://github.com/travis-ci/travis-ci/issues ?

**Comment by ikesyo** [comment] 2017-10-12 17:01
I'm not sure about Travis so please feel free to do that.

**Comment by codeOfRobin** [comment] 2017-10-12 17:03
Cool 👍 . Meanwhile, I'll try making an example project for you guys to debug.

**Comment by ikesyo** [comment] 2017-10-24 04:51
Closing this for now.

**Closed by ikesyo** 2017-10-24 04:51 UTC

**Comment by codeOfRobin** [comment] 2017-10-24 14:56
Ah, I forgot about this 😬 . Sorry about that. Was an issue with travis and we resolved it with them. Thanks for the help!
