### ISSUE TITLE
Error "dependency has no shared framework schemes for any of the platforms: tvOS"

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#1372] opened 2016-06-25 22:50 UTC
* `carthage version`: 0.17.1
* `xcodebuild -version`: Xcode 7.3.1 (7D1014)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* What command are you running? `carthage update AsyncImageView --platform tvos`

**Cartfile**
```
github "NachoSoto/AsyncImageView" "master"
```

**Carthage Output**
```
*** Skipped building AsyncImageView due to the error:
Dependency "AsyncImageView" has no shared framework schemes for any of the platforms: tvOS
```

**Project configuration**

<img width="215" alt="screen shot 2016-06-25 at 15 46 55" src="https://cloud.githubusercontent.com/assets/685609/16359511/10ef1a40-3aec-11e6-8de7-0d10fd27ba2d.png">
<img width="930" alt="screen shot 2016-06-25 at 15 47 40" src="https://cloud.githubusercontent.com/assets/685609/16359514/4f786604-3aec-11e6-90c7-7c53b3c9ced8.png">

**Notes**

- I haven't changed anything in the target or scheme, so this seems to be a regression.
- The `iOS` target builds fine.

**Comment by ikesyo** [comment] 2016-06-28 16:41
`AsyncImageView-tvOS` is not configured correctly:

- `SDKROOT` should be `appletvos`
- `TARGETED_DEVICE_FAMILY` should be `3`

**Comment by ikesyo** [comment] 2016-06-28 16:57
So it seems that this is really the case of #467.

**Comment by ikesyo** [comment] 2016-07-01 13:19
Opened https://github.com/NachoSoto/AsyncImageView/pull/29.

**Comment by NachoSoto** [comment] 2016-07-01 19:03
Ooooh. How was this even working before? Thanks @ikesyo :)

**Comment by ikesyo** [comment] 2016-07-15 14:21
Closing this as a duplicate of #467.

**Closed by ikesyo** 2016-07-15 14:21 UTC
Labels: bug, build
