### ISSUE TITLE
Why aren't nested dependencies built?

### ISSUE THREAD

**Issue by memmons-ntst** [Carthage/Carthage#917] opened 2015-11-12 16:17 UTC
If I have a framework project -- A.framework -- that uses carthage and that project has a cartfile that looks like this:

    github "thoughtbot/Argo" ~> 2.2

And I have a project called B that uses the A framework. It's included in the project's cartfile like this:

     github "someUser/A" ~> 1.0

When I `carthage update`, shouldn't carthage download and build Argo before attempting to build someUser/A? Otherwise someUser/A's build will fail. Currently carthage fails to do this at all. 

What's the magic sauce to force carthage to build nested dependencies before attempting to build the frameworks that rely on the nested dependencies?

Maybe the expectation is that all frameworks will be linked at the application level? But even then, the build order seems non-deterministic, so some frameworks that rely on frameworks above it in the cartfile list are built first causing the build to fail.

**Comment by mdiep** [comment] 2015-11-12 19:36
> Maybe the expectation is that all frameworks will be linked at the application level?

That is the expectation, yes.

But transitive dependencies should get built in the correct order. It's still non-deterministic because the sorting isn't stable, but dependencies should always get built first.

If you can build a reproducible case, that would be very helpful.

**Comment by memmons-ntst** [comment] 2015-11-13 16:26
Here is the cartfile: 
```
github "ReactiveCocoa/ReactiveCocoa" ~> 3.0
github "thoughtbot/Argo" ~> 1.0.3
github "jverdi/JVFloatLabeledTextField" ~> 1.1.0
github "privateRepo/FormKit" ~> 0.0.1
git "someOtherPrivateRepo/CareKit.git" >= 1.0.10
```
The private repos require `JVFloatLabeledTextField`, but carthage builds the private repos first, so the build fails.

**Comment by ikesyo** [comment] 2016-02-12 17:16
Is there any change with the latest version of Carthage?

**Comment by ikesyo** [comment] 2016-05-03 07:44
Maybe the Cartfile of `someOtherPrivateRepo/CareKit.git` is not in the root directory of the repo, I think. Closing.

**Closed by ikesyo** 2016-05-03 07:44 UTC
Labels: question

**Comment by eonist** [comment] 2017-02-03 22:52
@memmons-ntst I woundered the same thing, the solution: see: ``1. The Automated workflow:`` http://stylekit.org/blog/2017/02/03/Carthage-and-nested-frameworks/
