### ISSUE TITLE
Any new release plan

### ISSUE THREAD

**Issue by keithcml** [Carthage/Carthage#2977] opened 2020-04-23 03:26 UTC
I saw there are several good PR merged but no new release still.

May I know the timeline on it?

And is it safe to use master branch instead of 0.34.0?

**Comment by tmspzz** [comment] 2020-04-27 14:06
duplicate of #2927

**Closed by tmspzz** 2020-04-27 14:06 UTC

**Comment by sam-w** [comment] 2020-06-22 08:18
@keithcml in case you haven't seen, 0.35.0 is now released :)
