### ISSUE TITLE
Error when using --cache-builds

### ISSUE THREAD

**Issue by alickbass** [Carthage/Carthage#1822] opened 2017-03-07 15:29 UTC
* `carthage version`: 0.20.0
* `xcodebuild -version`: Xcode 8.2.1 Build version 8C1002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries` yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

**Cartfile**
```
github "Alamofire/Alamofire"
github "ReactiveX/RxSwift"
github "alickbass/SwiftyJSONModel"
```

**Carthage Output**
```
carthage bootstrap --no-use-binaries --platform iOS --cache-builds
*** Checking out Alamofire at "4.4.0"
*** Checking out RxSwift at "3.2.0"
*** Checking out SwiftyJSON at "3.1.4"
*** Checking out SwiftyJSONModel at "0.1.0"
Failed to write to /Users/myUser/Desktop/apps/ApiConnector/Carthage/Checkouts/SwiftyJSONModel/Carthage/Checkouts/SwiftyJSON: 
Error Domain=NSCocoaErrorDomain Code=516 "The file “SwiftyJSON” couldn’t be saved in the folder “Checkouts” because a file with the same name already exists." 
UserInfo={NSFilePath=/Users/myUser/Desktop/apps/ApiConnector/Carthage/Checkouts/SwiftyJSONModel/Carthage/Checkouts/SwiftyJSON, NSUnderlyingError=0x7fecaccb1e90 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
```
Whenever I try to build the second time, when the cache is available.

I guess the problem is that `SwiftyJSONModel` has a dependecy of `SwiftyJSON`

**Comment by ikesyo** [comment] 2017-03-07 15:42
This is a duplicate of #1794. Please follow the issue instead. 🙏

**Closed by ikesyo** 2017-03-07 15:42 UTC
Labels: duplicate
