### ISSUE TITLE
xcodebuild timeout while trying to read AWSiOSSDKv2.xcodeproj with carthage < v0.29

### ISSUE THREAD

**Issue by mlfarrell** [Carthage/Carthage#2338] opened 2018-01-30 02:35 UTC
READ THE ENTIRE THING BEFORE YOU MARK THIS AS A DUPLICATE

* `carthage version`: 
0.26
* `xcodebuild -version`: 
no idea
* Are you using `--cache-builds`? 
Yes

**Cartfile**
```
github "aws/aws-sdk-ios" ~> 2.5
```

**Carthage Output**
```
xcodebuild timeout while trying to read AWSiOSSDKv2.xcodeproj
```

**I'm stuck with the installed version on nevercode's severs.  Before I complain to them to upgrade, has this issue been altered/changed since 0.26?  If not, then I still have a problem!  Ideally we need a command line or environment variable argument to configure this delay!  Having to edit and recompile carthage to do this is not a solution!**

**Comment by jdhealy** [comment] 2018-01-30 03:59
> has this issue been altered/changed since `0.26`

The [timeout and retry-attempts `carthage` applies for `xcodebuild clean -showBuildSettings …` has not changed since `0.26`](https://github.com/Carthage/Carthage/blame/19e584623e548de68f424ea5c5dc4c081d750112/Source/CarthageKit/BuildSettings.swift#L61-L62). Check [the release notes for future changes](https://github.com/Carthage/Carthage/releases), such a change would surely be included there. Important to note: whether the (wall clock) limit gets hit may vary based on Xcode version and the particular [checked-out working tree](https://git-scm.com/docs/gitglossary#gitglossary-aiddefworkingtreeaworkingtree) of a repository.

> I'm stuck with the installed version on nevercode's severs.… Having to edit and recompile carthage to do this is not a solution!

For my clarification, you’re using [nevercode.io](https://developer.nevercode.io/docs/custom-build-steps) and some set of their limitations require not forking `carthage`?

That should be doable: one strategy would be modifying @raid5’s [script to delete unused `AWSiOSSDKv2.xcodeproj` schemes](https://github.com/Carthage/Carthage/issues/1227#issuecomment-353126948). Would that work under the set of limitations?

**Comment by mlfarrell** [comment] 2018-01-30 04:27
Yes nevercode.io.  They have installed Carthage themselves. I mean, I could commit a Carthage binary to our repo,  but that would be a ridiculous hack in my opinion. And I don’t even know what I would edit in the Carthage code to fix the problem.

I’ll take a look at that script tomorrow. I’m not sure how I can execute it however, since I’d have to insert the script execution between the Carthage checkout and the build, which happens all at once

**Comment by mlfarrell** [comment] 2018-01-30 18:08
Is there an option to embed custom script execution as a carthage post checkout, pre build step?

**Comment by mdiep** [comment] 2018-01-30 20:03
> Is there an option to embed custom script execution as a carthage post checkout, pre build step?

No

**Comment by jdhealy** [comment] 2018-01-30 20:16
While the option (with `carthage` flags) doesn’t exist, the [previously mentioned script](https://github.com/Carthage/Carthage/issues/2338#issuecomment-361470047) does a [`carthage update --no-build`¹, then has side-effectual scripting, then `carthage build`](https://gist.github.com/raid5/ae5c6787926e7cdd4412ad6bb4456a79#file-buddybuild_carthage_command-sh-L3-L19).

Would that work for your purposes?

⑴: Alternatively, `carthage bootstrap --no-build`.

**Comment by mlfarrell** [comment] 2018-01-31 00:53
Maybe...  unless both steps incur alot of overhead together (trying to keep the build times down on nevercode).

Either way, it wouldn't hurt to have configurable shell script custom build steps (at various stages of the pipeline).  Consider that a feature request :p

**Comment by mlfarrell** [comment] 2018-02-03 00:48
@raid5 thanks!

**Comment by mattgallagher** [comment] 2018-03-09 00:33
I get the same error on the same project file (using Xcode 9.3 beta 4, carthage 0.28.0) and the problem is fixed by deleting Carthage/Checkouts/aws-sdk-ios/AWSAuthSDK (and the xcodeproj file it contains). Fortunately I don't need the contents of that project (3rd party authorization).

For some reason, when carthage tries to open aws-sdk-ios/AWSAuthSDK/AWSAuthSDK.xcodeproj it spawns 30-40 instances of xcodebuild on my tired old 2 core laptop and nothing happens until the timeout message. This happens *before* any build messages appear (it happens during *opening* of the project). Something specific in that project is messing with either xcodebuild or carthage.

**Comment by mdiep** [comment] 2018-03-09 01:09
> For some reason, when carthage tries to open aws-sdk-ios/AWSAuthSDK/AWSAuthSDK.xcodeproj it spawns 30-40 instances of xcodebuild on my tired old 2 core laptop – slowing everything to a crawl – and nothing happens until the timeout message. This happens before any build messages appear (it happens during opening of the project). Something specific in that project is messing with either xcodebuild or carthage.

That sounds like it might be fixed in the next release of Carthage by https://github.com/Carthage/Carthage/pull/2343.

**Comment by mattgallagher** [comment] 2018-03-19 23:13
@mdiep I just wanted to confirm: Carthage 0.29 fixes the problem I described. Thanks!

**Comment by mdiep** [comment] 2018-03-20 00:26
Awesome! Thanks for reporting back @mattgallagher.

**Comment by jamesone** [comment] 2018-03-22 05:34
@mlfarrell How did you find setting up Carthage on Nevercode? I'm about to start this process. Any tips?

**Closed** 2018-04-04 14:56 UTC
