### ISSUE TITLE
Carthage 0.26.0 - Build Failure with Symlink

### ISSUE THREAD

**Issue by aaroncrespo** [Carthage/Carthage#2208] opened 2017-10-11 16:27 UTC
* `carthage version`: 0.26.0
* `xcodebuild -version`: 9A235
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`?  NO

**Cartfile**
```
github "https://github.com/fpillet/NSLogger" "master"
```

**Carthage Output**
```shell
$ carthage build --no-skip-current

*** xcodebuild output can be found in /var/folders/vx/hmnt9s3x0qn_bcdjc_9qrcnsgp2kq9/T/carthage-xcodebuild.8aAdJg.log
*** Building scheme "NSLoggerUser" in NSLoggerUser.xcworkspace
Failed to read file or folder at /Users/me/NSLoggerUser/Carthage/Build/Mac/NSLoggerUser.framework
```

In a project with multiple slices (or maybe just the addition of a macOS slice say. 
It appears to not follow symlinks or properly create the symlinks inside arg least the Mac Build folder:

I am also seeing it in projects with no Dependencies but the same error different path and watchOS:
```shell
Failed to read file or folder at /Users/me/Library/Developer/Xcode/DerivedData/MultiPlatform-evjrpyhcrkoiafbeszfzoyzgosqc/Build/Intermediates.noindex/ArchiveIntermediates/MultiPlatform/BuildProductsPath/Release-watchos/MultiPlatform.framework
```

**Comment by SeanRobinson159** [comment] 2017-10-11 19:37
I am having the same issue, with a different framework (my private framework). I am using the commands `carthage update` and `carthage bootstrap` same results as yours. It was working right before I updated carthage.

- macOS High Sierra version 10.13 (17A405)
- Xcode version 9.0 (9A235)
- Carthage version 0.26.0

**Comment by aaroncrespo** [comment] 2017-10-11 20:13
Having issues with sharable repro steps but one thing I think is required is one library/framework that is built for multiple platforms.

**Comment by SeanRobinson159** [comment] 2017-10-11 20:16
My framework is only for iOS.

**Comment by aaroncrespo** [comment] 2017-10-11 20:17
Whoops, there goes that idea.

**Comment by NicholasTD07** [comment] 2017-10-12 05:01
Getting the same error trying to build SnapKit.

Here's my config

    carthage version: 0.26.0
    xcodebuild -version: Xcode 9.0
    Are you using --no-build? No
    Are you using --no-use-binaries? YES
    Are you using --use-submodules? NO
    Are you using --cache-builds? NO

```
github "SnapKit/SnapKit" "3.0.2"
```

I have rolled back to 0.25.0 to temporarily work around this issue.

**Comment by ikesyo** [comment] 2017-10-12 10:53
Closing this as a duplicate of #2207.

**Closed by ikesyo** 2017-10-12 10:53 UTC
Labels: bug, build, duplicate
