### ISSUE TITLE
Binary dependencies not showing under working directory

### ISSUE THREAD

**Issue by KoCMoHaBTa** [Carthage/Carthage#2525] opened 2018-07-21 14:12 UTC
* carthage install method: homebrew
* `which carthage`: ~/Homebrew/homebrew-master/bin/carthage
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 9.4.1
* Are you using `--no-build`? yes
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
binary "crashlytics.json"
github "Alamofire/Alamofire" ~> 4.4
```

**Carthage Output**
```
*** Downloading binary-only framework crashlytics at "file:///Users/milen.halachev/Downloads/gg/crashlytics.json"
*** Fetching Alamofire
*** Checking out Alamofire at "4.7.3"
```

**crashlytics.json**
```
{
    "3.10.5": "https://s3.amazonaws.com/kits-crashlytics-com/ios/com.twitter.crashlytics.ios/3.10.5/com.crashlytics.ios-manual.zip"
}
```

**Actual outcome**
Carthage did or did not provide the downloaded binary dependency in the working directory when using `carthage update --no-build`.
The github dependency appears correctly under `Carthage/Checkouts` folder.
The binary dependency is missing.

**Expected outcome**
Carthage should provide the downloaded binary dependency in the working directory when using `carthage update --no-build`.
The github dependency appears correctly under `Carthage/Checkouts` folder.
The binary dependency should appear somewhere inside the Carthage directory.

**Comment by ikesyo** [comment] 2018-07-21 17:48
This is a duplicate of #2449.

**Closed by ikesyo** 2018-07-21 17:48 UTC
