### ISSUE TITLE
.pkg file installation shows unidentified develoeper dialog

### ISSUE THREAD

**Issue by ivan-konov** [Carthage/Carthage#1387] opened 2016-07-09 18:08 UTC
* `carthage version`: 0.17.x

![screen shot 2016-07-09 at 21 05 57](https://cloud.githubusercontent.com/assets/5302709/16709424/337d1c0a-4619-11e6-90f5-8080553dba28.png)

This is the first time I see this dialog installing Carthage that way. I know it is no brainer but IMO things better be clean and by the book :)

**Comment by ikesyo** [comment] 2016-07-10 12:46
This is a duplicate of #142, #577, #813 and #1186. Closing.

**Closed by ikesyo** 2016-07-10 12:46 UTC
