### ISSUE TITLE
Incorrect 'carthage update {dependency}'

### ISSUE THREAD

**Issue by dmoroz0v** [Carthage/Carthage#2441] opened 2018-05-03 13:56 UTC
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

**Cartfile**
```
github "SnapKit/Masonry"

git "ssh://git@my-domain/mip/myrepo.git" "master"
```

**Call in termanal**
```
carthage update myrepo --platform iOS
```

**Carthage Output**
```
*** Fetching Masonry
*** Fetching myrepo
```

**Expected outcome**
Carthage should fetching only myrepo

Carthage version 0.29.0

Thanks!

**Comment by ikesyo** [comment] 2018-05-03 14:09
This is a duplicate of https://github.com/Carthage/Carthage/issues/1081.

**Closed by ikesyo** 2018-05-03 14:09 UTC
