### ISSUE TITLE
Carthage crash bootstrapping CocoaLumberjack

### ISSUE THREAD

**Issue by fdstevex** [Carthage/Carthage#1286] opened 2016-04-30 10:52 UTC
* `carthage version`: 0.9.1
* `xcodebuild -version`: 7.3, Xcode 7.37D175
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "robbiehanson/CocoaAsyncSocket" "master"
github "CocoaLumberjack/CocoaLumberjack"
```

**Carthage Output**
```
$ carthage update
*** Fetching CocoaLumberjack
*** Fetching CocoaAsyncSocket
*** Checking out CocoaLumberjack at "2.2.0"
*** Checking out CocoaAsyncSocket at "562bae6af6dbd7e1891293dae20b9f79a2fd7228"
*** xcodebuild output can be found in /var/folders/jl/drpb8yl909q4l6n3qs71tw600000gq/T/carthage-xcodebuild.QjFZ2Q.log
*** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "CocoaLumberjackSwift" in Lumberjack.xcworkspace
fatal error: SDK count 3 in scheme CocoaLumberjackSwift is not supported: file /Users/mdiep/Repositories/Carthage/Carthage/Source/CarthageKit/Xcode.swift, line 959

Caught signal triggered by the Swift runtime!
Illegal instruction: 4

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.


Caught signal triggered by the Swift runtime!
Illegal instruction: 4

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

Caught signal triggered by the Swift runtime!
Illegal instruction: 4

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

Caught signal triggered by the Swift runtime!
Illegal instruction: 4

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

^C
```

**Comment by ikesyo** [comment] 2016-04-30 14:42
This is a duplicate of #776 and fortunately, that is already fixed. Please update to the latest release. Closing.

**Closed by ikesyo** 2016-04-30 14:42 UTC
