### ISSUE TITLE
carthage with xcode 7.1.1 won't copy frameworks to Build folder

### ISSUE THREAD

**Issue by chainone** [Carthage/Carthage#964] opened 2015-12-03 09:32 UTC
Take "github "ankurp/Dollar.swift" ~> 4.0.1" for example
there are two shared schemas, however only Cent.framework shows up in Build folder for iOS platform

command line I use:  carthage update --platform ios --use-submodules

**Comment by chainone** [comment] 2015-12-21 09:43
Any update?

**Comment by ikesyo** [comment] 2015-12-21 10:16
This is a dupe of #644 and already tackled in #892.

**Closed by ikesyo** 2015-12-21 10:16 UTC
Labels: duplicate
