### ISSUE TITLE
Only build 

### ISSUE THREAD

**Issue by klundberg** [Carthage/Carthage#1934] opened 2017-05-16 15:46 UTC
* `carthage version`: 0.22
* `xcodebuild -version`: 8.3.2
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

**Cartfile**
```
github "ReactiveX/RxSwift"
```

**Carthage Output**
```
*** Checking out RxSwift at "3.4.1"
*** xcodebuild output can be found in /var/folders/_6/x99xj8f55_1fqyl24cqzsypw00344n/T/carthage-xcodebuild.XCja76.log
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
*** Building scheme "RxCocoa-iOS" in Rx.xcworkspace
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
*** Building scheme "RxTests-iOS" in Rx.xcworkspace
```

When I use a dependency like RxSwift above, which has 4 framework schemes shared, Carthage builds all 4 of them. I would like to have the ability to specify exactly which schemes I want to build, in case I don't want all of them (in this case, RxSwift and RxCocoa are what I'd want to use). Is it possible to add this sort of feature to Carthage and to extend the Cartfile syntax to allow for this in some capacity?

**Comment by ikesyo** [comment] 2017-05-16 15:50
Duplicate of #1227.

**Closed by ikesyo** 2017-05-16 15:50 UTC
