### ISSUE TITLE
Carthage update error "A shell task failed with exit code 128"

### ISSUE THREAD

**Issue by wsof401** [Carthage/Carthage#642] opened 2015-07-27 05:34 UTC
I add the line  github "ReactiveCocoa/ReactiveCocoa" "v3.0-RC.1" 
output
*** Fetching ReactiveCocoa
*** Fetching Result

A shell task failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git

**Comment by ikesyo** [comment] 2015-07-27 05:40
ref: ReactiveCocoa/ReactiveCocoa#2219.

**Comment by ikesyo** [comment] 2015-07-27 05:55
This might be a dupe of #407 (and #398?). Could you please check that issues?

**Comment by wsof401** [comment] 2015-07-27 07:28
@ikesyo  Thanks a lot, It solved my probelem

**Closed** 2015-07-27 07:32 UTC
Labels: bug

**Comment by ikesyo** [comment] 2015-07-27 07:35
My pleasure. :smiley:

**Comment by ariok** [comment] 2016-03-11 17:58
It seems that the issue is still there. 
I've included Quick and Nimble into my Cartfile.private file. Here is the result.
```
*** Fetching Nimble
*** Fetching Quick
*** Checking out Nimble at "v3.1.0"
*** Checking out Quick at "v0.9.1"
A shell task failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git
```
I'm using this command: 
`carthage update --platform iOS --use-submodules --no-use-binaries` and the carthage ~/Library/cache folder is clean.
