### ISSUE TITLE
Inconsistent dependency resolution

### ISSUE THREAD

**Issue by wtmoose** [Carthage/Carthage#479] opened 2015-05-18 23:32 UTC
Currently using 0.7.3 and I'm seeing inconsistent dependency resolution, such that multiple different versions of the same dependency are being fetched.

__Example 1:__

1. Create a new Xcode Project
2. Add a Cartfile with the following

    > github "ReactKit/ReactKit" == 0.10.0

3. Run `carthage update`

Carthage downloads two versions of the SwiftTask dependency, 3.0.0 and 3.1.0. ReactKit's Cartfile says:

>github "ReactKit/SwiftTask" ~> 3.0.0

And the top level, version 3.1.0 is resolved and checked out. However, inside `Carthage/Checkouts/ReactKit`, version 3.0.0 is resolved and checked out. This problem causes incorrect/incompatible frameworks to be built.

__Example 2:__

1. Create a new Xcode Project
2. Add a Cartfile with the following

    >github "ReactKit/ReactKit"

3. Run `carthage update`

Carthage apparently stalls or hangs with the following output:

>*** Fetching ReactKit
>*** Fetching SwiftTask
>*** Fetching SwiftState
>*** Checking out SwiftTask at "3.1.0"
>*** Fetching SwiftState
>*** Checking out ReactKit at "0.10.0"
>*** Fetching SwiftState
>*** Fetching SwiftState
>*** Fetching SwiftState
>*** Fetching SwiftState
>*** Fetching SwiftState

**Comment by inamiy** [comment] 2015-05-19 00:57
I also reproduced the same bug in Carthage 0.7.3,
but not for older version 0.6.2.

**Comment by jspahrsummers** [comment] 2015-05-19 23:00
> However, inside `Carthage/Checkouts/ReactKit`, version 3.0.0 is resolved and checked out.

This is correct behavior, because ReactKit uses SwiftTask as a submodule. Carthage isn't responsible for picking the submodule version—it's part of the repository.

It should be fine as long as ABI compatibility is maintained, and only one copy makes it into the final app bundle (which is what happens when you use Carthage's copy).

> Carthage apparently stalls or hangs with the following output:

This sounds like the same issue as #448, which should be fixed in our next release. Sorry about that!

**Closed by jspahrsummers** 2015-05-19 23:00 UTC

**Comment by wtmoose** [comment] 2015-05-20 02:39
@jspahrsummers  thanks for the explanation!

>It should be fine as long as ABI compatibility is maintained, and only one copy makes it into the final app bundle (which is what happens when you use Carthage's copy).

From a perfectly clean setup, I didn't have issues. But eventually Xcode would get in a state where it was trying to link against the wrong framework and would generate errors. It was happening most frequently with the IBDesignables build. I didn't figure out why it was doing this, though, and I don't have reproduction steps. Moving on.
