### ISSUE TITLE
[DATA LOSS] Carthage update without warning deletes any change made to a framework in the Checkouts folder

### ISSUE THREAD

**Issue by einsteinx2** [Carthage/Carthage#1157] opened 2016-02-25 21:45 UTC
In our project, we use Carthage for dependency management. I usually use all frameworks pre-compiled as per standard Carthage behavior, however one framework I made frequent code changes to, so I have it pulled into the project as a subproject.

I found out the hard way just now when adding a new framework to the project that running carthage update will immediately delete any changes made in the Checkouts folder without any warning.

Thankfully I had a Time Machine backup, so nothing was lost, but it was a really close call.

I understand this is not the standard way of doing things, but Carthage should really give some kind of warning prompt in this case or fail. It should definitely not just immediately delete the changes.

I'm also open to any recommendations on how to better use Carthage in my use case.

**Comment by mdiep** [comment] 2016-02-26 13:31
This is a duplicate of #626.

**Closed by mdiep** 2016-02-26 13:31 UTC
