### ISSUE TITLE
Updating single dependency fetches and clones all dependencies in the Cartfile

### ISSUE THREAD

**Issue by GRiMe2D** [Carthage/Carthage#2291] opened 2017-12-14 10:58 UTC
* `carthage version`: 0.27.0
* `xcodebuild -version`: Xcode 9.2, Build version 9C40b
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO

**Cartfile**
```
github "ReactiveX/RxSwift" ~> 4.0
github "aabbcc-double/ABCDServiceFoundation" ~> 1.0
github "AliSoftware/Dip" ~> 6.0
github "mac-cain13/R.swift.Library" ~> 4.0
github "JohnSundell/Wrap" ~> 3.0
```

**Carthage Output**
```
$ carthage update Wrap --platform iOS
*** Cloning ABCDServiceFoundation
*** Cloning Wrap
*** Cloning R.swift.Library
*** Cloning Dip
*** Cloning RxSwift
*** Checking out Wrap at "3.0.1"
*** xcodebuild output can be found in /var/folders/_6/8j0kk_dx7vd50t4k6r5x_5100000gn/T/carthage-xcodebuild.sBOq7Y.log
*** Building scheme "Wrap-iOS" in Wrap.xcodeproj
```

Was expecting to only cloning Wrap and building

**Comment by ikesyo** [comment] 2017-12-14 11:30
This is a duplicate of #1081.

**Closed by ikesyo** 2017-12-14 11:30 UTC
