### ISSUE TITLE
carthage malloc: pointer being freed was not allocated

### ISSUE THREAD

**Issue by mt00chikin** [Carthage/Carthage#2320] opened 2018-01-11 20:41 UTC
* `carthage version`: 0.26.2, 0.27.0 
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "ReactiveX/RxSwift" ~> 4.0
github "SwiftKit/Cuckoo" ~> 0.10.1
github "Swinject/Swinject" ~> 2.0.0
```

**Carthage Output**
```
carthage bootstrap --platform iOS
*** Checking out Swinject at "2.1.1"
*** Downloading RxSwift.framework binary at "Spread.1"
*** Checking out Cuckoo at "0.10.2"
*** xcodebuild output can be found in /var/folders/r5/q19rtml90xv396zgv1xpf18s0pw573/T/carthage-xcodebuild.OKFB1Q.log
*** Building scheme "Cuckoo" in Cuckoo.xcworkspace
*** Building scheme "Cuckoo+Run" in Cuckoo.xcworkspace
*** Building scheme "Swinject-iOS" in Swinject.xcodeproj
carthage(12042,0x7fffb4b863c0) malloc: *** error for object 0x10769fd08: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

```
/usr/local/bin/carthage update --platform iOS --toolchain com.apple.dt.toolchain.XcodeDefault
*** Fetching RxSwift
*** Fetching Swinject
*** Fetching Cuckoo
*** Checking out Cuckoo at "0.10.2"
*** Checking out Swinject at "2.1.1"
*** Checking out RxSwift at "4.1.1"
*** xcodebuild output can be found in /var/folders/wy/40bvjrf903sgv4jqs6lb3lq40000gq/T/carthage-xcodebuild.g5rhp2.log
*** Building scheme "Cuckoo" in Cuckoo.xcworkspace
*** Building scheme "Cuckoo+Run" in Cuckoo.xcworkspace
*** Building scheme "RxCocoa-iOS" in Rx.xcworkspace
*** Building scheme "RxTests-iOS" in Rx.xcworkspace
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
*** Building scheme "Swinject-iOS" in Swinject.xcodeproj
carthage(70304,0x7fff96a7a3c0) malloc: *** error for object 0x1075a0c68: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
/var/folders/wy/40bvjrf903sgv4jqs6lb3lq40000gq/T/jenkins3646389720896300784.sh: line 2: 70304 Abort trap: 6           /usr/local/bin/carthage update --platform iOS --toolchain com.apple.dt.toolchain.XcodeDefault
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Carthage has been having this intermittent malloc error for some time on our build server (running Jenkins 2.92). I found https://github.com/Carthage/Carthage/issues/2263 in the issue list and started looking at our dependencies for any known issues, but were unable to find anything. Also, our Xcode build output from the carthage builds showed no signs of any problem. All of the carthage-xcodebuild logs indicate successful builds and have no signs of any build issue in any of the dependencies.
This error happens intermittently for both `carthage update --platform iOS` as well as `carthage bootstrap --platform iOS` and `carthage bootstrap --platform iOS --no-use-binaries`.

**Comment by mdiep** [comment] 2018-01-19 18:00
I'm not able to reproduce this. If you can reproduce this while running Carthage in the Xcode debugger, you might get some more helpful information that could direct us to the cause.

**Comment by admeister** [comment] 2018-03-08 20:33
+1 here

carthage(543,0x7fff91e0d340) malloc: *** error for object 0x10a485d08: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by blender** [comment] 2018-03-20 11:45
@mt00chikin @admeister Does 0.29.0 https://github.com/Carthage/Carthage/releases/tag/0.29.0 fix the problem for you?

If so, please consider closing this issue.

**Comment by blender** [comment] 2018-03-21 11:33
I'll close this issue for now, please feel free to comment if you see it happen again.

**Closed by blender** 2018-03-21 11:33 UTC
