### ISSUE TITLE
Leverage Xcode 10's new "File list" feature for input/output files of Run Script build phases

### ISSUE THREAD

**Issue by Sajjon** [Carthage/Carthage#2568] opened 2018-09-07 13:40 UTC
Have you seen `File List` feature in Xcode 10? 

[Oliver a.k.a. AliSoftware talks about it here regarding SwiftGen](https://github.com/SwiftGen/SwiftGen/issues/441). I believe we could drastically reduce the manual work of entering all the input and output files in Xcode when using Carthage.

My idea is that after having run `carthage update` or `carthage bootstrap`, carthage would create two file lists:
 `input_files.xcfilelist` and  `output_files.xcfilelist` and we would only need to reference these two file lists once, as an initial setup of Carthage, in Xcode. Then for every new entry we add in the Cartfile we would only need to add perform the adding of frameworks to `Linked Frameworks and Libraries` for Apps, and `Link Binaries With Libraries build phase` for frameworks/tests.

What do you think?

**Comment by ikesyo** [comment] 2018-09-07 13:43
Duplicate of #2477.

**Closed by ikesyo** 2018-09-07 13:43 UTC
