### ISSUE TITLE
Carthage builds fail at xcrun lipo on Xcode 12

### ISSUE THREAD

**Issue by 15809284891** [Carthage/Carthage#3072] opened 2020-10-12 09:29 UTC
carthage install method: [ ] .pkg, [x] homebrew, [x] source
which carthage:  /usr/local/Cellar/carthage
carthage version: 0.36.0
xcodebuild -version: 12A7300
Are you using --no-build? No
Are you using --no-use-binaries? No
Are you using --use-submodules? No
Are you using --cache-builds? No
Are you using --new-resolver? No
an error occurred when i excuted "carthage build --no-skip-current" command
![image](https://user-images.githubusercontent.com/17779724/95729956-32251300-0cb0-11eb-80cc-d7c1b28a2e6d.png)
but the build log display was successful
![image](https://user-images.githubusercontent.com/17779724/95730120-639dde80-0cb0-11eb-85f8-1e4a825487f1.png)

**Comment by tmspzz** [comment] 2020-10-12 10:07
Please check for open issues instead of opening new ones.

This is a duplicate of https://github.com/Carthage/Carthage/issues/3019 (which is also a pinned issue) 

Here is a workaround guide: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

**Closed by tmspzz** 2020-10-12 10:07 UTC
