### ISSUE TITLE
xcodebuild time out while trying to read ____ (on Travis…)

### ISSUE THREAD

**Issue by schwa** [Carthage/Carthage#1310] opened 2016-05-17 19:25 UTC
Xcode 7.3.1, Carthage 0.16.2.

We have a carthage project running on Travis CI and it has started timing out (throwing XcodebuildTimeout errors) inside xcodebuild tasks.

`xcodebuild timed out while trying to read Rx.xcworkspace 😭`

I found two xcodebuild tasks that throw these errors and the timeout and retry values are inconsistent (see https://github.com/Carthage/Carthage/search?q=XcodebuildTimeout ). I suggest standardising on a 60 second timeout with 2 retries (as per Xcode.swift / schemesInProject).

I also suggest that carthage log the exact tool output so the user can see exactly what is failing and therefore provide better feedback to Carthage team.

I've implemented the latter two suggestions in this fork: https://github.com/schwa/Carthage/tree/jwight/timeout_tests - that I'm currently testing.

It might also be handy to expose a timeout parameter to carthage (possibly via an environment variable) so users can workout timeout problems without waiting for a new carthage release? (Not implemented on my branch yet - not sure environ variable is correct solution).

**Comment by mdiep** [comment] 2016-05-18 00:32
Could you test how long it takes to read those files on Travis? I'd be happy to adjust the timeout based on timings on Travis.

This is a tricky item because sometimes `xcodebuild` will work immediately on the second attempt. That's why the timeout is shorter for this particular case. Adding a longer timeout will increase the build times for some users, so I don't want to make the timeout longer than necessary.

We could also do something akin to an exponential back off to get a quick retry but prevent timeouts for larger projects. That would require more work, but is ultimately the best solution. Pull requests welcome for that. :smile:

**Comment by Hais** [comment] 2016-07-01 15:50
I'm currently battling with TravisCI now to try and get to the bottom of this. With an open ticket with Travis support to see if they can help track the issue where applicable. 

Is there any kind of data I can collect for yourselves to help determine the problem? 

Mines a fairly large project with 25+ Carthage dependancies. But it consistently fails with the same timeout after on the same dependancy each time. If I remove the failing dependancy it then fails on the next one. etc.

**Comment by mdiep** [comment] 2016-07-02 01:15
This is a bug in the `xcodebuild` command line program provided by Xcode. We try to work around it by adding a timeout. That timeout can be too short on slow hardware like Travis.

It'd be helpful to know (a) which `xcodebuild` command is timing out and (b) how long it takes to run that command successfully. Then we can adjust the timeout.

**Comment by schwa** [comment] 2016-07-06 17:31
Out of curiosity - what's the evidence that this is an actual bug in xcodebuild? We've run various tests (including replacing carthage with our own python based alternative: http://github.com/schwa/punic) and xcodebuild info/showBuildSettings have been 100% reliable - both locally and on travis (with their painfully slow VMs). I'm more inclined to believe the issue is with RACTask. Has that been ruled out yet?

**Comment by mdiep** [comment] 2016-07-06 20:53
I've reproduced the hangs with xcodebuild directly on my machine.

**Comment by samsonjs** [comment] 2016-08-27 02:16
I'm trying to run `carthage bootstrap` on a 2016 MacBook and with Carthage 0.17.2 it fails consistently with `xcodebuild timed out while trying to read CoreDataLogger.xcodeproj 😭`. Tried that several times with no luck.

So I found all these issues about timeouts, cloned the Carthage repo, changed the timeouts for `xcodebuild -list` and `xcodebuild -showBuildSettings` to 24 hours, and now it works. At least one of these timeouts is still too low for real world use for me. I can experiment a bit to try and find a better middle ground between 30s and 24h.

**Comment by yas375** [comment] 2016-08-31 07:47
I'm getting the same error when running integration tests for a library on TravisCI:
* iOS: https://travis-ci.org/mattt/FormatterKit/jobs/156337296
* macOS: https://travis-ci.org/mattt/FormatterKit/jobs/156337297
* watchOS: https://travis-ci.org/mattt/FormatterKit/jobs/156337298
* tvOS: https://travis-ci.org/mattt/FormatterKit/jobs/156337299

Works fine locally (carthage 0.17.2)

**Comment by Mehdzor** [comment] 2016-08-31 11:27
+1

**Comment by Mehdzor** [comment] 2016-08-31 11:27
@samsonjs, how did you set timeouts?

**Comment by yas375** [comment] 2016-09-01 08:21
I'm not sure if it would help but just in case:

I have integration tests for a framework. The framework has multiple languages. One of the recent changes I did for the framework after which tests have started to fail, is that I moved all localizations into a bundle. Not sure if this is the reason why it times out, but just in case...

**Comment by samsonjs** [comment] 2016-09-01 15:15
@Mehdzor https://github.com/samsonjs/Carthage/commit/946e202019c9ede36a4ea6cfb57df067dd8cb3ee

**Comment by gbejarano01** [comment] 2016-09-12 21:40
+1 Experiencing the same issue here.

**Comment by frogcjn** [comment] 2016-10-03 19:21
@samsonjs, how did you set timeouts??

**Comment by samsonjs** [comment] 2016-10-03 19:30
@frogcjn https://github.com/samsonjs/Carthage/commit/946e202019c9ede36a4ea6cfb57df067dd8cb3ee ... if you're using CocoaLumberjack then this will help _a lot_ as well: https://github.com/samsonjs/CocoaLumberjack/commit/ce8caa212eac0dca913a73b391bee1d59492afed

**Comment by frogcjn** [comment] 2016-10-03 20:36
@samsonjs Thanks! I build the hacked-up branch, and it works.

**Comment by gbejarano01** [comment] 2016-10-03 20:45
Yeah, the issue is in [Xcode.swift] (https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Xcode.swift) either line 142 or 493.

Search for `XcodebuildTimeout` and you will find it, that's the timeout hard-coded on 60 and 30 seconds each.

**Comment by mdiep** [comment] 2016-10-04 00:16
Are you still experiencing this issue with Carthage 0.18? We were hoping that #1447 would work around this issue.

**Comment by yas375** [comment] 2016-10-04 00:24
@mdiep I was getting this issue on Travis with Carthage 0.18:

* iOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922844#L774-L777
* macOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922845#L774-L777
* watchOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922846#L774-L777
* tvOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922847#L774-L777

**Comment by mdiep** [comment] 2016-10-04 00:47
Does someone want to open a PR to change the second timeout to 60 seconds for the next release?

**Comment by gbejarano01** [comment] 2016-10-04 14:50
@mdiep is there any way to parametrize that instead? I believe that would be more appropriate, because we don't know how long it may take building one framework, it depends how big and how many dependencies it has. My two cents.

**Comment by samsonjs** [comment] 2016-10-04 16:15
@mdiep My specific issues building `CocoaLumberjack/CocoaLumberjack` is fixed in 0.18.

@gbejarano01 Making it a parameter might be a good idea, that way people on fast machines can make it low and keep things fast and those on slow machines can configure things to actually work for them.

**Comment by TheArtOfEngineering** [comment] 2016-10-15 21:40
I am also getting this issue when trying to install the new Facebook Swift SDK. 
`carthage version: 0.18.1`

**Comment by mdiep** [comment] 2016-10-16 00:02
No one has opened a PR to make this change. PRs welcome!

**Comment by TheArtOfEngineering** [comment] 2016-10-16 00:39
Are we okay with just bumping the timeout to 60 sec? Or would you prefer it be parameterized?

**Comment by yas375** [comment] 2016-10-16 00:42
@mdiep @TheArtOfEngineering I've just submitted a PR with just increasing the value. I did that change a few days ago and have verified on Travis. Seem to fix the problem. I don't see much value in making it as a parameter. If it builds fast enough on your machine, then you don't need to think about it. If 60 seconds might be not enough on Travis, then I would rather increase it to even more by default.

**Closed** 2016-10-16 01:27 UTC

**Comment by DJBen** [comment] 2017-12-09 19:49
Currently I am integrating AWS SDK into iOS using Carthage and 60s doesn't seem enough for Travis.
`xcodebuild timed out while trying to read AWSiOSSDKv2.xcodeproj`

Would love to see this option parametrized.

**Comment by cszucko** [comment] 2017-12-18 16:56
I just ran into this with the AWS SDK as well.  This was on a 1.8 GHz i7 mid-2011 MacBook Air, so it needing extra time isn't a huge shock.

I was able to get around the issue by building my own version of Carthage with the timeout raised to to 240 seconds (see: [BuildSettings.swift](https://github.com/Carthage/Carthage/blob/f65531d9c3d80875a74655f4a4040030a982b08d/Source/CarthageKit/BuildSettings.swift#L61)).  A lower value might work too; I just picked something arbitrarily high.

**Comment by raid5** [comment] 2017-12-18 21:08
I'm hitting this issue as well on BuildBuddy.

`xcodebuild timed out while trying to read AWSiOSSDKv2.xcodeproj`

**Comment by mlfarrell-convene** [comment] 2018-01-30 02:12
Exact same issue!  Help!!

I'm hitting this issue as well on BuildBuddy.

xcodebuild timed out while trying to read AWSiOSSDKv2.xcodeproj

**Comment by sunchunqiang** [comment] 2018-10-31 21:47
same issue here @mlfarrell-convene . 
any solution?

**Comment by CalebeRios** [comment] 2019-06-04 13:46
I'm experiencing this error in `v0.33.0`
Solutions?

**Comment by butyrin-bookmate** [comment] 2019-12-26 12:17
Same issue here, solved it by using this shell script: https://gist.github.com/raid5/ae5c6787926e7cdd4412ad6bb4456a79
just replace `! -name "AWSCore.xcscheme" ! -name "AWSPinpoint.xcscheme"` there with the schemes you actually use in your project and it should work.

**Comment by markd2** [comment] 2020-05-28 22:13
Same issue here with facebook-ios-sdk.  Having the timeout being parameterized would be wonderful.
