### ISSUE TITLE
Undefined symbols error in linker with Xcode 10.2 / Swift 5

### ISSUE THREAD

**Issue by Nass30** [Carthage/Carthage#2753] opened 2019-04-01 12:16 UTC
Hello,

Using Xcode 10.2 (we had no similar issues with Xcode 10.1), carthage succeeds to build framework, but when I build the project with the added framework, some specific symbols are missing by the linker.

To test the fail, I have created two framework :
- [FrameworkTest](https://github.com/Nass30/Framework-Test) : 
    - It contains a GenericClass, a GenericClassChild, a struct Model and an InternalClass.
    - The generic class contains an internal method using an instance of the InternalClass in parameters and a public method.
    - The generic class child override the internal method with an `override final` mark. This symbol method is missing by the linker.
- [FrameworkImplementingFrameworkTest](https://github.com/Nass30/Framework-Implementing-FrameworkTest)
    - It implement the GenericClassChild of the FrameworkTest.

To trigger the build fail, clone [FrameworkImplementingFrameworkTest](https://github.com/Nass30/Framework-Implementing-FrameworkTest), carthage boostrap, and build the framework.

We also tried to build the framework with Xcode, copy the .framework from Xcode/DerivedData to Repo/Carthage/Build and the bug doesn't occurs anymore.

* carthage install method: brew and make install on master
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: Carthage 0.32.0 and Carthage master
* `xcodebuild -version`: Xcode 10.2
* Are you using `--no-build`? 
No
* Are you using `--no-use-binaries`? 
No
* Are you using `--use-submodules`? 
No
* Are you using `--cache-builds`? 
No
* Are you using `--new-resolver`? 
No

**Cartfile**
```
github "Nass30/Framework-Test" "master"
```

**Carthage Output**
```
*** Checking out Framework-Test at "883a53567804efe5c2578b487ee0e402de0de7a1"
*** xcodebuild output can be found in /var/folders/yt/hyz_g0957ylc2p2c6m2b5cr9v_3vx9/T/carthage-xcodebuild.uj6X53.log
*** Building scheme "FrameworkTest" in FrameworkTest.xcodeproj
```

**Actual outcome**
The carthage build succeed but when we build the project, an error occurs :
Undefined symbols for architecture x86_64:
  "FrameworkTest.GenericClassChild.performAction(someModel: A, someInternalInstance: FrameworkTest.InternalClass) -> ()", referenced from:
      type metadata for FrameworkImplementingFrameworkTest.ClassImplementingGenericChildClass in ClassImplementingGenericChildClass.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Expected outcome**
The build should succeed.

**Comment by ZhuoranTan** [comment] 2019-04-02 03:15
Possibly related to the known issue in [Xcode 10.2 Release Note](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes). Maybe Carthage should implement a workaround?

**Comment by DavidBrunow** [comment] 2019-04-02 03:18
I believe this is a duplicate of this issue: https://github.com/Carthage/Carthage/issues/2718

If so, a PR to resolve this issue has been merged to master and the Carthage team is working on a new release.

**Comment by blender** [comment] 2019-04-02 05:26
Duplicate of #2718

**Closed by blender** 2019-04-02 05:27 UTC

**Comment by Nass30** [comment] 2019-04-02 09:48
@DavidBrunow @blender 
I tried again with the new master version of Carthage, it still fails to build.

Note that so far we use a hack by removing the `final` mark of the method and the build succeeds.

But yeah, this is certainly a duplicate of the #2718.

**Comment by DavidBrunow** [comment] 2019-04-02 14:48
@Nass30 If removing the `final` mark fixes the build I would see that as a separate issue -- I wouldn't think the issue with the header files would impact that.

**Comment by Nass30** [comment] 2019-04-02 16:34
@DavidBrunow Setting the method as public fixes the build too.

**Comment by jdhealy** [comment] 2019-04-02 18:38
Couldn't reproduce with latest Carthage master (87e21988) —

```shell
sudo xcode-select --switch /Applications/Xcode/Xcode_10.1.app
brew uninstall --force carthage
HOMEBREW_VERBOSE=1 brew install --HEAD /var/tmp/carthage.rb
# See HEAD is now at 87e21988 Merge pull request #2741 from Carthage/revert-authorization-header-for-redirected-requests
git clone https://github.com/Nass30/Framework-Test
cd Framework-Test
sudo xcode-select --switch /Applications/Xcode/Xcode_10.2.app
carthage build --no-skip-current --verbose

open -a /Applications/Xcode/Xcode_10.2.app
# File → New → Workspace
# File → New → Project → Cocoa Touch Framework
# File → New → File → Swift File
# add `import TestFramework`
# Drag …/Carthage/Build/iOS/FrameworkTest.framework into “Linked Frameworks and Libraries”
# Set `FRAMEWORK_SEARCH_PATH`
# Build in Debug for device and simulator
# Build in Release for device and simulator
```

**Comment by manu-d** [comment] 2019-04-03 08:12
@jdhealy 
Following the steps you described, adding
```swift
/// A simple model.
struct SomeModel {
    var nb: Int

}

/// Here we implement the GenericClassChild of the FrameworkTest.
class ClassImplementingGenericChildClass: GenericClassChild<SomeModel> { }
```
to the new swift file in your framework leads to the error @Nass30 mentioned

**Comment by Nass30** [comment] 2019-04-03 09:01
To trigger the build fail :
git clone git@github.com:Nass30/Framework-Implementing-FrameworkTest.git
cd Framework-Implementing-FrameworkTest
open FrameworkImplementingFrameworkTest.xcodeproj
build

**Comment by Nass30** [comment] 2019-04-04 12:15
Hello @jdhealy ,
I upgraded to carthage 0.33.0 and the project still fails to build. Could you please try to trigger the build fail by adding the @manu-d 's code to a new swift file or cloning my repo ?

**Comment by manu-d** [comment] 2019-04-04 16:46
Following some investigation, the issue seems to come with Swift 5. If I build the framework with Xcode 10.2, but the Swift 4.2.1 toolchain, the issue disappears
