### ISSUE TITLE
Carthage always fetch original repository instead of my forked changes commit.

### ISSUE THREAD

**Issue by MingLoan** [Carthage/Carthage#2190] opened 2017-10-03 05:20 UTC
* `carthage version`: 0.25
* `xcodebuild -version`: xcode9
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
git "https://github.com/<my_account>/<a_forked_repo>.git"
```

Carthage always fetch original repository instead of my forked changes commit.

**Comment by MingLoan** [comment] 2017-10-03 05:35
I fixed it by cleaning cache in ~/Library/Caches/org.carthage manually.

Any other ways I can make it robust since I need to tell all my teammates to do it as well as the CI server.

**Comment by nomadplanet** [comment] 2017-10-03 09:02
I guess it's the same issue as https://github.com/Carthage/Carthage/issues/2143

**Comment by ikesyo** [comment] 2017-10-03 10:11
Yes, this is a duplicate of #2143. Closing.

**Closed by ikesyo** 2017-10-03 10:11 UTC
