### ISSUE TITLE
Carthage misspell update all repos

### ISSUE THREAD

**Issue by purkylin** [Carthage/Carthage#1840] opened 2017-03-20 04:22 UTC
My carthage version: 0.20.1

* I found Carthage update is a bit slow
* Carthage update do not as my expectation
I run `carthage update SwiftyJson`,  get the output:

<pre>
*** Fetching SwiftyJSON
*** Fetching lottie-ios
*** Fetching realm-cocoa
*** Fetching Hero
*** Fetching Alamofire
*** Fetching RxSwift
*** Fetching RxDataSources
*** Checking out Alamofire at "4.4.0"
*** Checking out Hero at "0.3.4"
*** Checking out lottie-ios at "20b94330121ce4a33e1fa50897552390580933aa"
*** Downloading realm-cocoa.framework binary at "v2.4.4"
*** Downloading RxSwift.framework binary at "Hashimoto.1"
^C
</pre>

but I run `carthage update SwiftyJSON` get this output:

<pre>
*** Fetching SwiftyJSON
*** Fetching lottie-ios
*** Fetching realm-cocoa
*** Fetching Hero
*** Fetching Alamofire
*** Fetching RxSwift
*** Fetching RxDataSources
*** Downloading SwiftyJSON.framework binary at "3.1.4"
......
</pre>

**Comment by ikesyo** [comment] 2017-03-20 08:28
This is a duplicate of #1517.

**Closed by ikesyo** 2017-03-20 08:28 UTC
