### ISSUE TITLE
Parse error: expected submodule commit SHA in output of task

### ISSUE THREAD

**Issue by paultnp** [Carthage/Carthage#1763] opened 2017-02-15 06:16 UTC
* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? : NO
* Are you using `--no-use-binaries`? : NO
* Are you using `--use-submodules`? : NO

**Cartfile**
github "cloudinary/cloudinary_ios"
github "Kumulos/KumulosSdkSwift" ~> 1.1

**Carthage Output**
Parse error: expected submodule commit SHA in output of task (ls-tree -z 2.0.1 Cloudinary/Frameworks/Alamofire) but encountered: 

wloudinary and Kumulos both are using Alamofire as submodule and so this error is coming. Also both are using different Alamofire version. How would it be handled.

**Comment by mdiep** [comment] 2017-02-15 13:57
This is because cloudinary_ios (currently at version 2.0.1) doesn't have its submodules configured properly.

`.gitmodules` lists this:

```
[submodule "Cloudinary/Frameworks/Alamofire"]
	path = Cloudinary/Frameworks/Alamofire
	url = https://github.com/Alamofire/Alamofire.git
[submodule "Alamofire"]
	branch = 4.1.0
```

But those submodules don't exist.

Carthage should handle this better, but there's also an issue with that repo.

**Comment by mdiep** [comment] 2017-02-15 13:58
See: https://github.com/Carthage/Carthage/issues/135

**Comment by ikesyo** [comment] 2017-07-12 17:16
Closing as a duplicate of #135.

**Closed by ikesyo** 2017-07-12 17:16 UTC
Labels: bug, duplicate
