### ISSUE TITLE
dyld: Library not loaded @rpath/libswiftAVFoundation.dylib

### ISSUE THREAD

**Issue by yiz0816** [Carthage/Carthage#1422] opened 2016-08-07 09:38 UTC
* `carthage version`: 0.17.2
* `xcodebuild -version`:  XCode 8.0 8S174q
* Are you using `--no-build`?  NO
* Are you using `--no-use-binaries`?  NO
* Are you using `--use-submodules`? NO

Carthage build all work well but when I run project, the app crashes with the following log

```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /var/containers/Bundle/Application/9B839EB5-0D3D-44C0-92E6-AA6B4857E1EC/SecureTribe.app/SecureTribe
  Reason: image not found
```

Sometimes it is libswiftCore.dylib

**Comment by ikesyo** [comment] 2016-08-07 10:54
This should be a duplicate of https://github.com/Carthage/Carthage/issues/1394#issuecomment-234735729 and not a Carthage issue. Closing.

**Closed by ikesyo** 2016-08-07 10:54 UTC
