### ISSUE TITLE
Issue fetching a private repo on GitHub

### ISSUE THREAD

**Issue by Baza207** [Carthage/Carthage#796] opened 2015-09-24 14:01 UTC
I've been trying to use Carthage to get a private repo I use for most of my project, lets call it `MyPrivateKit`.

I've tried adding it to the Cartfile but everything I try I get the following response.

```
*** Fetching MyPrivateKit
A shell task failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git
```

The different way's I've tried adding it to the Cartfile are listed below:
- `github "<organisation>/MyPrivateKit" ~> 0.6`
- `git "https://<Username>@github.com/<organisation>/MyPrivateKit" ~> 0.6`
- `git "https://<Username>@github.com/<organisation>/MyPrivateKit.git" ~> 0.6`

I'm sure I probably need to state my password or token for the repo somewhere, but I'm not sure where. KeychainAccess has the token in it, so I'm not sure where to try next. I obviously don't want it in a file that gets pushed, so I'm sure I shouldn't add it to the Cartfile, even if I know how.

Carthage 0.8.0, fyi :)

**Comment by ikesyo** [comment] 2015-09-24 14:11
This would be dupe of #407, #642 and #694. Removing `~/Library/Caches/org.carthage.CarthageKit` would help.

**Comment by ikesyo** [comment] 2015-09-24 14:16
Additionally, this should have been fixed in Carthage 0.9.1.

**Comment by Baza207** [comment] 2015-09-24 14:19
Thanks, I'm now getting the following however.

```
A shell task failed with exit code 128:
fatal: could not read Password for 'https://<username>@github.com': terminal prompts disabled
```

Any news on 0.9.2 for brew?

**Comment by ikesyo** [comment] 2015-09-24 14:24
It means that your Keychain is not correctly set up, I think. Please follow [these instructions](https://help.github.com/articles/caching-your-github-password-in-git/) to set up a credential helper, or just try with `github "<organisation>/MyPrivateKit" ~> 0.6`. `https://<Username>@github.com` and `https://github.com` would be different URLs for credential helper.

**Comment by Baza207** [comment] 2015-09-24 14:28
Ah amazing, that did the trick. I knew it'd be something somewhere. Thanks for the help and the fast response as always. 😊

**Comment by ikesyo** [comment] 2015-09-24 14:59
My pleasure!

**Closed by ikesyo** 2015-09-24 14:59 UTC
Labels: bug, duplicate

**Comment by willeeklund** [comment] 2017-01-17 13:55
For me this worked for the authorization: "carthage update --use-ssh"

**Comment by vivekrigil** [comment] 2017-05-30 11:42
My terminal is struck while using it , I have also tried "carthage update --use-ssh"
<img width="567" alt="screen shot 2017-05-30 at 5 10 56 pm" src="https://cloud.githubusercontent.com/assets/22632653/26581621/19723740-455b-11e7-98c7-bd7d16718ad3.png">
