### ISSUE TITLE
How to build lib that contains other framework

### ISSUE THREAD

**Issue by idokleinman** [Carthage/Carthage#1230] opened 2016-03-31 03:20 UTC
* `carthage version`: 0.14
* `xcodebuild -version`: 7.2.1 (7C1002)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? yes

**Cartfile**
```
github "spark/spark-setup-ios" "test_cart1"
```

**Carthage Output**
```
*** Fetching spark-setup-ios
*** Checking out spark-setup-ios at "test_cart1"
*** xcodebuild output can be found in /var/folders/cs/fd7952qj5s53313lphmrfqph0000gn/T/carthage-xcodebuild.l9HOE6.log
*** Building scheme "ParticleDeviceSetupLibrary" in SparkSetup.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/SparkSetup-eqmjvprdcahpckdrqowzpvxutdbr/Build/Intermediates/ParticleDeviceSetupLibrary.build/Release-iphoneos/ParticleDeviceSetupLibrary.build/Objects-normal/armv7/SparkUserForgotPasswordViewController.o /Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkUserForgotPasswordViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/SparkSetup-eqmjvprdcahpckdrqowzpvxutdbr/Build/Intermediates/ParticleDeviceSetupLibrary.build/Release-iphoneos/ParticleDeviceSetupLibrary.build/Objects-normal/armv7/SparkSetupResultViewController.o /Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkSetupResultViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/SparkSetup-eqmjvprdcahpckdrqowzpvxutdbr/Build/Intermediates/ParticleDeviceSetupLibrary.build/Release-iphoneos/ParticleDeviceSetupLibrary.build/Objects-normal/armv7/SparkUserLoginViewController.o /Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkUserLoginViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)
/Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkUserForgotPasswordViewController.m:12:9: fatal error: 'ParticleSDK/ParticleSDK.h' file not found
/Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkSetupResultViewController.h:11:9: fatal error: 'ParticleSDK/ParticleSDK.h' file not found
/Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkUserLoginViewController.m:14:9: fatal error: 'ParticleSDK/ParticleSDK.h' file not found
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/SparkSetup-eqmjvprdcahpckdrqowzpvxutdbr/Build/Intermediates/ParticleDeviceSetupLibrary.build/Release-iphoneos/ParticleDeviceSetupLibrary.build/Objects-normal/armv7/SparkUserForgotPasswordViewController.o /Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkUserForgotPasswordViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/SparkSetup-eqmjvprdcahpckdrqowzpvxutdbr/Build/Intermediates/ParticleDeviceSetupLibrary.build/Release-iphoneos/ParticleDeviceSetupLibrary.build/Objects-normal/armv7/SparkSetupResultViewController.o /Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkSetupResultViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/SparkSetup-eqmjvprdcahpckdrqowzpvxutdbr/Build/Intermediates/ParticleDeviceSetupLibrary.build/Release-iphoneos/ParticleDeviceSetupLibrary.build/Objects-normal/armv7/SparkUserLoginViewController.o /Users/ido/projects/Spark/test_cart/test_cart/Carthage/Checkouts/spark-setup-ios/Classes/UI/SparkUserLoginViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)
```
---

I am trying to create a framework (ParticleDeviceSetupLibrary) that contains a 'daughter' framework as a dependency (ParticleSDK). The ParticleSDK builds fine and is listed as "linked frameworks" in the ParticleDeviceSetupLibrary project target, also "Linked binary with Libraries" - it compiles fines in Xcode but carthage build fails on finding the reference to that daughter lib header files. What's the recommended way to go about doing that?

Thanks

**Comment by ikesyo** [comment] 2016-03-31 03:44
It seems to me that the problem is your Cartfile is in `ParticleDeviceSetupLibrary` directory, but Cartfile must be in the root directory of the repo. Otherwise, Carthage can't find the file and its dependencies.

**Comment by ikesyo** [comment] 2016-03-31 03:47
So this is a duplicate of #1048 and #1066. Closing.

**Closed by ikesyo** 2016-03-31 03:47 UTC
Labels: duplicate, question
