### ISSUE TITLE
Generic Xcode Archieve 

### ISSUE THREAD

**Issue by vishal91** [Carthage/Carthage#1423] opened 2016-08-08 14:02 UTC
* `carthage version`: 0.16
* `xcodebuild -version`: Xcode 7.3.1 , Build version 7D1014
* Are you using `--no-build`? 🔕 
* Are you using `--no-use-binaries`? 🔕 
* Are you using `--use-submodules`? 🔕 
I am not able to export archieve to App store. What can be the issue?

**Comment by ikesyo** [comment] 2016-08-08 14:24
This is a duplicate of #1259 and #1263, and is already fixed in [0.16.1](https://github.com/Carthage/Carthage/releases/tag/0.16.1) or later by #1261. Closing.

**Closed by ikesyo** 2016-08-08 14:24 UTC
Labels: question
