### ISSUE TITLE
Invalid architecture UUIDs for binary-only library

### ISSUE THREAD

**Issue by schukin** [Carthage/Carthage#1516] opened 2016-10-05 22:27 UTC
We have a binary-only library for which we're trying to add Carthage support. However every time I run `carthage update`, we encounter the following error:

```
$ carthage update --platform ios
*** Fetching Buglife-iOS-Carthage-Test
*** Downloading Buglife-iOS-Carthage-Test.framework binary at "1.3.2"
Invalid architecture UUIDs: Could not parse UUIDs using dwarfdump from /Users/schukin/src/temp/TestApp/Carthage/Build/iOS/Buglife-iOS-Carthage-Test.framework/Buglife-iOS-Carthage-Test
```

We've looked at similar libraries (e.g. Carthage wrappers around Crashlytics, and their corresponding Info.plists), and everything _seems_ like it should work on our end. We're at a bit of a loss here... Any ideas?

* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 8.0
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "Buglife/Buglife-iOS-Carthage-Test"
```

**Comment by ikesyo** [comment] 2016-10-05 22:44
Are you sure that your framework is a dynamic framework, not a static (fake) framework? Carthage does not support the latter.

**Comment by ikesyo** [comment] 2016-10-05 22:48
Looks like this should be a duplicate of #889.

**Comment by schukin** [comment] 2016-10-05 22:50
Ah, yeah it's a static (fake) framework. Apologies, thought I read [this](https://github.com/Carthage/Carthage/issues/1379#issuecomment-229802457) comment in that ticket and thought that fake frameworks _were_ supported. Thanks!

**Closed** 2016-10-06 00:53 UTC
Labels: question
