### ISSUE TITLE
Carthage builds dependency for Binary with valid swift version.

### ISSUE THREAD

**Issue by aaroncrespo** [Carthage/Carthage#1979] opened 2017-06-06 17:49 UTC
* `carthage version`: 0.23.0
* `xcodebuild -version`: Xcode 8.3.3
Build version 8E3004b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "https://enterprise.github/quick/"  "binary release 1.1.0"
github "https://enterprise.github/nimble/"  "binary release 7.0.1"
```

**Carthage Output**
```shell 
$ carthage update

*** Fetching quick
*** Fetching nimble
*** Downloading nimble.framework binary at "7.0.1"
*** Downloading quick.framework binary at "1.1.0"
*** Skipped installing nimble.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 effective-3 and the local version is 3.1."
*** Checking out nimble at "7.0.1"
*** xcodebuild output can be found in /var/folders/vx/hmnt9s3x0qn_bcdjc_9qrcnsgp2kq9/T/carthage-xcodebuild.Kzm6ez.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Nimble-macOS" in Nimble.xcodeproj
*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
```

The Nimble binary is produced via: 

```shell
$ carthage build --no-skip-current && carthage archive
```

In the same environment the above `cartfile` is being updated in. 

Xcode select is not changing 8.3.3 is selected. Quick works fine but Nimble is reporting `3.1 effective-3` swift version which is interpreted as not the same as `3.1`

**Comment by aaroncrespo** [comment] 2017-06-07 14:15
Nimble added a swift flag to support Swift 3 and Swift 4 and

removing 
```diff
-                               OTHER_SWIFT_FLAGS = "$(inherited) -swift-version 3";
```
And rebuilding the framework allows carthage to use the binary.

**Comment by aaroncrespo** [comment] 2017-06-15 17:34
Same issue happens even with swift and 4 self built binaries.
Cartfile only contains forks of Quick/Nimble built under Xcode 9 with `carthage build --no-skip-current && carthage archive`

```
$xcode-select -p
/Applications/Xcode-beta.app/Contents/Developer
$ carthage update
*** Downloading Nimble.framework binary at "xcode-9"
*** Downloading Quick.framework binary at "xcode-9"
*** Skipped installing Nimble.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 effective-3.2 and the local version is 4.0."
*** Checking out Nimble at "xcode-9"
*** Skipped installing Quick.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 effective-3.2 and the local version is 4.0."
*** Checking out Quick at "xcode-9"
*** xcodebuild output can be found in /var/folders/vx/hmnt9s3x0qn_bcdjc_9qrcnsgp2kq9/T/carthage-xcodebuild.H7pArc.log
// carthage proceeds to build from source
```

**Comment by BobElDevil** [comment] 2017-06-15 18:16
I believe you're hitting the same root cause as #1983 which is fixed by #1984 

Can you try with the latest 'master' and see if it resolves your issues?

**Comment by aaroncrespo** [comment] 2017-06-15 18:59
looks like https://github.com/Carthage/Carthage/pull/1984 is a fix for this

**Comment by aaroncrespo** [comment] 2017-06-15 19:00
@BobElDevil yeah I scanned PR's after this was posted and after much `Xcode select`ing and `make`ing I see some expected behaviors.

**Comment by BobElDevil** [comment] 2017-06-15 20:14
👍  Thanks for checking. Closing this since it's fixed in the latest

**Closed by BobElDevil** 2017-06-15 20:14 UTC
