### ISSUE TITLE
multiple schemes don't work since 7.4+

### ISSUE THREAD

**Issue by jeremiegirault** [Carthage/Carthage#644] opened 2015-07-27 17:52 UTC
Hey
I noticed that in a project with multiple schemes, frameworks are not copied to build directory since 7.4. It was not present in 7.4-beta2.

Is that "working as intended" or a bug ?

To test this, use this cartfile:
``` github "ankurp/Dollar.swift" ~> 3.0.1 ```

What is the workaround ?

Thanks

**Comment by jeremiegirault** [comment] 2015-07-27 18:02
Note that, I noticed by looking into DerivedData that projects are correctly built but not copied.

**Comment by jeremiegirault** [comment] 2015-07-27 20:26
Working a a test project, investigating ...

**Comment by ikesyo** [comment] 2015-07-28 23:09
_Multiple schemes_ in one project should work, but _Multiple projects_ each of them have their framework schemes does not work. This is an intended behavior. See #210 for the discussion (but the scheme/project discovery a slightly changed with #476, #570, #632 and #637).

You should have just one project for building frameworks and set up separate targets/schemes in it.

**Comment by ikesyo** [comment] 2015-07-29 00:55
> Note that, I noticed by looking into DerivedData that projects are correctly built

This is because Cent depends on Dollar, so Xcode builds Dollar first automatically to build Cent. Only Cent is built by Carthage, Dollar is not.

**Comment by jeremiegirault** [comment] 2015-07-29 07:02
> This is an intended behavior. See #210 for the discussion (but the scheme/project discovery a slightly changed with #476, #570, #632 and #637).

Ok If I sum up long ago, building the first scheme found seemed to be the most simple. There was a lot of issues and they were stacked up to a more complex logic ("error but only if a repo contains a project with no shared scheme, because empty repo are ok..."). 
But now the scheme discovery was improved and workspaces are supported so I guess we are in a different situation. I toyed with the code yesterday and I would consider contributing something which would allow this kind of situation to work.

Would you at least consider it, or is it not worth spending my time trying to improving this ?

Thanks!

**Comment by ikesyo** [comment] 2015-07-29 07:41
With the improved scheme discovery by #570, allowing to build multiple projects which have at least one shared framework scheme might be OK at now. However, for the users who just want to use one of multiple frameworks in a dependency (e.g. only Dollar but Cent in Dollar.swift), splitting them into each own repository would be better, I think.

@mdiep How do you think about this?

/cc @Carthage/carthage

**Comment by mdiep** [comment] 2015-07-29 13:16
I'll think about this, but I'm moving this week so I probably won't respond until next week.

**Comment by jeremiegirault** [comment] 2015-08-31 14:08
ok great !

**Comment by mdiep** [comment] 2015-09-01 00:57
I'm sorry… I'm a little confused about what you're proposing. Can you explain it again for me? :confused:

**Comment by jeremiegirault** [comment] 2015-09-01 08:25
Actually some projects like Dollar.swift contains multiple .xcodeproj & schemes in a single repo. (Dollar.swift & Cent.swift). It would be possible (even intuitive for the user) that carthage would build every project in the repo.

This is not the case (it was in 7.4-beta.2 but was removed later). Would you agree that this feature could come back ?

**Comment by mdiep** [comment] 2015-09-01 12:39
Splitting it into multiple repos would be better, but I think it'd be okay to build all the framework targets that come from the same level. In other words, if we're going to build a framework from an `xcodeproj` in the root directory of the repo, build _all_ the frameworks in `xcodeproj`s in the root directory of the repo.

But I wouldn't expect Carthage to let you selectively build only one of the frameworks. So it'd be fine if Carthage built both Dollar and Cent, but don't expect it to let you choose to build only Dollar.

**Comment by jeremiegirault** [comment] 2015-09-01 12:40
agree

**Comment by jeremiegirault** [comment] 2015-09-01 12:41
I will work on this

**Comment by mdiep** [comment] 2015-12-22 05:58
#892 covers this! :tada:

**Closed by mdiep** 2015-12-22 05:58 UTC
