### ISSUE TITLE
cannot update when we have submodule in project

### ISSUE THREAD

**Issue by jasonShen89** [Carthage/Carthage#847] opened 2015-10-14 09:45 UTC
there is error message when we have submodule in project, when run "carthage update", it says : 
"Parse error: expected submodule commit SHA in ls-tree output:"

Something wrong with my config? Or it's a bug?

**Comment by Danappelxx** [comment] 2015-10-15 03:54
You have to use `carthage update --use-submodules` since you're using submodules. Unless, of course, that submodule has nothing to do with Carthage - in which case this is a valid bug :)

**Comment by Danappelxx** [comment] 2015-10-15 03:57
Personally I'm having this issue when there's no submodules in my directory at all...

```bash
Dan $ ls -al
total 16
drwxr-xr-x  6 dan  staff  204 Oct 14 20:56 .
drwx------+ 4 dan  staff  136 Oct 14 20:50 ..
-rw-r--r--@ 1 dan  staff   72 Oct 14 20:51 Cartfile
drwxr-xr-x  2 dan  staff   68 Oct 14 20:50 bin
-rw-r--r--@ 1 dan  staff  283 Oct 14 20:50 build
drwxr-xr-x  3 dan  staff  102 Oct 14 20:50 src
Dan $ cat Cartfile
github "Mast-Swift/Mast" "master"
github "Mast-Swift/Mast-HBar" "master"
Dan $ carthage update --verbose
*** Fetching Mast-HBar
*** Fetching Mast
*** Fetching taylor
*** Fetching handlebars-objc
*** Fetching CocoaAsyncSocket
*** Checking out handlebars-objc at "4072c100a31dcc71d3ebe5e255f852b93920727c"
*** Checking out CocoaAsyncSocket at "fe716222f72811e66de02809eae8db77dacb6a83"
*** Checking out Mast at "dd346f5a5560ff97999dc7320e4ae4948eab983f"
*** Checking out Mast-HBar at "2b7fc51acf0aa8d6222d03b82665758f962aae64"
Parse error: expected submodule commit SHA in ls-tree output:
```

Any ideas? I've used submodules in other projects but definitely not here.

**Comment by mdiep** [comment] 2015-10-15 14:07
You could try removing `Carthage/Checkouts/` and/or `~/Library/Caches/org.carthage.CarthageKit`.

**Comment by Danappelxx** [comment] 2015-10-17 05:36
I've tried both of those - doesn't work :(

**Comment by mdiep** [comment] 2015-10-17 13:31
Are the projects listed as submodules in `.gitmodules`?

**Comment by Danappelxx** [comment] 2015-10-17 14:13
Strangely enough I get this error even in directories that aren't even part of git repositories

**Comment by lottadot** [comment] 2015-10-31 15:18
I have seen this too, but haven't had time to delve into it.
I did create a sample repo, with which you can easily reproduce this with v0.9.4

https://github.com/lottadot/carthagesubmodulepoc

**Comment by mdiep** [comment] 2015-11-02 17:36
This is a dupe of #135. See [this comment](https://github.com/Carthage/Carthage/issues/135#issuecomment-153094511) about it being a configuration issue in the dependency.

**Closed by mdiep** 2015-11-02 17:36 UTC

**Comment by yoiang** [comment] 2015-12-15 19:57
I read through the #135 thread, the resolution was that for participents' cases they didn't mean to have both the submodule manually defined and the dependency referenced in the `Cartfile`.

What about a situation where you would like both? Or perhaps you can offer an alternative:
I would like to provide easy routes for people to use a library or project and its dependencies through the method of their choosing, either it be *git submodules* or *Carthage* (or *Cocoapod*). I'd also love to be able to easily test each of these configurations easily.

If you check out (StoryboardKit's Carthage Support branch)[https://github.com/Adorkable/StoryboardKit/tree/feature/CarthageSupport] you'll notice I'm attempting to include *SWXMLHash* via `.gitmodules` and in the `Carthage` folder via `Cartfile`. I run into the same error as above, as is well documented and understood between the two threads.

I'm unclear as to why Carthage, when not specifying to `--use-submodules` should run into this issue, putting aside that *git submodules* support including the same `url` in duplicate.

If this is a stretch situation (understandable ;) ) and not going to be supported what are some alternatives folks would recommend? 

* separate git repos
* ...

**Comment by mdiep** [comment] 2015-12-21 00:13
@yoiang 

1. I don't think Carthage will work if your `Cartfile` isn't in the top-level directory. Also, you should check in your `Cartfile.resolved` file so that you've selected specific versions of your dependencies.

2. You could use `--use-submodules`, and that would allow you to work with both submodules and Carthage—you wouldn't need a separate submodule checkout.

3. If Carthage is getting confused by a separate submodule checkout of the dependency, please open a new issue. :smile:

**Comment by mdiep** [comment] 2015-12-21 00:16
Also, your branch seems to build with `carthage`?

**Comment by usezhuce** [comment] 2016-03-11 03:52
I resolve it with brew upgrade
