### ISSUE TITLE
[Question] Is it possible to inject build settings to build command ?

### ISSUE THREAD

**Issue by toshi0383** [Carthage/Carthage#1929] opened 2017-05-15 04:56 UTC
It would be nice if this is possible.
```
IPHONEOS_DEPLOYMENT_TARGET=9.0 carthage build --no-skip-current --platform ios
```

**Comment by ikesyo** [comment] 2017-05-15 05:07
This is a duplicate of #1622. Could you check https://github.com/Carthage/Carthage/issues/1622#issuecomment-267919074?

**Closed by ikesyo** 2017-05-15 05:07 UTC

**Comment by toshi0383** [comment] 2017-05-15 06:08
It worked, thanks! 
```
echo 'IPHONEOS_DEPLOYMENT_TARGET=9.0'>a; XCODE_XCCONFIG_FILE=a carthage build --no-skip-current
```
