### ISSUE TITLE
Add configuration support

### ISSUE THREAD

**Issue by benjohnde** [Carthage/Carthage#2348] opened 2018-02-12 14:11 UTC
In reply to https://github.com/Carthage/Carthage/pull/2312:

We always use the following command:
```
carthage update --platform iOS --cache-builds --no-use-binaries
```

Wouldn't it be nice to have some sort of shortcut in terms of a configuration file so that with
```
carthage update
```
all the magic happens?

I am asking this as we are very tired of having some one-liner additional script. Of course, one could also add a shortcut in his personal shell initialization file or just entering the whole command everytime.

**Comment by mdiep** [comment] 2018-02-12 14:12
Dupe of #356.

**Closed by mdiep** 2018-02-12 14:12 UTC

**Comment by benjohnde** [comment] 2018-02-12 14:18
Thanks @mdiep, only found the linked PR 🙃.
