### ISSUE TITLE
Not checking out the correct master

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Carthage/Carthage#1233] opened 2016-03-31 19:44 UTC
* `carthage version`: 0.15.2
* `xcodebuild -version`: Xcode 7.3
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "MailCore/mailcore2"
```

I'm trying to get this project called [MailCore](https://github.com/MailCore/mailcore2) via Carthage. Above is my `Cartfile`. It used to work fine before Xcode 7.3. Now I'm getting [this build error](https://github.com/MailCore/mailcore2/issues/1390). They have already implemented a fix for that in their master branch.

However when I update Carthage, the version it checks out somehow gets an old version where that fix is missing. I tried specifically mentioning the branch name in the `Cartfile` like so this.
```
github "MailCore/mailcore2" "master"
```

Still it doesn't pull down the correct master branch.

I already reported the issue to them as well. Posting it here also since I'm not sure where exactly the problem is.

**Comment by ikesyo** [comment] 2016-04-01 00:18
This is a duplicate of #1191 and will be fixed in the next release (fixed by #1202).

**Closed by ikesyo** 2016-04-01 00:18 UTC
Labels: bug, duplicate
