### ISSUE TITLE
Fork/Cache issue

### ISSUE THREAD

**Issue by kenji21** [Carthage/Carthage#2197] opened 2017-10-06 12:41 UTC
* `carthage version`: 0.25.0
* `xcodebuild -version`: Xcode 9.0 Build version 9A235
* Are you using `--no-build`? yes
* Are you using `--no-use-binaries`?  yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
# github "openium/TTGSnackbar" "5291302f3f850a0be93b888279d4701512d7d040"
github "zekunyan/TTGSnackbar" ~> 1.7
```

**Carthage Output**
```
*** Fetching TTGSnackbar
No available version for github "zekunyan/TTGSnackbar" satisfies the requirement: ~> 1.7.0
```

Carthage run with the openium 5291302f3f850a0be93b888279d4701512d7d040 commit was fine. But switching back to original repo (zekunyan) got the error:
No available version for github "zekunyan/TTGSnackbar" satisfies the requirement: ~> 1.7.0

After a:

````
rm -Rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/TTGSnackbar/
````

The 1.7.0 is correctly checked out and built

**Comment by ikesyo** [comment] 2017-10-06 12:45
This is a duplicate of #2143 and #2190.

**Closed by ikesyo** 2017-10-06 12:45 UTC

**Comment by kenji21** [comment] 2017-10-06 12:47
Oups, didn't checked before creating the issue. Sorry for the noise.
