### ISSUE TITLE
xcodebuild command line

### ISSUE THREAD

**Issue by neilpa** [Carthage/Carthage#429] opened 2015-04-19 20:49 UTC
Are the `xcodebuild ...` commands that carthage runs logged anywhere? I don't seem them in the generated build log

**Comment by robrix** [comment] 2015-04-19 21:30
Apparently not. I think that’d be pretty useful :+1:

**Comment by modocache** [comment] 2015-04-19 22:04
Probably a duplicate of #91?

**Comment by robrix** [comment] 2015-04-19 22:16
Good catch.

**Closed by robrix** 2015-04-19 22:16 UTC
Labels: enhancement, help wanted
