### ISSUE TITLE
Allow to inject build configuration settings

### ISSUE THREAD

**Issue by Johennes** [Carthage/Carthage#2206] opened 2017-10-11 13:49 UTC
* `carthage version`: 0.25.0

CocoaPods seems to have support for injecting build configuration settings. In [DTCoreText](https://github.com/Cocoanetics/DTCoreText) this is, for instance, used to enable consumers to either build an extension safe or an extension unsafe framework.

```
  spec.subspec 'Extension' do |ap|
    ap.source_files = 'Core/Source/*.{h,m,c}'
    ap.pod_target_xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) DT_APP_EXTENSIONS=1' }
  end
```

In Carthage, on the other hand, we can only build the extension-unsafe variant right now since there doesn't seem to be a way to inject build configuration settings.

**Comment by ikesyo** [comment] 2017-10-12 17:06
Looks like this is a duplicate of #1622 and #2192.

**Closed** 2017-10-14 06:56 UTC

**Comment by Johennes** [comment] 2017-10-15 18:21
Ah, I wasn't aware of the `XCODE_XCCONFIG_FILE` environment variable. Will give that a try. Thanks!
