### ISSUE TITLE
Unable to Build as Static Libraries

### ISSUE THREAD

**Issue by jsorge** [Carthage/Carthage#2200] opened 2017-10-06 20:44 UTC
* `carthage version`: 0.25.0
* `xcodebuild -version`: Xcode 9.0 Build version 9A235
* Are you using `--no-build`? Yes (on update, the error is happening on build)
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "rs/SDWebImage"
github "AgileBits/onepassword-extension"
github "hsousa/HCSStarRatingView"
github "facebook/facebook-ios-sdk"
github "CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout"
github "card-io/card.io-iOS-source"
github "nicklockwood/FXPageControl"
```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/_7/m_6wh_zj3qscy03tfskchfms8yj8vk/T/carthage-xcodebuild.spVF1P.log
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "CardIO" in icc.xcodeproj
*** Building scheme "CSStickyHeaderFlowLayoutCarthage" in CSStickyHeaderFlowLayoutDemo.xcworkspace
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKLoginKit-Dynamic" in FacebookSDK.xcworkspace

Caught signal triggered by the Swift runtime!
Illegal instruction

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.
...
many lines of the same Swift error
...
./staticbuild.sh: line 13: 39375 Segmentation fault: 11  carthage build --platform ios
```

I'm attempting to build static libraries as outlined [here](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md) and am doing so by triggering this script:

```
#!/bin/sh -e

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

echo "LD = $PWD/ld.py" >> $xcconfig
echo "DEBUG_INFORMATION_FORMAT = dwarf" >> $xcconfig
echo "ENABLE_BITCODE = NO" >> $xcconfig
echo "OTHER_CFLAGS = \$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks" >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"

carthage build --platform ios
```

I should also mention that in the console.app, no crash report is to be found in the build log.

Thanks for any help!

**Comment by jdhealy** [comment] 2017-10-06 20:48
This seems like a duplicate of `facebook-ios-sdk`-specific #2099.

**Closed by jdhealy** 2017-10-06 20:48 UTC

**Comment by jdhealy** [comment] 2017-10-06 20:50
@jsorge forgot to add, thanks for filing this 👍

**Comment by jsorge** [comment] 2017-10-06 20:52
Hope it can help. I've gotten some of the frameworks outputting properly if I change the order of things and am having boatloads of problems consolidating them into their own framework. Should I open a separate issue thread for that problem?

**Comment by jdhealy** [comment] 2017-10-06 21:04
> if I change the order of things and am having boatloads of problems consolidating them into their own framework

Not sure I follow: what is “them” referring to in that sentence?

**Comment by jsorge** [comment] 2017-10-06 21:05
Sorry, I can comment repos out and selectively get things to build if I do them one at a time (even got the Facebook one working at one point). So I'm having issues when they all are in my cartfile and active at once, as well as afterwards combining them into a dylib.

**Comment by jdhealy** [comment] 2017-10-06 21:19
Swapping in [`github "sugoi-wada/facebook-ios-sdk "780a72cd6086c57939d83a7143462ae13dfb9a74"`](https://github.com/sugoi-wada/facebook-ios-sdk/commit/780a72cd6086c57939d83a7143462ae13dfb9a74) would be the temporary fix (until it or some equivalent commit is merged by facebook). That should prevent you from getting "Illegal instruction" errors and output, so if "Illegal instruction" reoccurs after that (double check to make sure the fork actually gets checked out), then please file that as a new issue.

If you have non-Carthage-crash problems with particular frameworks (in isolation in a new Cartfile), then that's an issue for said framework’s developer, not us…

> as well as afterwards combining them into a dylib

A better venue is probably StackOverflow for this aspect (if you post there, feel free to link to it in another comment in this issue though).

**Comment by jsorge** [comment] 2017-10-06 21:23
Thanks! I'll give the Facebook fix a shot, and post in SO about the library combination.

**Comment by jsorge** [comment] 2017-10-06 21:34
I'm getting an error when trying to checkout the repo. Here's the error:
```
Failed to check out repository into /Users/jsorge/Library/Caches/org.carthage.CarthageKit/dependencies/facebook-ios-sdk: No object named "780a72cd6086c57939d83a7143462ae13dfb9a74" exists (Error Domain=CarthageKit.CarthageError Code=22 "(null)")
```

And here's the updated cartfile:
```
github "rs/SDWebImage"
github "AgileBits/onepassword-extension"
github "hsousa/HCSStarRatingView"
# github "facebook/facebook-ios-sdk"
# Temporary Facebook SDK
github "sugoi-wada/facebook-ios-sdk" "780a72cd6086c57939d83a7143462ae13dfb9a74"
github "CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout"
github "card-io/card.io-iOS-source"
github "nicklockwood/FXPageControl"
```

**Comment by jdhealy** [comment] 2017-10-06 21:36
`rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies` should workaround that (on all affected machines)

sorry about that…

**Comment by jsorge** [comment] 2017-10-06 22:08
Perfect, thanks!

**Comment by jsorge** [comment] 2017-10-06 22:15
It's failing, and it appears to be doing so in the same place. Should I file a new issue like you referenced above?

**Comment by jdhealy** [comment] 2017-10-07 12:58
Same place meaning `Failed to check out repository into…`: no new issue, that’s well covered (can drop a reference, if so).

Same place meaning `Illegal instruction`: no new issue, unless we can determine it’s a different source of `Illegal instruction`.

Did it build for you at any point after switching to the fork?

Tried on my machine with `rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies &&
echo 'github "sugoi-wada/facebook-ios-sdk" "780a72cd6086c57939d83a7143462ae13dfb9a74"' | tee Cartfile && carthage bootstrap --platform iOS` and got the correct checkout and a successful build. That of course, with no `ld.py` config. If that command doesn’t succeed for you, we’ll delve deeper.

**Comment by jsorge** [comment] 2017-10-09 15:04
Sorry I wasn't clear before. I wrote it clearly in my head 🙂.

I ran your command chain that you pasted in the 4th paragraph and when building the FBSDKLoginKit-Dynamic, I'm getting the Swift runtime crash. This is using the newer cartfile I put in my comment above, but not using my static framework script (so `ld.py` is not being used).

**Comment by jdhealy** [comment] 2017-10-09 17:22
`tee` in the command chain that I pasted in the 4th paragraph should overwrite/create the Cartfile (intended for a freshly-created empty directory, but I guess I didn't make that apparent). Did you execute that in your existing project directory? Mind trying somewhere empty?

**Comment by jsorge** [comment] 2017-10-09 18:14
I tested it out in a new working directory and the command chain built. I'll try it with the `ld.py` file and my build script for static frameworks and see if it will work there.

**Comment by jsorge** [comment] 2017-10-09 20:12
In the new directory, the build succeeded. I looked back at my original and the cartfile did indeed change. I'm going to paste my cartfile from above back in to the new directory and see if it works there.

**Comment by jsorge** [comment] 2017-10-09 20:45
Cool! It's now building using my script in both the old and new locations. Next up is to group the static libraries as a single dylib. If I continue having problems I'll open up a new issue.
