### ISSUE TITLE
copy-frameworks script phase fails with 0.36.0

### ISSUE THREAD

**Issue by stepheng** [Carthage/Carthage#3054] opened 2020-09-21 17:43 UTC
* carthage install method: [x] homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.36.0
* `xcodebuild -version`:  11.2.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? Yes

Builds are failing consistently... did not see any issues with prior version (0.34, 0.35, etc)

```
    /bin/sh -c ../Script-DCB3DAAC238BE6EA0088E6B0.sh

The file couldn’t be saved.
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by basdevelop** [comment] 2020-09-22 01:55
I met the same problem

**Comment by HyunjoonKo** [comment] 2020-09-22 02:40
I have the same problem. So I reinstalled the previous version.

```
$ brew uninstall carthage
$ brew tap-new company/team; brew extract --version 0.35.1 carthage company/team; brew install company/team/carthage@0.35.1
```
Then I ran the build again.
Xcode 12 should be built by referring to: https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323

**Comment by kscheff** [comment] 2020-09-22 08:13
Same issue with Xcode 11.7
```
xcodebuild -version
Xcode 11.7
Build version 11E801a

```

**Comment by PierreBrisorgueil** [comment] 2020-09-22 09:12
same issue xCode 12

**Comment by YangYouYong** [comment] 2020-09-22 11:59
Same issue Xcode 12
```
/usr/bin/xcrun lipo -create xxx
fatal error: 
xxx have the same architectures (arm64) and can't be in the same fat output file

```

**Comment by tmspzz** [comment] 2020-09-23 08:42
Duplicate of https://github.com/Carthage/Carthage/issues/3056

**Closed by tmspzz** 2020-09-23 08:42 UTC
