### ISSUE TITLE
RACError when running checkout or update

### ISSUE THREAD

**Issue by gfontenot** [Carthage/Carthage#311] opened 2015-02-11 23:11 UTC
Since updating to 0.5.3 via Homebrew, I'm unable to run `carthage checkout` or `carthage update` without getting a failing exit code and the following error message:

```
Error Domain=RACErrorDomain Code=0 "The operation couldn’t be completed. (RACErrorDomain error 0.)"
```

I don't see any logs generated, or any other messages printed to the console. This is true no matter the contents of the Cartfile.

If there's anything I can look for to make this issue even slightly useful, I'm happy to.

**Comment by jspahrsummers** [comment] 2015-02-11 23:15
Can you share your `Cartfile` and `Cartfile.resolved`?

**Comment by gfontenot** [comment] 2015-02-12 03:29
Aha! A clue! It seems to be related to a framework in a private GitHub repo. I thought changing it to a public repo had the same issue, but I was wrong.

**Comment by jspahrsummers** [comment] 2015-02-12 18:27
Does it reliably reproduce 100% of the time when using a private repository?

**Comment by gfontenot** [comment] 2015-02-12 18:33
Yep. It looks like it's able to clone the private repo fine, but when it tries to check out a commit/branch/tag, it blows up.

**Comment by jspahrsummers** [comment] 2015-02-12 18:36
Hmm, okay. Thanks for digging in!

**Comment by jspahrsummers** [comment] 2015-02-13 20:56
Turns out this is coming from https://github.com/Carthage/Carthage/pull/257, which I accidentally merged to `master` while trying to integrate https://github.com/Carthage/Carthage/pull/292. :disappointed:

I'll have it fixed in the next release.

**Closed** 2015-02-13 21:06 UTC
Labels: bug, help wanted
