### ISSUE TITLE
carthage update hanging

### ISSUE THREAD

**Issue by foobar8675** [Carthage/Carthage#670] opened 2015-08-12 18:05 UTC
my updates are hanging and am not sure how to troubleshoot. my terminal has been sitting like this for 5 minutes 

````
MATTHEWs-MBP:cognitoios matthewchung$ carthage update --verbose
*** Fetching AwesomeCache
*** Fetching Alamofire
*** Fetching KeychainAccess
````

here is my carfile

github "kishikawakatsumi/KeychainAccess"
github "Alamofire/Alamofire" 
github "aschuch/AwesomeCache"

**Comment by mdiep** [comment] 2015-08-12 18:38
Hmm… I'm not able to reproduce this. What's the output of `carthage version` and `git --version`? If you hit Control-C and try again, does it still hang?

**Comment by foobar8675** [comment] 2015-08-13 16:03
Thanks for writing back. I did hit control-c a couple times and it still
did not work. is there something off with the version I am using?


MATTHEWs-MacBook-Pro:wordbug-bluetooth matthewchung$ carthage version

0.7.2

MATTHEWs-MacBook-Pro:wordbug-bluetooth matthewchung$ git --version

git version 2.3.2 (Apple Git-55)

On Wed, Aug 12, 2015 at 11:38 AM, Matt Diephouse <notifications@github.com>
wrote:

> Hmm… I'm not able to reproduce this. What's the output of carthage version
> and git --version? If you hit Control-C and try again, does it still hang?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Carthage/Carthage/issues/670#issuecomment-130407025>.
>



-- 
Regards,
Matt

**Comment by mdiep** [comment] 2015-08-13 20:35
There were some hangs in previous versions that are hopefully fixed in the latest version. Please try with 0.8 and reopen if you're still experiencing problems. Thanks!

**Closed by mdiep** 2015-08-13 20:35 UTC
