### ISSUE TITLE
Carthage build with Xcode 8 fails with Clean error

### ISSUE THREAD

**Issue by dsqrbAES** [Carthage/Carthage#1542] opened 2016-10-20 17:04 UTC
This is the same issue reported as issue #1520 .  I tried the recommended solution and cleared the derived data, but I still get the same error. Any other ideas?

* `carthage version`: 0.18.1
* `xcodebuild -version`: 
* Are you using `--no-build` No
* Are you using `--no-use-binaries` Yes
* Are you using `--use-submodules` No

**Cartfile**
github "SnapKit/SnapKit" ~> 3.0

**Carthage Output**
*** Fetching SnapKit
*** Checking out SnapKit at "3.1.1"
*** xcodebuild output can be found in /var/folders/gq/90_79t_n0vjc4qy9l5kg_vwc0000gp/T/carthage-xcodebuild.TQXnF6.log

A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/dbrown/Desktop/EPDS-Control/Carthage/Checkouts/SnapKit/SnapKit.xcworkspace -scheme "SnapKit OSX" -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme SnapKit OSX is not currently configured for the clean action.

**Comment by ikesyo** [comment] 2016-10-26 00:59
Looks like there is no `SnapKit OSX` scheme: https://github.com/SnapKit/SnapKit/tree/3.1.1/SnapKit.xcodeproj/xcshareddata/xcschemes. Once you remove `Carthage/Checkouts/SnapKit` and re-run `carthage bootstrap` or `carthage update` should fix the issue (this seems to be a duplicate of #704).

**Closed by ikesyo** 2016-10-26 00:59 UTC
Labels: question

**Comment by dsqrbAES** [comment] 2016-10-26 18:31
I was able to get this to work by deleting all of the SnapKit folders and then running carthage update. This essentially gave me a clean set of files to work with from the start. This would be equivalent, although more drastic, than the action recommend by ikesyo.  Thanks for you help.
