### ISSUE TITLE
ReactiveCocoa: No object named "v3.0-beta.4" exists

### ISSUE THREAD

**Issue by memmons-ntst** [Carthage/Carthage#477] opened 2015-05-18 17:56 UTC
This is the cartfile I see @ColinEberhardt use in https://github.com/ColinEberhardt/ReactiveTwitterSearch

`github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.4"`

This the error I get when I try to run `carthage update`:
`/Library/Caches/org.carthage.CarthageKit/dependencies/ReactiveCocoa: No object named "v3.0-beta.4" exists`

That tag does indeed exist. Running `rm -rf ~/Library/Caches/org.carthage.CarthageKit` did not help.

Note it does work when I set the version to `~> 3.0`

**Comment by mdiep** [comment] 2015-05-18 20:02
This might be a duplicate of #469.

**Comment by jspahrsummers** [comment] 2015-05-19 22:56
Could you please run `git config --global --list` and share the results?

**Comment by memmons-ntst** [comment] 2015-05-29 23:13
```
color.diff=true
color.status=auto
color.branch=auto
merge.tool=textedit
aslias.last=log -1 HEAD
alias.unstage=reset HEAD --
alias.visual=gitk
core.editor=open -W -n
core.excludesfile=/Users/...../.gitignore_global
difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"
difftool.sourcetree.path=
mergetool.sourcetree.cmd=/Applications/SourceTree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"
mergetool.sourcetree.trustexitcode=true
credential.helper=osxkeychain
push.default=simple
filter.media.required=true
filter.media.clean=git media clean %f
filter.media.smudge=git media smudge %f
filter.hawser.clean=git hawser clean %f
filter.hawser.smudge=git hawser smudge %f
filter.hawser.required=true
filter.lfs.clean=git lfs clean %f
filter.lfs.smudge=git lfs smudge %f
filter.lfs.required=true

```

**Comment by 0xpablo** [comment] 2015-06-10 22:39
Could it be that OS X is replacing your quotes `"` with typographical ones `“`?
It is likely to happen if you are using TextEdit.

**Comment by memmons-ntst** [comment] 2015-06-11 14:52
I moved back to Carthage version 0.6.4, cloned RAC v3.0-beta.8 into a new directory and ran `carthage udpate`. At least it provides new/different errors.

```
*** Downloading Box at "1.2.2"
2015-06-11 07:48:45.134 carthage[76437:2079547] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9812)
2015-06-11 07:48:45.267 carthage[76437:2079547] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9812)
Error Domain=NSURLErrorDomain Code=-1202 "The operation couldn’t be completed. (NSURLErrorDomain error -1202.)" UserInfo=0x7fa8a3e52840 {NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x7fa8a3c81560 [0x7fff77ff4ed0]>, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9812, NSUnderlyingError=0x7fa8a3e0f4d0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1202.)", NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x7fa8a3c8f310 [0x7fff77ff4ed0]>",
    "<SecCertificate 0x7fa8a3ccda30 [0x7fff77ff4ed0]>"
), NSErrorFailingURLKey=https://github.com/robrix/Box/releases/download/1.2.2/Box.framework.zip, NSErrorFailingURLStringKey=https://github.com/robrix/Box/releases/download/1.2.2/Box.framework.zip, NSErrorClientCertificateStateKey=0}
```

**Comment by robrix** [comment] 2015-06-11 16:28
What happens if you clear out the cache, i.e. remove `/Library/Caches/org.carthage.CarthageKit/dependencies/ReactiveCocoa` ?

**Closed** 2015-11-17 15:54 UTC
Labels: question, update
