### ISSUE TITLE
Failed to read file or folder at

### ISSUE THREAD

**Issue by eddieh** [Carthage/Carthage#2482] opened 2018-06-11 19:18 UTC
* carthage install method: [ ] .pkg, [✔︎ ] homebrew, [ ] source
* `which carthage`:  /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.4 Build version 9F1027a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
binary "GoogleMobileAds.json" ~> 7.31
```

**GoogleMobileAds.json**
```
{
  "7.31.0": "https://dl.google.com/googleadmobadssdk/googlemobileadssdkios.zip"
}
```

**Carthage Output**
```
$ carthage update
*** Downloading binary-only framework GoogleMobileAds at "file:///Users/eddie/adc/admob-adapter-test-app-ios/GoogleMobileAds.json"
*** Downloading binary-only framework GoogleMobileAds at "file:///Users/eddie/adc/admob-adapter-test-app-ios/GoogleMobileAds.json"
*** xcodebuild output can be found in /var/folders/2j/89zxpszn74qc91r9wbqhb3n40000gn/T/carthage-xcodebuild.BSsLYz.log
Failed to read file or folder at /Users/eddie/adc/admob-adapter-test-app-ios/Carthage/Build/iOS/GoogleMobileAds.framework
```

**Actual outcome**
Everything works, but "Failed to read file or folder at" is printed.

**Expected outcome**
"Failed to read file or folder at" is not printed, because everything works just fine.

**Comment by eddieh** [comment] 2018-06-11 19:20
I think [#2468](https://github.com/Carthage/Carthage/issues/2468) is the same issue.

**Comment by ikesyo** [comment] 2018-06-11 23:44
This is a duplicate of #2480.

**Closed by ikesyo** 2018-06-11 23:44 UTC
