### ISSUE TITLE
v0.12 fails when resolving redundant dependencies

### ISSUE THREAD

**Issue by jongraves** [Carthage/Carthage#1093] opened 2016-02-03 20:57 UTC
I have a repository that relies on a particular sub-repository. Both the parent repository and the sub-repository have Cartfiles that specify a dependency on a framework 'foo' on branch 'master'. v0.12 of Carthage fails to resolve the redundant dependency gracefully and gives this error:

```
Could not pick a version for git "<repo_url_redacted>", due to mutually incompatible requirements:
	"dfde365d378a620272a168c206a547cd84ff8230"
	"master"
```

The specified SHA is the latest commit on master and is not referenced explicitly in either Cartfile.

v0.11 of Carthage has no problem resolving these dependencies.

**Comment by exsortis** [comment] 2016-02-03 21:05
+1 This is happening to me as well with v0.12.

**Comment by ikesyo** [comment] 2016-02-03 22:47
This is a duplicate of #1080 and #765.

**Closed by ikesyo** 2016-02-03 22:47 UTC
