### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by txaiwieser** [Carthage/Carthage#2927] opened 2020-02-04 18:24 UTC
Hi, is there a plan to release a new version soon? My team is depending on some fixes that were made in develop

**Comment by tmspzz** [comment] 2020-02-05 09:13
I'm all up for a release. If I recall correctly however there are some problems around that, @jdhealy can maybe pitch in here.

**Comment by txaiwieser** [comment] 2020-02-06 19:56
Problems in `master` or problems on the release process? @jdhealy

**Comment by txaiwieser** [comment] 2020-02-17 12:42
Any info?

**Comment by dersim-davaod** [comment] 2020-03-02 10:08
I would like to add that my team is also very interested in new features Carthage has in `master`, and eagerly waiting for the new release.

Could you please shed some light on the plans?

/cc @tmspzz @jdhealy

**Comment by ianthetechie** [comment] 2020-03-19 06:46
Bugs or no, the current latest build is pretty much unusable.

**Comment by CraigSiemens** [comment] 2020-03-26 15:52
☝️ I agree with this, especially since the released version doesn't support using prebuilt swift binaries that were build with a different version of the compiler (https://github.com/Carthage/Carthage/issues/2958).

**Comment by mendesbarreto** [comment] 2020-03-30 17:30
Hey guys, I look forward to the next release too, our team need as well =)

**Comment by vrutberg** [comment] 2020-04-01 14:14
Just wanted to report that I'm also looking forward to a new release of Carthage.

Also, could the maintainers shed some light on any future plans for Carthage?

**Comment by bguidolim** [comment] 2020-04-08 16:59
+1

**Comment by CraigSiemens** [comment] 2020-04-19 03:14
@tmspzz @jdhealy Is there something that's blocking the creation of a new release? 

I was trying to look into what it would take to make a new release and there's something weird about how the 0.34.0 release was done. It's got its own branch but was never merged into master and now master still says it's 0.33.0.

**Comment by mozeryansky** [comment] 2020-04-19 03:20
@CraigSiemens I filed the 0.33.0 issue on master (https://github.com/Carthage/Carthage/issues/2964) it was quickly fixed already. But I also noticed the release branch wasn't merged in.

I've heard of discussion on how to maintain a branch without merging it in. If that's the issue, I suggest tagging the release (as is done), and merging the tag. That that there will be a merge, but the release branch will still point to the top of the release.

**Comment by teodorpenkov** [comment] 2020-05-05 11:54
Is this going to be answered or we should start migrating away from Carthage?

**Comment by bguidolim** [comment] 2020-05-05 11:57
@teodorpenkov I've migrated, but not away, from Carthage. In the company, we're now using this fork https://github.com/nsoperations/Carthage

So far so good.

**Comment by bpollman** [comment] 2020-05-14 01:02
> @teodorpenkov I've migrated, but not away, from Carthage. In the company, we're now using this fork https://github.com/nsoperations/Carthage
> 
> So far so good.

Wow. This fork looks awesome. So much development has been done. Will be giving it a go.

**Comment by kenji21** [comment] 2020-05-15 09:28
or you could try https://github.com/openium/CartfileToPackage.swift to migrate to SPM

**Comment by JackoPlane** [comment] 2020-05-18 01:23
@tmspzz @jdhealy Has there been any progress on a release?

**Comment by ikesyo** [comment] 2020-05-19 00:11
At the time of May 2020, App Store requires submitted apps to be built using Xcode 11, which requires macOS Mojave 10.14.3 or later. That means that we do not need to support High Sierra anymore.

https://developer.apple.com/app-store/submissions/

> ## Build with Xcode 11.
> Xcode 11 includes Swift 5 and the latest SDKs for all Apple platforms. With Swift 5, runtime is built into iOS, iPadOS, macOS, tvOS, and watchOS so your app no longer needs to bundle this library for these latest OS releases. Users who download an app built with Swift from the App Store will get a smaller app and a faster download.
> 
> Starting April, 2020, all apps submitted to the App Store will need to be built with Xcode 11. Xcode 11 requires macOS Mojave 10.14.3 or later.

**Comment by jdhealy** [comment] 2020-06-04 16:15
Pretty simply, we keep finding bugs on `master`. Regressions that slip past our unit (and small number of integration) tests. Stuff that, when we look at particular popular frameworks in combination, we realize would cause major issues.

Most of the voices in this thread seem [reflecting on a new feature](https://github.com/Carthage/Carthage/issues/2927#issuecomment-604510244), but I think it's pretty likely there's a silent majority that massively favors¹ thorough regression elimination over any particular new feature.

Important to note that a wide number of Carthage CI invocations are not pinned to a particular Carthage version 〜 _In other words_: at some point in the future, a new Carthage version could be placed under some unassuming CI run — _maybe upon opting into a new Xcode beta, but maybe not even as 'choice/side-effect'–oriented as that, maybe just under any particular run_ — and the lack of regressions keeps that system intact.

- _Is this fair to folks wanting new features on a timely basis?_ Nope, but that's the status quo.

- _Is it particularly easy for my CI — if I want to install my own Carthage master-branch-build or variant — to find a guide on how to do so?_ Unfortunately, there's not a great easy guide… but we would love (and gladly help peer review) a contribution ☀️ 

Hopefully, a new release is shaping up (as we work our way through fixing the regressions we know about) and we’ll keep y'all informed with the latest in this thread.

**Comment by tmspzz** [comment] 2020-06-04 18:25
If your CI supports if you can distribute and install your own version of Carthage via homebrew by writing your own formula. You can even commit this formula to your repo or create your own tap.

carthage.rb 
```ruby
class Carthage < Formula
  desc "My Carthage master build"
  homepage "https://github.com/Carthage/Carthage"
  url "https://path/to/carthage.zip"
  sha256 "a7bf815a3491119a038f70a975f1d3331a519edb09f4e0aaa7eea68e4b8e9f39" # shasum -a 256 carthage.zip

  bottle :unneeded

  def install
    bin.install "carthage"
  end

  test do
    system "#{bin}/carthage", "version"
  end
end
```

To use it just do
```
brew unlink carthage && brew install carthage.rb
```

**Comment by byaruhaf** [comment] 2020-06-04 18:30
+1

**Comment by mozeryansky** [comment] 2020-06-04 18:46
Based off another comment, our CI now uses the latest master: `brew install carthage --HEAD`. Hopefully, that doesn't break.

**Comment by jdhealy** [comment] 2020-06-04 18:48
@mozeryansky, I _would not_ rely upon that — plus, you probably don't want to recompile Carthage upon every CI run…

**Comment by kenji21** [comment] 2020-06-04 18:49
really impatient to have swift 5.3 released (SPM package binary support), got some idea to build once the dependencies and then "cache" them for the CI to be as fast as possible

soon sherlocked...

**Comment by kenji21** [comment] 2020-06-04 18:51
I still think, that carthage is a huge tool and piece of code for our community, many thanks to the team and all contributors

**Comment by mozeryansky** [comment] 2020-06-04 19:01
@jdhealy Yeah I know, but we had to get past the swift binaries issue. It's been working for a while now, we can always go with more complicated/safer solution if needed. It does add ~4mins to the CI time, could use caching, but we're no where near our CI time limit. Mostly, I rather not switch to the forked Carthage repos people have been linking.

**Comment by jdhealy** [comment] 2020-06-04 19:09
@mozeryansky, okay, cool — appreciate that comment as an artifact of ‘here’s what we did’; definitely don’t want folks interpreting that as general advice (_especially as [more general advice is starting to be crafted upthread](https://github.com/Carthage/Carthage/issues/2927#issuecomment-639028236)_)

Because folks deserve a more thoroughly crafted description of the trade-offs and risks and easy mitigation techniques. :sunny:

**Comment by RobertoMachorro** [comment] 2020-06-04 19:15
> Pretty simply, we keep finding bugs on `master`. Regressions that slip past our unit (and small number of integration) tests. Stuff that, when we look at particular popular frameworks in combination, we realize would cause major issues.

Thank you for the clarification. This helps a lot and alleviates the concerns we've been expressing here.

> Hopefully, a new release is shaping up (as we work our way through fixing the regressions we know about) and we’ll keep y'all informed with the latest in this thread.

As a Carthage user, this is definitely something to look forward to!

**Comment by tmspzz** [comment] 2020-06-04 19:24
@mozeryansky I updated my comment with more complete instructions

**Comment by RobertoMachorro** [comment] 2020-06-19 16:32
Woot! New release 👍 
I guess this issue is good to close?

**Comment by jdhealy** [comment] 2020-06-19 17:16
Closed by https://github.com/Carthage/Carthage/releases/tag/0.35.0 — see release notes for info.

**Closed by jdhealy** 2020-06-19 17:16 UTC

**Comment by michaeleisel** [comment] 2020-07-10 14:20
thanks for doing this release. i wonder a few things:
- could there be more communication in high-profile tickets like the swift module stability one about why there's no release forthcoming?
- what if there were faster minor releases that just backported the most desired features onto the latest version? or at least, some kind of decently supported branch that people could opt into. i think that would take the pressure off for big new releases, if the rate of regressions remains unchanged
