### ISSUE TITLE
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/texturegroup/texture.git /Users/myfolders/Library/Caches/org.carthage.CarthageKit/dependencies/texture) failed with exit code 128: error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

### ISSUE THREAD

**Issue by caosuyang** [Carthage/Carthage#2404] opened 2018-04-03 09:38 UTC
* carthage install method:  [ ] homebrew
* `which carthage`:
* `carthage version`: 0.29.0
* `xcodebuild -version`: Version 9.3 (9E145)
* Are you using `--no-build`? No.
* Are you using `--no-use-binaries`?    No.
* Are you using `--use-submodules`?    No.
* Are you using `--cache-builds`?    No.
* Are you using `--new-resolver`?    No.

**Cartfile**
```
github "SVProgressHUD/SVProgressHUD"
github "Alamofire/Alamofire" ~> 4.7
github "SwiftyJSON/SwiftyJSON"
github "alibaba/HandyJSON" ~> 1.8.0
github "onevcat/Kingfisher" ~> 4.0
github "IBanimatable/IBAnimatable"
github "jiecao-fm/SwiftTheme"
github "ReactiveX/RxSwift" ~> 4.0
github "stephencelis/SQLite.swift" ~> 0.11.4
github "BrikerMan/BMPlayer"
github "airbnb/lottie-ios" "master"
github "texturegroup/texture" "master"
```

**Carthage Output**
```
*** Cloning texture
*** Fetching SwiftTheme
*** Fetching lottie-ios
*** Fetching SVProgressHUD
*** Fetching RxSwift
*** Fetching Alamofire
*** Fetching HandyJSON
*** Fetching IBAnimatable
*** Fetching SwiftyJSON
*** Fetching Kingfisher
*** Fetching BMPlayer
*** Fetching SQLite.swift
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/texturegroup/texture.git /Users/myfolders/Library/Caches/org.carthage.CarthageKit/dependencies/texture) failed with exit code 128:
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Actual outcome**
Carthage did cloned SVProgressHUD.framework.

**Expected outcome**
Carthage should clone all frameworks.

**Comment by blender** [comment] 2018-04-03 10:15
This looks like and error while closing. Look at the message.


Can you reliably reproduce this?

**Comment by mdiep** [comment] 2018-04-03 10:42
This isn't really a Carthage issue, since carthage just uses git to clone. If you copy out that `git clone` command and run it separately, you should see the same thing.

**Closed by mdiep** 2018-04-03 10:42 UTC

**Comment by caosuyang** [comment] 2018-04-04 03:59
Thanks for your advice, it is a problem of git clone. Later, I tried to annotate some framework in Cartfile, and then one of the git third-party libraries in each clone file was successfully cloned.

Finally, when I tried the corresponding `texturegroup/texture` third-party library in the clone file, the result was a failure. I tried to solve this problem using `git config --global http.proxy "localhost:1080"`, but it didn't work.

**Cartfile**
```
# github "SVProgressHUD/SVProgressHUD"
# github "Alamofire/Alamofire" ~> 4.7
# github "onevcat/Kingfisher" ~> 4.0
# github "alibaba/HandyJSON" ~> 1.8.0
# github "SwiftyJSON/SwiftyJSON"
# github "IBanimatable/IBAnimatable"
# github "jiecao-fm/SwiftTheme"
# github "ReactiveX/RxSwift" ~> 4.0
# github "stephencelis/SQLite.swift" ~> 0.11.4
# github "BrikerMan/BMPlayer"
# github "airbnb/lottie-ios" "master"
  github "texturegroup/texture" "master"
```

**Carthage Output**
```
➜  CFTodayNews git:(master) ✗ carthage update --platform iOS
*** Fetching texture
*** Cloning libwebp
*** Fetching PINOperation
A shell task (/usr/bin/env git clone --bare --quiet https://chromium.googlesource.com/webm/libwebp /Users/myfolders/Library/Caches/org.carthage.CarthageKit/dependencies/libwebp) failed with exit code 128:
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

➜  CFTodayNews git:(master) ✗ carthage update --platform iOS
*** Fetching texture
*** Cloning libwebp
*** Fetching PINOperation
A shell task (/usr/bin/env git clone --bare --quiet https://chromium.googlesource.com/webm/libwebp /Users/myfolders/Library/Caches/org.carthage.CarthageKit/dependencies/libwebp) failed with exit code 128:
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

➜  CFTodayNews git:(master) ✗ git config --global http.proxy "localhost:1080"
➜  CFTodayNews git:(master) ✗ carthage update --platform iOS
*** Fetching texture
*** Cloning libwebp
*** Fetching PINOperation
*** Checking out PINRemoteImage at "3.0.0-beta.13"
*** Checking out PINOperation at "1.1.1"
*** Checking out libwebp at "v0.6.0"
*** Checking out PINCache at "3.0.1-beta.6"
*** Checking out texture at "1e8c6f0e0f7f94936e4461e5cc731cb7c0a745d1"
*** xcodebuild output can be found in /var/folders/93/syn9l9_x3sl_jk0cgpfx4j2h0000gn/T/carthage-xcodebuild.NFC6P9.log
*** Downloading PINOperation.framework binary at "Just fixing some warnings"
*** Downloading PINCache.framework binary at "3.0.1-beta.6"
*** Downloading PINRemoteImage.framework binary at "3.0 beta 13: Animated WebP support / better GIF handling"
*** Skipped building libwebp due to the error:
Dependency "libwebp" has no shared framework schemes for any of the platforms: iOS
*** Building scheme "AsyncDisplayKit" in AsyncDisplayKit.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/myfolders/Downloads/Github/CFTodayNews/CFTodayNews/Carthage/Checkouts/texture/AsyncDisplayKit.xcworkspace -scheme AsyncDisplayKit -configuration Release -derivedDataPath /Users/myfolders/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/texture/1e8c6f0e0f7f94936e4461e5cc731cb7c0a745d1 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=28A7301C-03D9-4878-9C0B-7BA6227B3199 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/myfolders/Downloads/Github/CFTodayNews/CFTodayNews/Carthage/Checkouts/texture)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/93/syn9l9_x3sl_jk0cgpfx4j2h0000gn/T/carthage-xcodebuild.NFC6P9.log
```
