### ISSUE TITLE
Feature request: Supports build and combine each platform framework to `XCFramework` for Xcode 11

### ISSUE THREAD

**Issue by dreampiggy** [Carthage/Carthage#2811] opened 2019-06-19 09:35 UTC
* carthage install method:  [x] homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`: Xcode 11.0

#### Feature request

See WWDC Session: https://developer.apple.com/videos/play/wwdc2019/416/
Xcode Release Notes: [New Features - XCFramework](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_2_release_notes#3318304)

Xcode 11 introduce a new bundled framework format: `.xcframework`

It can contains all of massive platform && architecture combination of current `.framework`.

For example, if your framework supports all Apple platform, you'll need 4 targets and generate 8 frameworks. If you support Static Framework, this number bumped to 16.

+ iOS(armv7 arm64)
+ iOS Simulator (x86_64)
+ macOS (x86_64)
+ macOS UIKit (x86_64)
+ tvOS(arm64)
+ tvOS Simulator (x86_64)
+ watchOS (armv7k arm64_32)
+ watchOS SImulator (x86_64)

Then when you have 8 frameworks, you need to open Finder and drag them one by one for your Application target. You should also be careful not to mix them up (such as drag a iOS framework into WatchKitExtention target).

It's cool if Carthage can automatically generate one `XXX.xcframework` which combine all the individual framework for all valid target, then let user just drag one is OK.

![image](https://user-images.githubusercontent.com/6919743/59750941-3571df80-92b2-11e9-8fa9-264b0a9d4cc1.png)

Note the `xcframework` can also be dependented, so it's also cool for framework author, to just dependency one `Carthage/build/YYY.xcframework` in Xcode build setting.

**Comment by blender** [comment] 2019-06-19 12:59
Duplicate of #2799

**Closed by blender** 2019-06-19 12:59 UTC
