### ISSUE TITLE
bad CPU type in executable: carthage

### ISSUE THREAD

**Issue by Rain-dew** [Carthage/Carthage#3332] opened 2023-03-29 02:22 UTC
I installed  latest  carthage.pkg in my Mac

When I check on the command line：

raindew@raindew-2 ~ % carthage version 
zsh: bad CPU type in executable: carthage

**Comment by DeveloperLinus** [comment] 2023-04-26 05:42
me to

**Comment by BMinas** [comment] 2023-07-17 17:56
I just had the same problem.  The package installs ARM64 on an Intel Macbook.

**Comment by J-Swift** [comment] 2023-07-22 23:31
Yep, when you run `file` on it, it reports:

`Mach-O 64-bit executable arm64`

**Comment by jdhealy** [comment] 2023-12-31 22:43
Duplicate of https://github.com/Carthage/Carthage/issues/3323

**Closed** 2023-12-31 22:43 UTC
