### ISSUE TITLE
Build local project without creating a git repo

### ISSUE THREAD

**Issue by ceichin** [Carthage/Carthage#2212] opened 2017-10-12 17:34 UTC
Is it possible to use Carthage for building local projects **without** creating a git repo inside that folder? Like just specifying the folder path in the cartfile.

Now I'm using: `git "./../myproject" "master"`, but I need to create a repo just for that folder, and for each change we have to commit. It's like a dummy repo, inside the real repo.

Is there a way to do this without creating this dummy repo? Thanks!

**Comment by ikesyo** [comment] 2017-10-13 00:02
This is a duplicate of #740.

**Closed by ikesyo** 2017-10-13 00:02 UTC
