### ISSUE TITLE
--cache-builds always see an invalid cache under certain circumstances

### ISSUE THREAD

**Issue by scottrhoyt** [Carthage/Carthage#1800] opened 2017-02-28 16:36 UTC
* `carthage version`: 0.20.0
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "Moya/Moya" "7.0.4"
```

**Carthage Output**
```
*** Fetching RxSwift
*** Fetching Alamofire
*** Fetching Result
*** Checking out Alamofire at "3.5.1"
*** Checking out Result at "2.1.3"
*** Checking out ReactiveCocoa at "v4.2.2"
*** Checking out RxSwift at "2.6.1"
*** Checking out Moya at "7.0.4"
*** xcodebuild output can be found in /var/folders/kk/vhmt6xwd5f17hfq_zz_lbnth0000gn/T/carthage-xcodebuild.3Q6zoJ.log
*** Valid cache found for Alamofire, skipping build
*** Invalid cache found for Result, rebuilding with all downstream dependencies
*** Valid cache found for RxSwift, skipping build
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "ReactiveCocoa-iOS" in ReactiveCocoa.xcworkspace
*** Building scheme "Moya iOS" in Moya.xcodeproj
*** Building scheme "ReactiveMoya iOS" in Moya.xcodeproj
*** Building scheme "RxMoya iOS" in Moya.xcodeproj
```

With this Cartfile, repeated runs of `carthage update --platform ios --cache-builds` detect an invalid cache for `Result` and rebuild it and it's dependents every time.

**Comment by jakeadams** [comment] 2017-02-28 17:32
@scottrhoyt do the dependencies reference different versions of `Result`?

**Comment by scottrhoyt** [comment] 2017-02-28 19:11
@jakeadams thanks. no, It appears that only the `ReactiveCocoa` dependency depends on `Result`.

**Comment by BobElDevil** [comment] 2017-02-28 20:55
So this is an interesting situation. The issue appears to stem from the fact that "ReactiveCocoa" includes "Result" in it's own workspace, and builds it. So what happens during every build is:
- Result builds  `Result.framework`, checksums it and puts that information in .Result.versionfile
- ReactiveCocoa builds a new copy of `Result.framework`, checksums it, and _replaces_ the other one (since the Build folder does not categorize by dependency), putting that info in .ReactiveCocoa.versionfile

So at this point, ReactiveCocoa has clobbered Results cache.

I'm not sure what the solution to this would even be. When developing for ReactiveCocoa it clearly wants to use the workspace and build everything itself (presumably with submodules). But when reactive cocoa itself is a dependency, we'd ideally use the project and not the workspace and let carthage just do the build ordering. We'd have to do something like "Share the workspace scheme... but don't tell carthage about it" which isn't really possible at the moment.

**Comment by scottrhoyt** [comment] 2017-02-28 23:18
Yeah, that is interesting. I don't know if this is high priority as ReactiveSwift has mostly superseded ReactiveCocoa (for Swift users at least) and at worst the behavior is the same as without cache, but it is an interest edge case to consider. Perhaps @mdiep has some thoughts about it considering ReactiveCocoa/ReactiveSwift are his wheelhouse?

**Comment by mdiep** [comment] 2017-03-01 13:47
ReactiveCocoa builds Result through its workspace (not with `carthage`). So I don't think that `Result.framework` should be getting placed in `Carthage/Build/`.

**Comment by BobElDevil** [comment] 2017-03-01 20:52
The problem is when ReactiveCocoa itself is a dependency. Carthage finds any shared schemes, including in workspaces (which it prefers). You can see this behavior if you checkout ReactiveCocoa and run no-skip-current. Then look at the version file contents

```
$ cat Carthage/Build/.ReactiveSwift.version                                                                                                                                                                                                                                                        
{
  "xcodeVersion" : "Xcode 8.2.1\nBuild version 8C1002",
  "commitish" : "1.1.0",
  "Mac" : [
    {
      "name" : "Result",
      "md5" : "9ae480bdb3a92d777eb3506a69580805"
    },
    {
      "name" : "ReactiveSwift",
      "md5" : "1c582b75e3acaae3b7fcd11e278cd9ec"
    }
  ]
}
```

**Comment by mdiep** [comment] 2017-03-06 14:05
Ah, okay. That makes sense. The version file needs to exclude dependency projects.

I think it's currently versioning all projects that are built (using the values sent on the build signal producer). Instead, I think it needs to locate the framework targets to be built in the project. That should generate the list without needing to filter out dependencies.

**Comment by BobElDevil** [comment] 2017-03-06 17:10
The version file actually does exactly what you said. It catches the output of the project build producer, prior to being merged with any upstream build producers. The problem is that ReactiveSwift itself is building Result, due to the workspace performing the build. (So Result.framework is actually being built twice, once by Result, once by ReactiveSwift)

For solutions, I'm thinking of a couple things:
- We accomplish something like the original suggestion in #1304 (though compatibility is an issue, so that's probably a no-go unless we get clever with symlinks)
- We allow a repo to exclude schemes when itself is included as a Carthage dependency. e.g., ReactiveSwift excludes it's workspace scheme, via something like a "carthage.excluded" file, so it can still be shared by developers, but when someone pulls it in, carthage skips over it and only builds the project shared scheme instead
- We allow a repo to essentially claim "I've got my dependencies covered (because I build them as submodules / a versioned Checkout folder)", and we skip any upstream dependencies for that project

I'm partial to the second solution, as it's the least invasive and would only require enhancing the 'project locator' logic.

**Comment by scottrhoyt** [comment] 2017-03-06 18:28
The second solution is very similar to what was proposed in #1616.

**Comment by BobElDevil** [comment] 2017-03-06 18:49
yeah pretty much the same idea, just a white list instead of black list. Even ignoring the --cache-builds flag, we still are building a framework twice (with possibly different versions). So it's another use case for wanting to share a scheme, but not wanting to share it with carthage. 

I'll let @mdiep chime in on this, since it seems we want to avoid this type of configuration if we can.

**Comment by mdiep** [comment] 2017-03-06 22:32
> We allow a repo to essentially claim "I've got my dependencies covered (because I build them as submodules / a versioned Checkout folder)", and we skip any upstream dependencies for that project

I think this is the right idea.

Carthage already knows what your dependencies are. We should leverage this and do the right thing automatically.

**Comment by BobElDevil** [comment] 2017-03-07 05:03
So how do we detect this case? Even though we know the dependencies, we can't actually detect which ones are built by the workspace vs. should be built for carthage.

Unless this is a valid case for `Cartfile.private`? i.e., ReactiveSwift puts 'Result' into its Cartfile.private because it's taking responsibility for providing the Result framework. This way when developing ReactiveSwift, one can update dependencies/submodules, but to others that pull in ReactiveSwift, it behaves like a 'leaf' dependency. This would require no additional changes in Carthage, just by any projects that specify 'included' dependencies in the public Cartfile.

**Comment by mdiep** [comment] 2017-03-07 13:04
The version file should never contain dependencies. There's already logic to rebuild if dependencies change [here](https://github.com/Carthage/Carthage/blob/8084f0691350e90fdcbd77fc7454a41540713d92/Source/CarthageKit/Project.swift#L962).

`xcodebuild -showBuildSettings -project path/to/ReactiveSwift.xcodeproj` shows:

```
FULL_PRODUCT_NAME = ReactiveSwift.framework
```

I think that's how we should be deciding what to save for each scheme.

**Comment by BobElDevil** [comment] 2017-03-07 17:00
@mdiep I think I confused things by putting that version file there. That's not the cause of the issue, it's the symptom. The issue being that ReactiveSwift is building Result in addition to itself. This is true whether we're caching builds or not, this is because of the workspace. If you run `carthage bootstrap` by itself, Result will build it's framework, and then ReactiveSwift will build it's workspace which builds both Result and ReactiveSwift. This is seen from the output of showBuildSettings
```
$ xcodebuild -showBuildSettings -workspace ReactiveSwift.xcworkspace -scheme ReactiveSwift-macOS | grep FULL_PRODUCT
    FULL_PRODUCT_NAME = Result.framework
    FULL_PRODUCT_NAME = ReactiveSwift.framework
```

Are you suggesting that we look for names of dependency frameworks and avoid even copying those results into the Carthage/Build folder? (but still take the hit of unnecessarily rebuilding it)?

**Comment by mdiep** [comment] 2017-03-07 20:13
ReactiveSwift is going to build Result either way. That's expected and shouldn't change.

We _shouldn't_ be copying the `Result.framework` that ReactiveSwift builds into the `Carthage/Build` folder—Carthage shouldn't know anything about that built framework. I didn't think we were doing that; but from your comment it sounds like we are?

**Comment by BobElDevil** [comment] 2017-03-07 20:37
Yes, we copy any produced frameworks from running the schemes we find. This is because we support repos that produce more than one framework out of one or many projects/workspaces. We don't actually 'know' currently that the frameworks produced were derived from sources in the Carthage/Checkouts folder as opposed to somewhere else in the repo. 

Looking through the build settings, we could probably check whether `PROJECT_FILE_PATH` dives into Carthage/Checkouts, and if it does, add it to a list of things to _not_ copy. However this would break a project if someone did solve the 'avoid redundant' builds situation by putting that dependency in `Cartfile.private`

I think we either need to blacklist certain schemes from carthage (we don't _really_ want ReactiveSwift to build Result if it's running as part of a carthage process, just when building it directly), or let the schemes build but have an explicit blacklist of frameworks to not copy.

**Comment by mdiep** [comment] 2017-03-08 13:48
> Yes, we copy any produced frameworks from running the schemes we find 

Then that's a serious bug. ReactiveSwift needn't build against the same version of Result—only a compatible one.

If ReactiveSwift is pinned to `Result == 1.0`, but you specify `Result ~> 1.1` in your root Cartfile, ReactiveSwift can still build against Result 1.0, but you should absolutely end up with Result 1.1..<2.0.

> we don't really want ReactiveSwift to build Result if it's running as part of a carthage process, just when building it directly

I think that _is_ what we want. We should respect how ReactiveSwift builds.

**Comment by BobElDevil** [comment] 2017-03-08 17:39
> I think that is what we want. We should respect how ReactiveSwift builds.

Thinking about it more that seems right, because if the project uses submodules, they may not have even added Carthage/Build/* to their framework search paths. So the workspace may be the only way to build properly. 

Then I think the solution here what I mentioned above about the project directory. If we add that to the BuildSettings, and then filter results out from the frameworks to copy (the same place we filter out non-dynamic framework targets), it won't be copied at all, which means we'll copy the correct final version, and we won't be clobbering build caches. Does that sound like a reasonable solution? If so, I'll take a look later this week if I have the chance.

**Comment by mdiep** [comment] 2017-03-08 20:19
That sounds reasonable. I'm not 100% certain that `PROJECT_FILE_PATH` does what we want. That would requires some investigation. But it sounds plausible.

**Comment by dodikk** [comment] 2017-03-13 10:49
```bash
carthage bootstrap --cache-builds --platform iOS

...
...
...

*** No cache found for PINCache, building with all downstream dependencies
*** No cache found for SwiftyJSON, building with all downstream dependencies
*** Building scheme "AsyncDisplayKit-iOS" in AsyncDisplayKit.xcworkspace
```

Carthage is constantly rebuilding `PINCache`, `SwiftyJSON ` and `AsyncDisplayKit ` for me. How can I check if I am experiencing the same issue?
P.S. My cartfile is listed below.


```bash
$ cat Cartfile
# General
github "FutureKit/FutureKit" "739674b6e69d9bb7ff56f207d0e3c9634657843a"
github "bitstadium/HockeySDK-iOS" == 4.1.3

# Network
github "Alamofire/Alamofire" == 4.3
github "SwiftyJSON/SwiftyJSON" == 3.1.4

# Feeds
github "Instagram/IGListKit" ~> 2.0.0

# Chat GUI
# github "eBay/NMessenger" == 1.0.79

github "facebook/AsyncDisplayKit" == 1.9.92
github "pinterest/PINCache" "3.0.1-beta.3"
github "pinterest/PINRemoteImage" "3.0.0-beta.3"
github "pinterest/PINOperation" "ef99f949015cf931e6078e8ba382a49f7132fdea"


# Chat
# github "robbiehanson/XMPPFramework" "85828804d9a03b41753b06a7919ce7aeda3efa40"
github "CocoaLumberjack/CocoaLumberjack" ~> 2.0
github "robbiehanson/CocoaAsyncSocket" ~> 7.5.1
# github "robbiehanson/KissXML" ~> 5.1.2
github "chrisballinger/libidn-framework" "2d01c969feb82c156189d2846fa97237b1a90e88"
```

**Comment by dodikk** [comment] 2017-03-13 10:53
Is it possible to add the `--no-build` option to some specific repositories in my `Cartfile`? 
See the example :

```bash

## Not building this one as I'd like to integrate it from source
github "facebook/AsyncDisplayKit" == 1.9.92 --no-build

## Building other dependencies as ususally
github "pinterest/PINCache" "3.0.1-beta.3"
github "pinterest/PINRemoteImage" "3.0.0-beta.3"
github "pinterest/PINOperation" "ef99f949015cf931e6078e8ba382a49f7132fdea"
```


P.S. Sorry for asking here if it's a wrong place.

**Closed** 2017-03-16 12:11 UTC
Labels: bug, help wanted
