### ISSUE TITLE
why SwiftyJSON is not building

### ISSUE THREAD

**Issue by ch-hui** [Carthage/Carthage#566] opened 2015-06-17 05:33 UTC
i wanna use Carthage to Integrate SwiftyJSON,but when i executed the carthage update command there is no .framework file in the Build catalog.somebody who knows how to fix it?

**Comment by ikesyo** [comment] 2015-06-17 05:57
This seems a duplicate of #532.

**Closed by ikesyo** 2015-06-17 05:57 UTC
Labels: build, question

**Comment by ikesyo** [comment] 2015-08-07 21:34
[0.8](https://github.com/Carthage/Carthage/releases/tag/0.8) is released, it should fix the issue.
