### ISSUE TITLE
Archive Failed Xcode 11.1 

### ISSUE THREAD

**Issue by pacu** [Carthage/Carthage#2888] opened 2019-10-08 22:27 UTC
* carthage install method: [ ] .pkg, [ ] homebrew, [x] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`:  Xcode 11.1 Build version 11A1027
* Are you using `--no-build`?  NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`? NO

**Cartfile**
```
github "grpc/grpc-swift"
github "stephencelis/SQLite.swift"
```

**Carthage Output**
```
*** Fetching SQLite.swift
*** Fetching grpc-swift
*** Checking out grpc-swift at "0.9.1"
*** Checking out SQLite.swift at "0.12.2"
*** xcodebuild output can be found in /var/folders/zd/zss_3kv112337jq_8hm28j540000gn/T/carthage-xcodebuild.g3QO3w.log
*** Building scheme "SwiftGRPC-Package" in SwiftGRPC-Carthage.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/pacu/Repos/ECC/ZcashLightClientKit/Carthage/Checkouts/grpc-swift/SwiftGRPC-Carthage.xcodeproj -scheme SwiftGRPC-Package -configuration Release -derivedDataPath /Users/pacu/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/grpc-swift/0.9.1 -sdk watchos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/zd/zss_3kv112337jq_8hm28j540000gn/T/grpc-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/pacu/Repos/ECC/ZcashLightClientKit/Carthage/Checkouts/grpc-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zd/zss_3kv112337jq_8hm28j540000gn/T/carthage-xcodebuild.g3QO3w.log
```

**Actual outcome**
Carthage did or did not build Swift-GRPC

**Expected outcome**
Carthage should... be nice and build my dependencies ?

Note: reproduced also in another different Mac with Xcode 11 GM Seed

**Comment by jdhealy** [comment] 2019-10-08 22:44
Could you run the same commands you did with `--verbose` passed to Carthage and see if `The following build commands failed: ¬ Ld /Users` appears in the output?

**Comment by ikesyo** [comment] 2019-10-09 00:46
Looks like this is a duplicate of https://github.com/grpc/grpc-swift/issues/507, closing.

**Closed by ikesyo** 2019-10-09 00:46 UTC
