### ISSUE TITLE
Update/Build specific schemas

### ISSUE THREAD

**Issue by RingoD** [Carthage/Carthage#2417] opened 2018-04-12 02:20 UTC
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.27.0
* `xcodebuild -version`: Xcode 9.3 Build version 9E145
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

There are multiple shared schemas in one of my repo. But actually, developers do not need all of them all the time. Maybe one or two of them are necessary. 
So will it be a command to specific the expected schemas to update and build?

**Comment by blender** [comment] 2018-04-12 09:26
Duplicate of: https://github.com/Carthage/Carthage/issues/1227

**Closed by blender** 2018-04-12 09:26 UTC
