### ISSUE TITLE
Infinite loop when using carthage update

### ISSUE THREAD

**Issue by DanielAsher** [Carthage/Carthage#2240] opened 2017-11-02 13:03 UTC
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`?  YES
* Are you using `--no-use-binaries`? YES
* Are you using `--use-submodules`? YES
* Are you using `--cache-builds`? NO

**Cartfile**
```
github "delba/Permission" ~> 2.0
github "mac-cain13/R.swift.Library" ~> 3.0
github "ReactiveX/RxSwift" "rxswift-3.0"
github "inamiy/RxAutomaton" "swift/3.0"
github "RxSwiftCommunity/RxDataSources"
github "RxSwiftCommunity/RxGesture"
github "RxSwiftCommunity/RxSegue"
github "RxSwiftCommunity/RxSwiftExt"
github "sunshinejr/RxPermission"
```

**Carthage Output**
```
$ carthage update --use-submodules --no-use-binaries --no-build RxSwift
*** Fetching R.swift.Library
*** Fetching RxAutomaton
*** Fetching RxSwift
*** Fetching RxPermission
*** Fetching RxGesture
*** Fetching RxSwiftExt
*** Fetching RxSegue
*** Fetching RxDataSources
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
*** Fetching Permission
^C
```

This behaviour seems to be triggered by changing ```github "ReactiveX/RxSwift" ~> 3.6``` to ```github "ReactiveX/RxSwift" "rxswift-3.0"```

**Comment by NachoSoto** [comment] 2017-11-02 23:12
This is because version resolution is failing. Duplicate of #733.

**Closed by NachoSoto** 2017-11-02 23:12 UTC
Labels: duplicate

**Comment by skyparentile** [comment] 2019-04-30 07:06
cleaning carthage cache fix the issue

`rm -rf ~/Library/Caches/org.carthage.CarthageKit`
