### ISSUE TITLE
Carthage freezes on *** Fetching ReactiveSwift

### ISSUE THREAD

**Issue by nikitabelosludtcev** [Carthage/Carthage#2241] opened 2017-11-02 18:05 UTC
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes

**Cartfile**
```
github "Alamofire/Alamofire" ~> 4.4
github "onevcat/Kingfisher" ~> 3.0
github "patchthecode/JTAppleCalendar"
github "ReactiveX/RxSwift" ~> 3.0
github "skywinder/ActionSheetPicker-3.0"
github "lyft/mapper"
github "RxSwiftCommunity/RxDataSources" ~> 1.0
github "Moya/Moya"
github "Hearst-DD/ObjectMapper"
github "tristanhimmelman/AlamofireObjectMapper"
github "Yalantis/PullToRefresh"
github "Swinject/Swinject" ~> 2.0.0
github "HKisd/SlideMenuControllerSwift" "f32eac06781f3dc9260adc6fdbe0eea5a5d9d505"
github "Swinject/SwinjectStoryboard" ~> 1.0.0
github "intercom/intercom-ios"
github "kishikawakatsumi/KeychainAccess"
github "HKisd/accept-sdk-ios" ~> 0.0
github "johnsundell/unbox" ~> 2.5.0
github "ashleymills/Reachability.swift"
github "mixpanel/mixpanel-swift"

```

**Carthage Output**
```
carthage update  --platform iOS --no-use-binaries --cache-builds
*** Fetching AlamofireObjectMapper
*** Fetching accept-sdk-ios
*** Fetching intercom-ios
*** Fetching Reachability.swift
*** Fetching Alamofire
*** Fetching Moya
*** Fetching RxSwift
*** Fetching ObjectMapper
*** Fetching RxDataSources
*** Fetching mixpanel-swift
*** Fetching unbox
*** Fetching PullToRefresh
*** Fetching Swinject
*** Fetching ActionSheetPicker-3.0
*** Fetching mapper
*** Fetching SwinjectStoryboard
*** Fetching Kingfisher
*** Fetching KeychainAccess
*** Fetching JTAppleCalendar
*** Fetching Result
*** Fetching ReactiveSwift
```

**Comment by NachoSoto** [comment] 2017-11-02 23:12
Duplicate of #733.

**Closed by NachoSoto** 2017-11-02 23:12 UTC
