### ISSUE TITLE
How does Carthage know where the Cartfile is?

### ISSUE THREAD

**Issue by mkistler** [Carthage/Carthage#1066] opened 2016-01-27 18:09 UTC
This question is related to #1047.  How does Carthage find the Cartfile for nested dependencies?

My xcodeproj is several levels deep into my git repo.  Carthage does find it and attempt to build it but fails because its dependencies -- specified in the Cartfile in the same directory as the xcodeproj -- were not built.

**Comment by ikesyo** [comment] 2016-01-27 18:15
This is a dupe of #1048.

**Closed by ikesyo** 2016-01-27 18:15 UTC

**Comment by mkistler** [comment] 2016-01-27 18:57
Sorry for the dupe ... I hadn't seen that.  Would it be possible to make Carthage look for Cartfiles in the directory where it finds an xcodeproj?
