### ISSUE TITLE
Failed installing carthage with homebrew

### ISSUE THREAD

**Issue by evgenyneu** [Carthage/Carthage#825] opened 2015-10-05 05:00 UTC
I am getting an error when installing brew with carthage on OS X 10.11 (15A284), Xcode 7.0.1 (7A1001):

> You are in 'detached HEAD' state. 

If I am trying to use homebrew to install other packages it shows the following error:

> Failed to recurse into submodule path 'Carthage/Checkouts/ReactiveCocoa'

brew install carthage
==> Cloning https://github.com/Carthage/Carthage.git
Cloning into '/Library/Caches/Homebrew/carthage--git'...
remote: Counting objects: 9652, done.
remote: Compressing objects: 100% (337/337), done.
remote: Total 9652 (delta 208), reused 0 (delta 0), pack-reused 9311
Receiving objects: 100% (9652/9652), 7.92 MiB | 246.00 KiB/s, done.
Resolving deltas: 100% (5975/5975), done.
Checking connectivity... done.
Note: checking out '52e1a006158793eff3c9890f1934f0b7cb64d2b8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

**Comment by ikesyo** [comment] 2015-10-05 07:43
This is a duplicate of #807 (and #818), please see that issue instead. :smiley:

**Closed by ikesyo** 2015-10-05 07:43 UTC
