### ISSUE TITLE
Inconsistent behavior with case insensitive Cartfile entries. 

### ISSUE THREAD

**Issue by bwhiteley** [Carthage/Carthage#2289] opened 2017-12-11 16:26 UTC
* `carthage version`: 0.27.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

If you try to update a single Cartfile entry, and the name on the command line differs from the proper repo name only by case, Carthage recognizes that the entry matches (doesn't error with "No entry found...") but proceeds to update all entries. 

It should either error with "No entry found..." or behave the same as if the case was correct. 

**Cartfile**
```
github "https://github.example.com/bwhiteley/F1" "master"
github "https://github.example.com/bwhiteley/F2" "master"

github "bwhiteley/SwiftBits" "master"```

**Carthage Output**
```
$ carthage update 
*** Fetching SwiftBits
*** Fetching F1
*** Fetching F2
*** Fetching F3
*** Checking out SwiftBits at "f26da1fff278e1edea3e8baed82f1c476924603d"
*** Checking out F1 at "90bc141fac786ecfab64cff725397352d8dcb7fe"
*** Checking out F3 at "1.0.1"
*** Checking out F2 at "9f9c8b4dfd343ee4e4cdef793d6df0f58697e01b"
*** xcodebuild output can be found in /var/folders/4r/5rcyrj_55nsf7c73sprfyn7r0000gr/T/carthage-xcodebuild.KNNJmc.log
*** Building scheme "F3" in F3.xcodeproj
*** Building scheme "F1" in F1.xcodeproj
*** Building scheme "F2" in F2.xcodeproj
*** Building scheme "SwiftBits" in SwiftBits.xcodeproj
$ 
$ 
$ carthage update F1
*** Fetching F1
*** Fetching SwiftBits
*** Fetching F2
*** Fetching F3
*** Checking out F1 at "90bc141fac786ecfab64cff725397352d8dcb7fe"
*** xcodebuild output can be found in /var/folders/4r/5rcyrj_55nsf7c73sprfyn7r0000gr/T/carthage-xcodebuild.nbqBRl.log
*** Building scheme "F3" in F3.xcodeproj
*** Building scheme "F1" in F1.xcodeproj
$ 
$ 
$ carthage update F1x
No entry found for dependency f1x in Cartfile.
$ 
$ 
$ carthage update f1
*** Fetching SwiftBits
*** Fetching F1
*** Fetching F2
*** Fetching F3
*** xcodebuild output can be found in /var/folders/4r/5rcyrj_55nsf7c73sprfyn7r0000gr/T/carthage-xcodebuild.qPHxvR.log
*** Building scheme "F3" in F3.xcodeproj
*** Building scheme "F1" in F1.xcodeproj
*** Building scheme "F2" in F2.xcodeproj
*** Building scheme "SwiftBits" in SwiftBits.xcodeproj
$ 
```

**Comment by jdhealy** [comment] 2017-12-11 19:39
@bwhiteley Very well put, great writeup.

Thanks for taking the time to file an issue; this is a duplicate of #1517, so (to keep tidy) I'll close this and further comments and status updates can go in #1517 👍

**Closed by jdhealy** 2017-12-11 19:39 UTC
