### ISSUE TITLE
Bootstrap with --no-build skips binaries downloading

### ISSUE THREAD

**Issue by Alexey-Matjuk** [Carthage/Carthage#2829] opened 2019-07-21 10:08 UTC
* carthage install method: [x] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.2.1 Build version 10E1001
* Are you using `--no-build`? Yes
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDynamicLinksBinary.json"
```

**Carthage Output**
```
No output
```

**Actual outcome**
Carthage did not download binaries

**Expected outcome**
Carthage should download binaries like it does for `carthage update --no-build`.  Because `--no-build` should 
> skip the building of dependencies after updating

but not preventing downloading of binaries.

**Workaround**
Run additional bootstrap without `--no-build` with required dependencies:
```
   carthage bootstrap --no-build
   carthage bootstrap FirebaseDynamicLinksBinary FirebaseAnalyticsBinary
```

**Comment by ikesyo** [comment] 2019-07-23 14:33
Duplicate of #2449.

**Closed by ikesyo** 2019-07-23 14:33 UTC
