### ISSUE TITLE
Carthage update going into loop when looking for no-existant branch

### ISSUE THREAD

**Issue by drekka** [Carthage/Carthage#1412] opened 2016-08-01 00:30 UTC
* `carthage version`: 0.16.2
* `xcodebuild -version`: XCode 8
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No

**Main Cartfile**
```
git "https://stash.odecee.com.au/scm/in/crux-lib.git" "develop"
github "drekka/Alchemic" "develop"
github "drekka/StoryTeller"
```

**Sub project (crux-lib) Cartfile**
```
github "Mantle/Mantle"
github "socketio/socket.io-client-swift" "development"
github "drekka/StoryTeller"
```

The carthage update is run from the main project directory.

As you can see from the log below, carthage is going into a loop starting at socket.io. This is the first time I've encountered this. 

This has appeared since making a change to the cart file. Previous I had socket.io pointing at a fork I had made to implement a patch. The socket.io people have accepted the patch and I have set the cartfile back to their repo. 

I think carthage could fail faster if a repo cannot be found.

**Carthage Output**
```
Dereks-MBP:crux-Clients derekclarkson$ ./update-dependencies.sh 
*** Fetching Alchemic
*** Fetching StoryTeller
*** Fetching crux-lib
*** Fetching pegkit
*** Fetching ocmock
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching pegkit
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching socket.io-client-swift
*** Fetching Mantle
*** Fetching socket.io-client-swift
*** Fetching Mantle
Failed to check out repository into /Users/derekclarkson/Library/Caches/org.carthage.CarthageKit/dependencies/socket.io-client-swift: No object named "development" exists
```

**Comment by ikesyo** [comment] 2016-08-01 00:50
Looks like this is a duplicate of #1167. Closing.

**Closed by ikesyo** 2016-08-01 00:50 UTC
