### ISSUE TITLE
In case of incompatible dependencies, carthage update must fail and report the incompatibility

### ISSUE THREAD

**Issue by leontiy** [Carthage/Carthage#2768] opened 2019-04-18 14:17 UTC
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: 
* Are you using `--no-build`? YES
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? YES
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`? tried both YES and NO

**Cartfile**
```
github "ReactiveCocoa/ReactiveSwift" ~> 6.0
github "ReactiveCocoa/ReactiveCocoa" ~> 9.0
```

**Carthage Output**
```
*** Fetching Nimble
*** Fetching Quick
*** Fetching ReactiveSwift
*** Fetching ReactiveCocoa
*** Fetching Result
*** Fetching Box
*** Checking out ReactiveCocoa at "v3.0-beta.9"
*** Checking out ReactiveSwift at "6.0.0"
*** Checking out Quick at "v2.0.0"
*** Checking out Result at "0.4.5"
*** Checking out Box at "1.2.2"
*** Checking out Nimble at "v8.0.1"
```

**Actual outcome**
Carthage ignored an explicitly specified version of ReactiveCocoa (that appears to be incompatible with that of ReactiveSwift) and checked out a beta version that has no dependency on ReactiveSwift.

**Expected outcome**
Carthage should exit with non-zero exit code and print an adequate error communicating that dependencies cannot be satisfied (preferably outlining a minimal subset of conflicting constraints).

**Comment by mdiep** [comment] 2019-04-19 12:32
This is a duplicate of #469.

**Closed by mdiep** 2019-04-19 12:32 UTC
