### ISSUE TITLE
Support XCFrameworks?

### ISSUE THREAD

**Issue by Droppix** [Carthage/Carthage#3012] opened 2020-07-10 07:17 UTC
Hi,

Is XCFrameworks already supported by carthage 0.35.0?
If yes, how to use it?

Thanks

**Comment by ikesyo** [comment] 2020-07-10 07:25
Duplicate of #2799, #2801, #2881.

**Closed by ikesyo** 2020-07-10 07:25 UTC

**Comment by Droppix** [comment] 2020-07-10 07:31
Sorry to raise you again, but it's not clear to me! I see you've been working on it, but when will it be available?

**Comment by tmspzz** [comment] 2020-07-13 13:39
XCFrameworks are not supported in `0.35.0` . The closet thing to a release schedule is this document atm but there aren't enough contributions to hit the goals. https://github.com/Carthage/Carthage/issues/2890
