### ISSUE TITLE
Mach-O header error when validating/submitting app

### ISSUE THREAD

**Issue by elsurudo** [Carthage/Carthage#1565] opened 2016-11-09 22:01 UTC
I've set up my project with Carthage, and I have a bunch of iOS dependencies. I added the `copy-frameworks` step as directed, as well.

Now, when I archive my build (which works) and then try to validate or submit for the App Store, I get an error: "Found an unexpected Mach-O header code: 0x72613c21".

There are a bunch of logs I can examine. Instead of pasting my own, they look basically exactly like the ones in this [CocoaPods ticket](https://github.com/CocoaPods/CocoaPods/issues/4450).

Basically, I get the following line repeated for every carthage framework:

```
2015-10-27 03:39:49 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7f8fe920b2e0:'/Users/Aladdin/Library/Developer/Xcode/Archives/2015-10-27/ABang 15-10-27 上午11.30.xcarchive/Products/Applications/ABang.app/Frameworks/SwiftyJSON.framework'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/Aladdin/Library/Developer/Xcode/Archives/2015-10-27/ABang 15-10-27 上午11.30.xcarchive/Products/Applications/ABang.app/Frameworks/SwiftyJSON.framework" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/Aladdin/Library/Developer/Xcode/Archives/2015-10-27/ABang 15-10-27 上午11.30.xcarchive/Products/Applications/ABang.app/Frameworks/SwiftyJSON.framework" did not contain a "archived-expanded-entitlements.xcent" resource.}
```

* `carthage version`: 0.17.2
* `xcodebuild -version`: Xcode 8.0 (Build version 8A218a)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No

Has anyone run into this issue? I've tried all the usual suspects (clean, clear derived data, etc.), but to no avail. Thanks!

**Comment by ikesyo** [comment] 2016-11-14 23:18
> 2015-10-27 03:39:49 +0000

Maybe you should fix your clock settings?

**Comment by elsurudo** [comment] 2016-11-14 23:20
That’s not actually my log – that’s a log from the linked ticket. My log is basically identical to that one (I was just too lazy to sanitize some things so I posted that one instead).

**Comment by Sn0wfreezeDev** [comment] 2016-11-28 13:32
I have the same issue. Have you been able to fix it ?

**Comment by elsurudo** [comment] 2016-11-28 15:52
I removed the Fabric/Crashlytics frameworks from my project, which were being embedded in the binary (not using Carthage to build these – they were pre-built).

This isn’t a long-term fix as I actually want to use those, but that was my workaround until I figure something better out.

**Comment by ikesyo** [comment] 2016-11-28 17:19
Looks like the issue is related to embedding static frameworks to your app bundle: https://twittercommunity.com/t/crashlytics-causing-build-failures-with-xcode-8-beta-2/70114/23. So this should not be a Carthage issue. Closing.

**Closed by ikesyo** 2016-11-28 17:19 UTC
Labels: question

**Comment by Sn0wfreezeDev** [comment] 2016-11-28 19:51
In my case it was an error with the AWSMobileHubHelper framework from Amazon placed into the wrong build phase.
https://forums.aws.amazon.com/thread.jspa?threadID=228725
