### ISSUE TITLE
Carthage copy-framework lipo issue

### ISSUE THREAD

**Issue by AlexisQapa** [Carthage/Carthage#3057] opened 2020-09-22 08:06 UTC
* carthage install method: [ ] .pkg, [ ] homebrew, [X ] source (via Mint)
* `which carthage`: N/A (via Mint)
* `carthage version`: 0.36.0
* `xcodebuild -version`: Xcode 11.7 - Build version 11E801a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no (but same result with it)
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no (but same result with it)
* Are you using `--new-resolver`? no

**Cartfile**
```
github "dbukowski/DBDebugToolkit" 
github "evgenyneu/keychain-swift"
github "realm/realm-cocoa"
github "ReactiveX/RxSwift"
github "RxSwiftCommunity/RxGesture"
github "RxSwiftCommunity/RxDataSources"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/ZendeskCoreSDK/ZendeskCoreSDK.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/SupportSDK/SupportSDK.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/SupportProvidersSDK/SupportProvidersSDK.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/CommonUISDK/CommonUISDK.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/MessagingSDK/MessagingSDK.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/MessagingAPI/MessagingAPI.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/SDKConfigurations/SDKConfigurations.json"
github "BatchLabs/ios-sdk"
```

**Carthage Output**
```
A shell task (/usr/bin/xcrun lipo -remove arm64 -output /var/folders/w7/n4xjtstd57lg8yx1cpy5lls80000gn/T/TemporaryItems/(A\ Document\ Being\ Saved\ By\ carthage\ 527)/carthage-lipo-9lRDF2/ZendeskCoreSDK.framework.dSYM/Contents/Resources/DWARF/ZendeskCoreSDK /var/folders/w7/n4xjtstd57lg8yx1cpy5lls80000gn/T/TemporaryItems/(A\ Document\ Being\ Saved\ By\ carthage\ 527)/carthage-lipo-9lRDF2/ZendeskCoreSDK.framework.dSYM/Contents/Resources/DWARF/ZendeskCoreSDK) failed with exit code 1:
fatal error: /Applications/Xcode 11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: -remove's specified would result in an empty fat file
```

**Actual outcome**
Carthage copy-framework failed due to issue while stripping architectures. The script is correctly working while building for devices or for generic iOS device and archiving but fail while building for simulators.

**Expected outcome**
Carthage should strip without issue while building for simulator.

**Comment by Droppix** [comment] 2020-09-22 08:21
same error
+1

**Comment by AlexisQapa** [comment] 2020-09-22 08:54
The issue persists using Xcode 12.0 - Build version 12A7209

**Comment by Droppix** [comment] 2020-09-22 08:56
same as...

**Comment by YangYouYong** [comment] 2020-09-22 11:56
same as...

**Comment by marinofaggiana** [comment] 2020-09-23 13:20
Yes +1 !! I must restart the mac for that

**Comment by tmspzz** [comment] 2020-09-23 13:56
Duplicate of https://github.com/Carthage/Carthage/issues/3019

**Closed by tmspzz** 2020-09-23 13:56 UTC

**Comment by AlexisQapa** [comment] 2020-09-23 15:49
I'm not sure this is a duplicate while I agree that the root cause is surely related to the one causing #3019 but workarounds provided in #3019 don't work for the copy-framework phase while working for me at the Carthage bootstrap phase.

**Comment by xzoky** [comment] 2020-10-20 19:05
@AlexisQapa did you end up finding a workaround for this? I'm getting the same problem with the Zendesk SDK 😕

**Comment by AlexisQapa** [comment] 2020-10-21 07:06
Sadly no, for now I'm using devices hoping for SPM official support coming soon and Xcode fixes for this
