### ISSUE TITLE
Carthage ignores specific projects to build and builds everything

### ISSUE THREAD

**Issue by fruitcoder** [Carthage/Carthage#1608] opened 2016-11-22 09:00 UTC
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1 Build version 8B62
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

I was trying to build a single framework which I thought works since the 0.12 release.
But `carthage build Apollo --platform iOS` builds the iOS schemes for all my dependencies. What am I doing wrong?

**Comment by ikesyo** [comment] 2016-11-22 09:05
Maybe you mean the library, right? https://github.com/apollostack/apollo-ios: `github "apollostack/apollo-ios"`. In that case you should pass `apollo-ios`, not `Apollo` (which will be Xcode project name or built framework name). So this is a duplicate of #1517. Closing.

**Closed by ikesyo** 2016-11-22 09:05 UTC
Labels: question

**Comment by fruitcoder** [comment] 2016-11-22 09:08
I tried `Apollo iOS` since that was the scheme name. Now it works like a charm, thanks!
