### ISSUE TITLE
Shared schemes from xcworkspace's

### ISSUE THREAD

**Issue by flovilmart** [Carthage/Carthage#395] opened 2015-03-20 03:17 UTC
I've encountered that problem today while working with SDWebImage.

It appears that when a project is embedded in a workspace, the shared schemes are moved from the xcodeproj to the xcworkspace, like physically moved.

Therefore, as it doesn't seems that Carthage looks for shared schemes in the xcworkspace the build command failed.
Is that by design or a problem on our side?

I'm afraid the next time some other dev edits the workspace, the scheme gets moved along and that breaks Carthage installation for everyone.

Thanks

F.

**Comment by jspahrsummers** [comment] 2015-03-21 04:07
You're right that Carthage only looks for schemes in a project file, not a workspace—this is by design, because it avoids picking up schemes for dependencies that may have also been added to a workspace.

I knew that schemes could be added directly to a workspace instead of a project, but I've never done it myself, and I haven't seen a real world example that does.

It _should_ be possible to move the schemes from the workspace back to the project file, although I admit I don't know how.

**Comment by flovilmart** [comment] 2015-03-21 04:40
The main issue is that it appears that Xcode moves the schemes by itself. Had the problem with SDWebImage as they use a workspace for demo app etc...




That make sense in design to prevent external schemes to be built, however, don't you think it would be possible to accommodate that use case?

**Comment by flovilmart** [comment] 2015-03-21 04:41
And for that matter we managed to move it back to the project, still I'm afraid that doesn't provide a long term solution if XCode moves shared schemes around :)

**Comment by jspahrsummers** [comment] 2015-03-21 17:12
> The main issue is that it appears that Xcode moves the schemes by itself.

I haven't seen this myself yet. Do you happen to know the exact steps that resulted in this behavior? If so, I can take a deeper look.

> That make sense in design to prevent external schemes to be built, however, don't you think it would be possible to accommodate that use case?

I definitely don't like the pseudo-magical approach we take today, but I'm not sure how else to read schemes from a workspace _and_ ignore dependencies.

As a user, how would you like Carthage to figure out which ones to skip?

**Comment by flovilmart** [comment] 2015-03-21 17:24
@jspahrsummers the Xcode moving scheme is pretty odd. it happened with SDWebImage project:
The SDWebImage.xcodeproj doesn't hold any schemes, they are all defined in the workspace. By adding a scheme to the project, it moved the file from .xcworkspace to .xcodeproj. Then adding the scheme back to the project did the opposite. Odd behaviour and not really reliable.

The SDWebImage team has put all schemes into the workspace, and with the current Carthage build system, that conflicts with the project design. 

Because we’re only building shared schemes we should not skip anything. When a project is organized around a workspace, only the framework shared schemes would be built (as it is today).
If a workspace exposes multiple shared schemes, and is known as Carthage compatible, it makes only sense to build the other schemes as well.

There we can infer multiple scenarios:
1. Workspace with Demo App + Framework (shared)
 Only build the shared schemes

2. Workspace with Demo App +  Multiple Frameworks + No carthage dependencies:
  Build every thing that has a shared scheme

3. Workpace with demo App +  multiple shared schemes (frameworks) + Carthage dependencies:
   Skip the schemes that conflict with carthage deps and build only the carthage + non conflicting schemes.

At build time, carthage should collect all Shared schemes in all projects and workspaces.
If two shared schemes have the same name, we should only build the project scheme.

What do you think?

**Comment by jspahrsummers** [comment] 2015-03-23 06:12
I think:

> Because we’re only building shared schemes we should not skip anything.

and:

> Skip the schemes that conflict with carthage deps and build only the carthage + non conflicting schemes.

… are problematic, because projects that are _otherwise_ Carthage compatible may still contain target dependencies that are not.

In other words, just because a scheme is shared doesn't mean that Carthage will be able to build it successfully. This is why the current approach is more “opt-in” oriented.

Maybe what we could do is fall back to using _all_ workspace schemes if the project file doesn't have any of its own. Would that have solved the SDWebImage case?

**Comment by flovilmart** [comment] 2015-03-23 11:58
In that case that would have solved the issue. But the most important is wether you scheme is in a project or in a workspace, it should be build.

**Comment by auibrian** [comment] 2015-04-08 02:58
Having spent some time trying to modify the AFNetworking project to build with Carthage one idea I've kept coming back to is that the project maintainer could provide some direction to Carthage. For instance a Carthage.xcodeproj, or a Carthage.xcworkspace or a file specifying what scheme to build from what project/workspace. The current method of discovery feels confusing and inexact from the standpoint of a framework maintainer, I had to do a certain amount of trial and error before eventually reading the code and then doing a bit more trial and error. As it is a lot of projects have test schemes and other sorts of targets that may be part of shared schemes that have no business being built when a Carthage user wants a framework. Explicit vs implicit/magic just feels best here.

**Comment by jspahrsummers** [comment] 2015-04-10 18:20
@auibrian I agree that an explicit indicator would benefit Carthage, but that implies that Carthage can't be used on projects without explicit support.

As it is right now, many projects with framework targets _should_ work mostly automatically—I think the projects requiring fixes (at least, those that already had a framework target) tend to be fairly uncommon by comparison.

**Comment by flovilmart** [comment] 2015-04-10 19:47
@jspahrsummers why does it implies that without an explicit indication that won't work?
Complex framework projects will happen, and already happen in fact, if there's some kind of Carthage specific configuration in order to properly build the project Carthage should use it, otherwise, the default build with shared scheme should happen. 

The simplistic aspect of Carthage should not prevent complex frameworks or projects to be compatible. What you're saying is that it's easier for the community to adapt to Carthage than the Carthage team to provide a nice and simple way to configure the build. 

We already have two major frameworks  (SDWebImage and AFNetworking) who can't work out of the box with Carthage. Those two frameworks are amongst the most popular in the community. 

I dunno about you, but if to be Carthage compatible FW maintainers need to refactor/rearchitecture their work, there's a major chance no one will ever make that effort. and in the end, Carthage might as well die as a nice try.

**Comment by neilpa** [comment] 2015-04-10 21:22
I mentioned in #396 a potential feature that may solve this issue too - an optional export/vend/etc. Cartfile node that lists the schemes for carthage to build. If omitted (as would be the case for most projects) carthage would simply build all shared schemes.

**Comment by jspahrsummers** [comment] 2015-04-11 04:43
> What you're saying is that it's easier for the community to adapt to Carthage than the Carthage team to provide a nice and simple way to configure the build.

@flovilmart What @auibrian has suggested here is _still_ “the community [adapting] to Carthage,” because the project maintainer would have to add some kind of Carthage-specific metadata or project file.

> We already have two major frameworks (SDWebImage and AFNetworking) who can't work out of the box with Carthage.

But SDWebImage does now, thanks to [your pull request](https://github.com/rs/SDWebImage/pull/1071). As far as I can tell, the changes there would be necessary for _any_ framework target anyways. A Carthage-specific workspace wouldn't help.

Likewise, AFNetworking is an issue because it doesn't have (and [doesn't want](https://github.com/AFNetworking/AFNetworking/pull/2552)) a framework target. A Carthage-specific workspace wouldn't help here either.

> if to be Carthage compatible FW maintainers need to refactor/rearchitecture their work, there's a major chance no one will ever make that effort.

**The most common change necessary is adding a framework target.** Because of the philosophical underpinning of Carthage, that step will _always_ be required.

There are sometimes other changes required, yes, but most incompatible projects today are incompatible because they don't support building a framework. That's a more fundamental issue than Carthage's minor requirements on top.

**Comment by flovilmart** [comment] 2015-04-11 05:04
The case of SDWebImage opened that exact issue if I recall correctly. So even if my PR provided part of the solution, the way SDWebImage is architectured may lead to some fuck-ups at build time.

And excuse me, but between adding a single metadata file and refactoring a project, you and I would go for the metadata.

**Comment by kzaher** [comment] 2015-05-24 00:56
I'm also confused why Carthage doesn't provide a way for project maintainers to specify a metadata file with explicit mappings of schemes and containers paths for those schemes.

The algorithm could go like this:
1. Try to look for a carthage metadata file (like .carthage-schemes)
2. If it finds that metadata file, build explicit schemes from it
3. If it doesn't find it, fallback to current magical behavior

.carthage-schemes could look something like
```
Project.xcodeproj  -> Scheme1
Project.xcodeproj  -> Scheme2
```

That is a backwards compatible way that would please everyone IMHO.

Could somebody please explain it to me what is wrong with this solution?

**Comment by jspahrsummers** [comment] 2015-05-24 20:07
@kzaher That seems like a fine solution. I [acknowledged above](https://github.com/Carthage/Carthage/issues/395#issuecomment-91643754) that an explicit solution would benefit Carthage.

**Comment by kzaher** [comment] 2015-05-24 21:48
Oh, sry, I've seen last comment on this on more then a month ago, and I thought this was dead.

I'm just curios when will this be possible? 

I couldn't find it anywhere documented so I don't know if I need to read documentation more carefully, it's not documented, doesn't work or is still in planning :)

**Comment by mdiep** [comment] 2015-05-24 23:22
@kzaher Someone just needs to do the work. Pull requests are very welcome. :smile

**Comment by flovilmart** [comment] 2015-05-24 23:29
Should we start working on agreeing on

1. Decision tree

2. Format of the meta/build directives file?

**Comment by jspahrsummers** [comment] 2015-05-27 01:07
I think this particular enhancement will depend upon https://github.com/Carthage/Carthage/issues/262, which is stalled for the time being while more critical work gets tackled.

**Comment by istx25** [comment] 2015-06-07 05:31
Was Carthage support ever approved/merged in?

**Comment by mdiep** [comment] 2016-05-22 01:00
The current behavior seems to be working well.

**Closed by mdiep** 2016-05-22 01:00 UTC
Labels: build, enhancement, question
