### ISSUE TITLE
Any updates on using zip-based NewRelicAgent inside a cartfile?

### ISSUE THREAD

**Issue by mlfarrell** [Carthage/Carthage#2136] opened 2017-08-24 18:02 UTC
I need to migrate
  pod 'NewRelicAgent'

Into my Carthage setup.  Is this still not possible?

**Comment by jdhealy** [comment] 2017-08-24 18:13
Were people working toward this library specifically before? (Please link if so).

Closing this as a duplicate of #214.

Maybe New Relic is your best bet for support. I'd try going to https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/get-started/ios-installation-configuration and clicking on “No” if you see “Was this page helpful?” to make a request from New Relic.

**Closed by jdhealy** 2017-08-24 18:13 UTC

**Comment by mdiep** [comment] 2017-08-25 12:06
Carthage supports binary-only frameworks now with the `binary` keyword. You might need to set up the requisite `json` file if NewRelic doesn't supply one. Please consult the Carthage documentation.
