### ISSUE TITLE
GITHUB_ACCESS_TOKEN environment variable has no effect with El Capitan

### ISSUE THREAD

**Issue by flovilmart** [Carthage/Carthage#815] opened 2015-10-01 00:26 UTC
The recently introduced GITHUB_ACCESS_TOKEN environment variable for private repositories has unfortunately no effet in El Capitan so the private github repositories respond with:

```fatal: could not read Username for 'https://github.com': terminal prompts disabled```

**Comment by furyu-ikeda-sho** [comment] 2015-10-01 00:29
`GITHUB_ACCESS_TOKEN`?

**Comment by flovilmart** [comment] 2015-10-01 00:29
that's what I meant...

**Comment by ikesyo** [comment] 2015-10-01 00:47
So is this dupe of #786?

**Comment by flovilmart** [comment] 2015-10-01 00:58
@ikesyo yeah you're right. I've investigated a bit the issue and that's pretty odd, in the carthage app code, accessing the env vars yields the proper values, but once in the CarthageKit code, it seems that nothing gets called...

**Comment by mdiep** [comment] 2015-10-01 13:46
We could switch things around to read those from `carthage`.

**Comment by flovilmart** [comment] 2015-10-01 13:47
That would defeat the purpose of the separation of concerns.

**Comment by mdiep** [comment] 2015-10-01 14:13
I don't think reading the environment variable has to be a CarthageKit concern.

**Comment by flovilmart** [comment] 2015-10-01 14:35
@mdiep ok then, Where do you suggest we set this property? as a static prop of Github.swift?

**Comment by mdiep** [comment] 2015-10-01 14:36
That should be fine.

**Comment by flovilmart** [comment] 2015-10-01 14:36
I'm gonna take care of it then!

**Comment by flovilmart** [comment] 2015-10-01 14:50
@mdiep question for you, has commandant the ability to run a command before each command? I'd load the proper environment in general as it may be used in multiple scripts (Update, Checkout etc...)

**Comment by flovilmart** [comment] 2015-10-01 15:11
So even with a public global var, it seems to keep not working. It's a pain to debug as when passing the environment vars from Xcode is works properly. May be it's related to my current configuration. tried in bash and zsh.

**Comment by flovilmart** [comment] 2015-10-07 17:03
See PR #834

**Comment by mdiep** [comment] 2015-12-15 02:34
Fixed by #891.

**Closed by mdiep** 2015-12-15 02:34 UTC
Labels: help wanted
