### ISSUE TITLE
Carthage not building with Xcode 10.1

### ISSUE THREAD

**Issue by nazrdogan** [Carthage/Carthage#2640] opened 2018-11-08 14:39 UTC
* carthage install method:homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`:  Xcode 10.1 Build version 10B61
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "SwiftyJSON/SwiftyJSON" ~> 4.0
```

**Carthage Output**
```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/nazirdogan/Desktop/TestApp/Carthage/Checkouts/SwiftyJSON/SwiftyJSON.xcworkspace -scheme SwiftyJSON\ iOS -configuration Release -derivedDataPath /Users/nazirdogan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/SwiftyJSON/4.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/70/3pxgbytj50b21v00vx_m15m00000gn/T/SwiftyJSON SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/nazirdogan/Desktop/TestApp/Carthage/Checkouts/SwiftyJSON)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/70/3pxgbytj50b21v00vx_m15m00000gn/T/carthage-xcodebuild.d5vi7P.log

```

**Actual outcome**
Carthage did not build frameworks. its just empty iOS project. it was fine before Xcode 10.1

**Expected outcome**
Carthage should build frameworks.

**Comment by blender** [comment] 2018-11-08 16:23
Did you check the logs?

**Comment by blender** [comment] 2018-11-08 22:58
I think this is a duplicate of https://github.com/Carthage/Carthage/issues/2613

**Closed by blender** 2018-11-08 22:58 UTC
