### ISSUE TITLE
Ability to specify Swift version number for binaries, or set no-use-binaries on a per-library basis in Cartfile?

### ISSUE THREAD

**Issue by dcosson** [Carthage/Carthage#1550] opened 2016-10-28 05:01 UTC
Just wondering if a fix for this situation is possible - I'm running into an issue rebuilding everything for Swift 3.0.1. Some projects like Realm are finicky/time-consuming to build from scratch but are well-supported and generally have a binary released that I trust (and in this case, it's already been updated for 3.0.1). But other dependencies, especially smaller libraries, might have binaries that are updated much less often so they're built with an old version of swift.

I didn't want to build my whole project with no-use-binaries, so now I'm having to go through one by one for the handful of libraries where the binaries are still built with swift 3.0.0 and build them individually.

Would it be possible to specify a swift version in Carthage, and only download binaries if they're built with that version or higher?

Or alternatively, to specify in the Cartfile that some libs should be built with --no-use-binaries by default?

**Comment by mdiep** [comment] 2016-11-02 00:55
This is a duplicate of #1354. Pull requests welcome. 😄

**Closed by mdiep** 2016-11-02 00:55 UTC
