### ISSUE TITLE
Bogus "dependency graph cycle" error message in 0.15.

### ISSUE THREAD

**Issue by calebd** [Carthage/Carthage#1171] opened 2016-03-02 23:25 UTC
This did not happen in 0.14.

**Comment by mdiep** [comment] 2016-03-02 23:58
Can you share a Cartfile where this occurs?

**Comment by mz2** [comment] 2016-04-28 11:41
I'm also seeing what looks to me like a bogus cycle:

```
The dependency graph contained a cycle:
MPSheetView: 
CocoaHTTPServer: CocoaLumberjack
readability-objc: 
ITProgressIndicator: 
KSFileUtilities: 
Alamofire: 
ChimpKit3: 
MASShortcut: 
google-diff-match-patch-Objective-C: 
Freddy: 
evernote-sdk-mac: 
papers-shared: 
Fragaria: 
AFNetworking: 
RegexKitLite: 
YAML.framework: 
google-api-objectivec-client: 
CTidy: 
libextobjc: 
MPMaskedButton: 
GRMustache: 
ESCssParser: 
FDWebRingSDK: 
MAKVONotificationCenter: 
RMSkinnedView: 
SNRHUDKit: 
Extensions: RegexKitLite, Freddy, MPTimer, SWXMLHash, MPRateLimiter, OHHTTPStubs
P2Core: libextobjc, CocoaLumberjack
CocoaLumberjack: 
ZipZap: 
```

At least from this representation I can't work out where the cycle is?

**Comment by mdiep** [comment] 2016-04-28 13:24
@mz2  Could you please share your `Cartfile`?

**Comment by mz2** [comment] 2016-04-28 14:25
Here's my top level Cartfile:
```
github "mz2/AFNetworking" "510509a155355667a75b15241484e377767d8a82"
github "mpapp/CocoaLumberjack" "199fcdedc2ace9e27fc9be851e3e4f313a57bb9d"
github "mpapp/CocoaHTTPServer" "master"
github "mz2/ZipZap" "master"
github "mpapp/MASShortcut.git" "master"
github "mz2/KSFileUtilities" "master"
github "mz2/ChimpKit3" "master"
github "mz2/MAKVONotificationCenter" "master"
github "mpapp/YAML.framework" "master"
github "mz2/SNRHUDKit" "master"
github "mpapp/evernote-sdk-mac" "master"
github "mz2/GRMustache" "5b82f2eb6f9947d2c963729c276eac5c149cd4c5"
github "mpapp/MPSheetView" "master"
github "mpapp/MPMaskedButton" "master"
github "mz2/Fragaria" "master"
github "mpapp/P2Core" "master"
github "mpapp/CTidy" "master"
github "mpapp/readability-objc" "master"
github "mpapp/google-diff-match-patch-Objective-C" "master"
github "mpapp/google-api-objectivec-client" "master"
github "mpapp/RMSkinnedView" "master"
github "mpapp/FDWebRingSDK" "master"
github "mpapp/RegexKitLite" "master"
github "mpapp/papers-shared" "master"
github "mpapp/ESCssParser" "master"
github "mpapp/ITProgressIndicator" "master"
github "mpapp/Extensions" "master"
```

Here's 
```
➜  Manuscripts git:(master) cat ./Carthage/Checkouts/CocoaHTTPServer/Cartfile
github "mpapp/CocoaLumberjack" "199fcdedc2ace9e27fc9be851e3e4f313a57bb9d"
```

Here's one for Extensions:

```
➜  Manuscripts git:(master) cat ./Carthage/Checkouts/Extensions/Cartfile
github "bignerdranch/Freddy" "a9a0ca9d372d93e4c9a1051aa3c2c58715e68455"
github "mpapp/MPTimer" "master"
github "mpapp/RegexKitLite" "master"
github "drmohundro/SWXMLHash" "master"
github "AliSoftware/OHHTTPStubs" "master"
github "mz2/MPRateLimiter" "master"
```

One for P2Core:

```
➜  Manuscripts git:(master) cat ./Carthage/Checkouts/P2Core/Cartfile
github "mpapp/CocoaLumberjack.git" "199fcdedc2ace9e27fc9be851e3e4f313a57bb9d"
github "mz2/libextobjc.git" "7c202c858a655d54eccd5e5b0e717ba04310840a"
```


One for Feather:

```
➜  Manuscripts git:(master) cat ./External/Feather/Cartfile
github "mpapp/RegexKitLite" "master"
github "mz2/couchbase-lite-ios" "master"
github "mpapp/google-diff-match-patch-Objective-C" "master"
github "mpapp/P2Core" "master"
```

For CocoaHTTPServer that's inside couchbase-lite-ios/vendor/CocoaHTTPServer:

couchbase-lite-ios:
```
➜  Manuscripts git:(master) cat ./External/Feather/Carthage/Checkouts/couchbase-lite-ios/vendor/CocoaHTTPServer/Cartfile
github "mpapp/CocoaLumberjack" "155378a213fed031d60a8ebda804f1df512d9ef0"
```

Only weird thing I can see looking at these in combination is that the checkout of CocoaHTTPServer on the "top level" has a different revision of CocoaLumberjack required. No cycles that I can see though?

**Comment by mz2** [comment] 2016-04-29 10:31
Any ideas for a workaround for this, @mdiep?

**Comment by mdiep** [comment] 2016-04-29 12:23
I don't see anything that stands out. Can you try reducing your Cartfile to the smallest version that reproduces the error? That's often enlightening. Since there are a large number of dependencies and some of the repositories are private, it's hard to know what's going on.

**Comment by mz2** [comment] 2016-04-29 13:24
Unfortunately I can't – the issue's spontaneously went away by means of just starting from scratch (cleaned the cache away, fetched and built all dependencies again). Bizarre…

**Comment by mdiep** [comment] 2016-04-30 01:22
I'm going to close this since @mz2's problem went away after cleaning the cache.

If anyone experiences this issue, please open a new issue with the details of what you're seeing.

**Closed by mdiep** 2016-04-30 01:22 UTC

**Comment by zirinisp** [comment] 2017-02-01 11:48
Had the same problem after cleaning Carthage folder it went away. I wonder when this dependency management nightmare will go away. Yesterday I spend 3 hours with SPM today another 2 with Carthage.
