### ISSUE TITLE
segmentation fault : 11

### ISSUE THREAD

**Issue by flybikeGx** [Carthage/Carthage#501] opened 2015-05-28 08:32 UTC
```
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out Alamofire at "1.2.2"
*** Checking out SwiftyJSON at "2.2.0"
*** xcodebuild output can be found in /var/folders/fz/rlgkcxdn54gcf9lj6t7jf3gm0000gn/T/carthage-xcodebuild.rCGG7b.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task failed with exit code 65
Segmentation fault: 11
```
Xcode Version 6.3.2 (6D2105)
carthage version 0.7.3

but I can integrate them manually

**Comment by Vaseltior** [comment] 2015-05-28 14:45
:+1:

**Comment by jspahrsummers** [comment] 2015-05-28 16:01
Duplicate of https://github.com/Carthage/Carthage/issues/497.

**Closed by jspahrsummers** 2015-05-28 16:01 UTC

**Comment by jspahrsummers** [comment] 2015-06-06 05:35
I've tagged [0.7.4](https://github.com/Carthage/Carthage/releases/tag/0.7.4), which should fix all the hanging and crashing issues that we know about. The update should [become available in Homebrew](https://github.com/Homebrew/homebrew/pull/40450) soon.
