### ISSUE TITLE
Carthage support for a prebuilt .framework JSON dependency

### ISSUE THREAD

**Issue by bataboki** [Carthage/Carthage#2526] opened 2018-07-23 09:47 UTC
Hello,

is it posible to define famework dependencies  for prebuilt framework.

I tried adding Cartfile file to framework zip archive but id did not work.

Is there any way to do that?

**Comment by blender** [comment] 2018-07-23 10:00
Thanks for opening an issue.

This is not supported.

**Comment by ikesyo** [comment] 2018-07-23 12:11
This is a duplicate of #1937.

**Closed by ikesyo** 2018-07-23 12:11 UTC
Labels: question
