### ISSUE TITLE
Binary project specification including dynamic framework and sibling static framework

### ISSUE THREAD

**Issue by rajohns08** [Carthage/Carthage#2113] opened 2017-08-14 15:57 UTC
* `carthage version`:  0.24
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
# Visa Checkout iOS SDK
binary "https://localhost:4443/VisaCheckoutSDK.json" == 5.2.0
```

**Carthage Output**
```
Failed to read file or folder at /private/var/folders/lm/r2xch7b945x_h127yf35fx2wfl0bnk/T/carthage-archive.dfpPGh/TrustDefender.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.file=/tmp/carthage-20170519-51100-1ewwkj8/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1126, NSLocalizedDescription=the DTSDKName key in its plist file is missing}
```

When I install from my binary project specification zip that includes a dynamic binary framework and static binary framework, only the dynamic framework gets pulled down. The static framework is nowhere to be found.

The `TrustDefender.framework` mentioned in the output is the static framework.

**Comment by mdiep** [comment] 2017-08-14 16:00
Carthage doesn't currently support static frameworks. But there's been some discussion of adding support.

**Comment by ikesyo** [comment] 2017-08-15 23:51
Looks like this may be a duplicate of  https://github.com/Carthage/Carthage/issues/1056#issuecomment-174293745. Please make it sure that the framework's Info.plist file correctly contains `DTSDKName` as the error message says.

**Comment by ikesyo** [comment] 2017-08-15 23:56
IIUC prebuilt static frameworks are already supported thanks to https://github.com/Carthage/Carthage/pull/1932.

**Comment by ikesyo** [comment] 2017-09-06 14:42
Closing this due to inactivity. Feel free to reopen if you have any updates on this.

**Closed by ikesyo** 2017-09-06 14:42 UTC
