### ISSUE TITLE
Build cache is not invalidated when --configuration changes

### ISSUE THREAD

**Issue by rastersize** [Carthage/Carthage#2409] opened 2018-04-06 14:23 UTC
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.3, Build version 9E145
* Are you using `--no-build`? For bootstrap/update: yes.
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? Yes and No (bug is present with both)
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No (it’s not available to the `checkout` command)

**Cartfile**
```
github "https://github.com/Alamofire/Alamofire"
```

**Carthage Output**
```
$ carthage bootstrap --no-build --no-use-binaries
$ carthage build --configuration Debug --cache-builds --platform iOS --no-use-binaries
*** No cache found for Alamofire, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/pq/q5qww9n50hjglxqt04p7l13h0000gn/T/carthage-xcodebuild.ZaDIfK.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
$ carthage build --configuration Release --cache-builds --platform iOS --no-use-binaries
*** xcodebuild output can be found in /var/folders/pq/q5qww9n50hjglxqt04p7l13h0000gn/T/carthage-xcodebuild.DXlr1g.log
*** Valid cache found for Alamofire, skipping build
```

**Actual outcome**
Carthage did not re-build the framework with the Release configuration. The artifact previously built with the Debug configuration is used.

**Expected outcome**
Carthage notices that the cached framework was built with the Debug configuration and invalidates the artifact. Carthage then re-builds the framework with the Release configuration.

**Comment by blender** [comment] 2018-04-06 15:31
I think it would be enough to annotate in the `.version` file what configuration what used to build.

However one can also pass different .xcconfigs. What then?

**Comment by ikesyo** [comment] 2018-04-07 02:10
This is a duplicate of #1861

**Closed by ikesyo** 2018-04-07 02:10 UTC
Labels: enhancement, help wanted
