### ISSUE TITLE
Carthage update failed due to github DoesNotExist

### ISSUE THREAD

**Issue by tuxtux59** [Carthage/Carthage#1264] opened 2016-04-12 13:07 UTC
* `carthage version`: 0.16
* `xcodebuild -version`: 7D175
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "michaeltyson/TPKeyboardAvoiding"
github "Alamofire/Alamofire"
github "Alamofire/AlamofireImage"
github "SwiftyJSON/SwiftyJSON"
github "BradLarson/GPUImage"
github "dzenbot/DZNEmptyDataSet"
github "nickoneill/PermissionScope"
github "SVProgressHUD/SVProgressHUD"
```

**Carthage Output**
```
Fetching SVProgressHUD
*** Fetching PermissionScope
*** Fetching DZNEmptyDataSet
*** Fetching GPUImage
*** Fetching SwiftyJSON
*** Fetching AlamofireImage
*** Fetching Alamofire
*** Fetching TPKeyboardAvoiding
*** Checking out Alamofire at "3.3.1"
*** Downloading PermissionScope.framework binary at "PermissionScope 1.0.2"
*** Checking out GPUImage at "0.1.7"
*** Checking out AlamofireImage at "2.4.0"
GitHub API request failed: DoesNotExist
```

Most of Time the error is thrown when running PermissinoScope or GPUImage.
I tried to add a Github API Token with export HOMEBREW_GITHUB_API_TOKEN=MyAPIToken but not work

**Comment by mdiep** [comment] 2016-04-12 13:07
This is a duplicate of #1258, which was fixed and _just_ released in 0.16.1.

**Closed by mdiep** 2016-04-12 13:07 UTC
