### ISSUE TITLE
Issue with caching in Carthage

### ISSUE THREAD

**Issue by istx25** [Carthage/Carthage#704] opened 2015-08-22 15:12 UTC
I filed an issue to [Stripe's iOS repository](https://github.com/stripe/stripe-ios) because I received the following error when `carthage update` failed.

```
A shell task failed with exit code 66:
xcodebuild: error: Scheme StripeiOSStaticWithoutApplePay is not currently configured for the build action.
```

@jflinter explained to me the scheme `StripeiOSStaticWithoutApplePay` no longer exists. We suspect that this _bug_ has to do with a cache issue in Carthage, but we are not entirely sure.
#### Notes:
- My `Cartfile` includes:

```
github "stripe/stripe-ios" "master"
github "linehop/SAMTextView" "master"
```
- Original issue: https://github.com/stripe/stripe-ios/issues/210
- Device Information
  - Running Mac OS X 10.10.5 (14F27)
  - Using Xcode 6.4 (6E35b) and Carthage 0.8.0.
  - MacBook Pro (Retina, 15-inch, Mid 2015)

Cheers!

**Comment by ikesyo** [comment] 2015-08-23 07:18
Could you share the `Cartfile.resolved` of when this happened?

**Comment by ikesyo** [comment] 2015-08-23 07:45
@istx25 You wrote the following in https://github.com/stripe/stripe-ios/issues/210#issuecomment-133713599: 

> I tried deleting my DerivedData and updating Carthage first

What was the Carthage version when this happened before updating the tool? If this is not the case in Carthage 0.8, I'd like to close this out.

**Comment by istx25** [comment] 2015-08-23 11:36
@ikesyo: Here is my `Cartfile.resolved`:

```
github "linehop/SAMTextView" "d94fe8d45484d33c917064535fdc0adb66d228bb"
github "stripe/stripe-ios" "45ec81923ab3ced4e005ad089616d6dce9c1cab3"`
```

I was running the latest version of Carthage (0.8.0) when I ran `brew update && brew upgrade carthage`, so nothing was updated.

**Comment by ikesyo** [comment] 2015-08-23 14:33
I succeeded to reproduce the behavior.

1. `carthage update --no-build` with `github "stripe/stripe-ios" "v4.0.3"`.
2. Open `Carthage/Checkouts/stripe-ios/Stripe.xcworkspace`. After opening it, there is `StripeiOSStaticWithoutApplePay.xcscheme` in `Carthage/Checkouts/stripe-ios/Stripe.xcodeproj/xcuserdata/user_name.xcuserdatad/xcschemes`. That scheme is not shared, but Xcode automatically creates that from the corresponding target for your user.
3. `carthage update --no-build` with `github "stripe/stripe-ios" "v5.0.0"`.
4. `carthage build`, then the error happens. This is because `Stripe.xcodeproj` doesn't have `StripeiOSStaticWithoutApplePay` target any more, but `StripeiOSStaticWithoutApplePay.xcscheme` still exists in `Stripe.xcodeproj/xcuserdata/user_name.xcuserdatad/xcschemes`. That scheme file is not version controlled, checking out new revision doesn't remove the file.

I'm not sure this is what Carthage should consider.

**Comment by ikesyo** [comment] 2015-08-23 15:02
#655 seems to be related.

**Comment by mdiep** [comment] 2015-08-24 12:02
Maybe `carthage build` should display a warning if the checkout has been modified. I'm not sure if there's an easy way to do that if you're not using submodules.

**Comment by istx25** [comment] 2015-08-25 07:51
:+1:

**Comment by ikesyo** [comment] 2015-08-25 08:32
How about using `git status --ignored` or `git clean -ndX` with `--git-dir` and/or `--work-tree`?

**Closed** 2016-12-21 18:16 UTC
