### ISSUE TITLE
Problem bootstraping a multi target project

### ISSUE THREAD

**Issue by gperdomor** [Carthage/Carthage#1815] opened 2017-03-07 04:07 UTC
Hi... I'm building a framework for iOS, macOS, tvOS and watchOS...

I'm using Nimble and Quick for tests, but watchOS don't have tests, so Nimble and Quick don't have the schemas for watchOS, so when run `carthage bootstrap --platform watchOS` i get the bottom error

* `carthage version`: 0.20.0 
* `xcodebuild -version`:  Xcode 8.2.1 - Build version 8C1002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "Moya/Moya" ~> 8.0
github "Hearst-DD/ObjectMapper" ~> 2.2
```

**Cartfile Private**
```
github "Quick/Quick"
github "Quick/Nimble"
```

**Carthage Output**
```
$ carthage bootstrap --platform watchOS
*** Checking out Alamofire at "4.4.0"
*** Checking out Nimble at "v6.0.1"
*** Checking out Quick at "v1.1.0"
*** Checking out Result at "3.2.1"
*** Downloading ReactiveSwift.framework binary at "1.1.0"
*** Downloading RxSwift.framework binary at "Naldi"
*** Checking out Moya at "8.0.2"
*** Checking out unbox at "2.4.0"
*** xcodebuild output can be found in /var/folders/qp/6c3p64jd0yz3h1fdtqzx76jm0000gn/T/carthage-xcodebuild.HX66dl.log
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
Dependency "Nimble" has no shared framework schemes for any of the platforms: watchOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Quick/Nimble/issues/new
```

**Comment by ikesyo** [comment] 2017-03-07 04:27
This is a duplicate of #1792. Please track the issue. 🙏

**Closed by ikesyo** 2017-03-07 04:27 UTC
