### ISSUE TITLE
Repositories with Same Name Clash in Different Projects with Different Cartfiles

### ISSUE THREAD

**Issue by jdhealy** [Carthage/Carthage#569] opened 2015-06-17 21:52 UTC
_See also: #285_.
## To Reproduce:

``` shell
#!/usr/bin/env zsh
set -e # watch out for errors

# Only if the CI environment variable is set…
[[ -n $CI ]] && brew unlink carthage
[[ -n $CI ]] && brew install https://raw.githubusercontent.com/Homebrew/homebrew/dc0eb5fba1e74feca6204ba7d8a6921c5a0ea1d6/Library/Formula/carthage.rb # carthage 0.7.4

[[ "$(carthage version)" == "0.7.4" ]] # Check Carthage version output as string

preexec-print() { print -n '• '; print $2 }
autoload -U add-zsh-hook
add-zsh-hook preexec preexec-print # print all our commands from here-on-out

# - - -

local carthage_test="${PWD}/Carthage-Test"
mkdir -p ${carthage_test}
cd ${carthage_test}

mkdir antitypical
mkdir bignerdranch

echo 'github "bignerdranch/Result"' >> ./bignerdranch/Cartfile
echo 'github "antitypical/Result"' >> ./antitypical/Cartfile

cd ${carthage_test}/bignerdranch; carthage bootstrap --no-build --color='never'
cd ${carthage_test}/antitypical; carthage bootstrap --no-build --color='never'

cat ${carthage_test}/bignerdranch/Cartfile.resolved
cat ${carthage_test}/bignerdranch/Carthage/Checkouts/Result/Result/Info.plist || print 'Info.plist not found.'
cat ~/Library/Caches/org.carthage.CarthageKit/dependencies/Result/HEAD

cat ${carthage_test}/antitypical/Cartfile.resolved
cat ${carthage_test}/antitypical/Carthage/Checkouts/Result/Result/Info.plist || print 'Info.plist not found.'
cat ~/Library/Caches/org.carthage.CarthageKit/dependencies/Result/HEAD
```
### Output

```
Unlinking /usr/local/Cellar/carthage/0.6.4... 9 symlinks removed
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.7.4.yosemite.bottle.tar.gz
==> Pouring carthage-0.7.4.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/carthage/0.7.4: 124 files, 30M
• local carthage_test="${PWD}/Carthage-Test"
• mkdir -p ${carthage_test}
• cd ${carthage_test}
• mkdir antitypical
• mkdir bignerdranch
• echo 'github "bignerdranch/Result"' >> ./bignerdranch/Cartfile
• echo 'github "antitypical/Result"' >> ./antitypical/Cartfile
• cd ${carthage_test}/bignerdranch; carthage bootstrap --no-build 
*** No Cartfile.resolved found, updating dependencies
*** Cloning Result
*** Cloning Box
*** Checking out Box at "1.2.2"
*** Checking out Result at "1.2.1"
• cd ${carthage_test}/antitypical; carthage bootstrap --no-build --color='never
*** No Cartfile.resolved found, updating dependencies
*** Fetching Result
*** Fetching Box
*** Checking out Box at "1.2.2"
*** Checking out Result at "1.2.1"
• cat ${carthage_test}/bignerdranch/Cartfile.resolved
github "robrix/Box" "1.2.2"
github "bignerdranch/Result" "1.2.1"
• cat ${carthage_test}/bignerdranch/Carthage/Checkouts/Result/Result/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>com.bignerdranch.$(PRODUCT_NAME:rfc1034identifier)</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>$(CURRENT_PROJECT_VERSION)</string>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2014 Big Nerd Ranch. All rights reserved.</string>
    <key>NSPrincipalClass</key>
    <string></string>
</dict>
</plist>
• cat ~/Library/Caches/org.carthage.CarthageKit/dependencies/Result/HEAD
277e4b6c86c345de80554fac50f1c7cf9cbce91d
• cat ${carthage_test}/antitypical/Cartfile.resolved
github "robrix/Box" "1.2.2"
github "antitypical/Result" "1.2.1"
• cat ${carthage_test}/antitypical/Carthage/Checkouts/Result/Result/Info.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>com.bignerdranch.$(PRODUCT_NAME:rfc1034identifier)</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>$(CURRENT_PROJECT_VERSION)</string>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2014 Big Nerd Ranch. All rights reserved.</string>
    <key>NSPrincipalClass</key>
    <string></string>
</dict>
</plist>
• cat ~/Library/Caches/org.carthage.CarthageKit/dependencies/Result/HEAD
277e4b6c86c345de80554fac50f1c7cf9cbce91d
```

**Comment by jspahrsummers** [comment] 2015-06-18 04:35
This is “by design” because it allows all repositories in a GitHub network (i.e., forks and their parents) to share the repository cache, but I agree that the evidenced behavior is incorrect and surprising.

I'll leave this open, but https://github.com/Carthage/Carthage/issues/458 would fix this as well.

**Comment by ikesyo** [comment] 2017-10-19 00:55
Closing this as a duplicate of #2150.

**Closed by ikesyo** 2017-10-19 00:55 UTC
Labels: bug, help wanted, update
