### ISSUE TITLE
Carthage build failed when one of the nested dependency doesn't support arm64-simulator architecture

### ISSUE THREAD

**Issue by thangngoquocOura** [Carthage/Carthage#3173] opened 2021-04-30 22:55 UTC
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.37.0
* `xcodebuild -version`: Xcode 12.5 Build version 12E262
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "NordicSemiconductor/IOS-Pods-DFU-Library"
github "google/promises"

```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/w2/j6j_nctn0w3g74v63nvc95f00000gn/T/carthage-xcodebuild.ZlY6NK.log
*** Valid cache found for promises, skipping build
*** Valid cache found for ZIPFoundation, skipping build
*** Valid cache found for IOS-Pods-DFU-Library, skipping build
*** Building scheme "test-dfu" in test-dfu.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun dsymutil /Users/thang2410199/Library/Developer/Xcode/DerivedData/test-dfu-fbrvjndgrlygpdhabamjuoxijlnr/Build/Intermediates.noindex/ArchiveIntermediates/test-dfu/BuildProductsPath/Release-iphoneos/test_dfu.framework/test_dfu -o /Users/thang2410199/Library/Developer/Xcode/DerivedData/test-dfu-fbrvjndgrlygpdhabamjuoxijlnr/Build/Intermediates.noindex/ArchiveIntermediates/test-dfu/BuildProductsPath/Release-iphoneos/test_dfu.framework.dSYM

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/w2/j6j_nctn0w3g74v63nvc95f00000gn/T/carthage-xcodebuild.ZlY6NK.lo
```

**Actual outcome**
Carthage build command failed to create XCFramework

**Expected outcome**
Carthage should be able to build XCFramework of "test-dfu" which contains `ios-arm64_armv7` and `ios-i386_x86_64-simulator`.

Hello, I am having trouble adding Carthage support for my library, which has a dependency that doesn't support arm64-simulator architecture.

After setup the project, I use this command to verify Carthage build:
`carthage build --no-skip-current --use-xcframeworks --platform iOS --cache-builds`
First I got this error:

```
error: could not find module 'iOSDFULibrary' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator
#if canImport(iOSDFULibrary)
```
I then set my build setting of my library to exclude the arm64 architecture and ran the command again, this time I got the dsymutil error.

My test repo that reproduce the error:
https://github.com/thangngoquocOura/test-dfu

**Comment by thangngoquocOura** [comment] 2021-05-12 09:09
@elliottwilliams I can build the test project without any issue, my Xcode version is `12.5 (12E262)`
Building the project with `carthage build` is not an issue, but after building complete I got **dsymutil** error

I tried `EXCLUDED_ARCHS = arm64` for the whole project, and get the same result.

I will try XCODE_XCCONFIG_FILE approach and report back soon.

**Comment by elliottwilliams** [comment] 2021-05-18 21:34
Okay, I'm able to reproduce this with Xcode 12.5!

One thing I noticed further up in the build log is:

    warning: `None of the architectures` in ARCHS (arm64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7, armv7s) which is not in EXCLUDED_ARCHS (arm64). (in target 'test-dfu' from project 'test-dfu')

Looking at this project, the iOS deployment target (iOS 14.5) doesn't support 32-bit applications, so when Carthage builds the iOS variant, `$(ARCHS_STANDARD)` - `$(EXCLUDED_ARCHS)` is the empty set, which is why the iOS slice doesn't build or link anything. This is a "successful" xcodebuild but doesn't produce a binary, which is why Carthage fails right after xcodebuild exits.

It sounds like your goal is to only exclude arm64 on the simulator slice–if you want to do that, you should change the project's EXCLUDED_ARCHS build setting to be conditional like:

    EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64

I set this on the test project (diff: 
[exclude-arm64-simulator.patch.txt](https://github.com/Carthage/Carthage/files/6504536/exclude-arm64-simulator.patch.txt)), and carthage was able to build successfully, producing this xcframework:

    Carthage/Build/test_dfu.xcframework/
    ├── Info.plist
    ├── ios-arm64
    │   ├── BCSymbolMaps
    │   │   └── 0E05EF8A-1CF7-3713-A630-D77ABB65029B.bcsymbolmap
    │   ├── dSYMs
    │   │   └── test_dfu.framework.dSYM
    │   └── test_dfu.framework
    │       ├── Headers
    │       ├── Info.plist
    │       ├── Modules
    │       └── test_dfu
    └── ios-x86_64-simulator
        ├── dSYMs
        │   └── test_dfu.framework.dSYM
        └── test_dfu.framework
            ├── Headers
            ├── Info.plist
            ├── Modules
            ├── _CodeSignature
            └── test_dfu

**Comment by elliottwilliams** [comment] 2021-05-18 21:35
I'm going to close this out now since I think this is a problem with the project's configuration, not a problem with Carthage. If I've missed something please lmk and I'll reopen!

**Closed by elliottwilliams** 2021-05-18 21:35 UTC

**Comment by thangngoquocOura** [comment] 2021-05-19 18:48
Thank you @elliottwilliams Your change and explanation helped me understand the problem and be able to integrate a chain of dependencies to my project.
