### ISSUE TITLE
Carthage hangs when requesting an SSH passphrase

### ISSUE THREAD

**Issue by getaaron** [Carthage/Carthage#1617] opened 2016-11-29 15:18 UTC
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.0 Build version 8A218a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "danielgindi/Charts" == 3.0.0
git "git@<private URL>" == 6.0.2.1
```

**Carthage Output**
```
$ carthage bootstrap --platform ios
*** Fetching <private repo>
```

Carthage hangs. However:

```
$ /usr/bin/env git fetch --prune git@<private URL>

Enter passphrase for key '/Users/abrager/.ssh/id_rsa':
```

I think Carthage is eating the request for an SSH passphrase, possibly related to #219 and #447 or their fixes.

**Comment by Tapestes** [comment] 2017-01-06 21:59
Having what I believe is the same issue. On update, Carthage just hangs on Cloning <repository>.  When I clone in git, it's asking for the SSH passphrase.  That works fine.  Carthage never asks.

**Comment by jliu218-ford** [comment] 2017-09-13 05:58
@Tapestes thanks

**Comment by ikesyo** [comment] 2017-10-20 11:59
This is a duplicate of #1705.

**Closed by ikesyo** 2017-10-20 11:59 UTC
