### ISSUE TITLE
Cant add a dependency without updating all existing dependencies

### ISSUE THREAD

**Issue by LukeDefeo** [Carthage/Carthage#875] opened 2015-10-28 10:41 UTC
so i have the following cart file:

github "Alamofire/Alamofire" ~> 3.0
github "SwiftyJSON/SwiftyJSON"
github "mxcl/PromiseKit" ~> 3.0

All good. now i want to add a dependency so i add the following line:

github "Quick/Nimble"

The only i way i can get carthage to check this out and build it is to do carthage update. However this will update the version number of all the dependencies changing my carthage.resolved.

carthage checkout doesnt fetch my new dependency, nor does carthage bootstrap. What am i supposed to do here?

**Comment by NachoSoto** [comment] 2015-10-28 19:08
Yup! this is a dupe of #610.

**Closed by NachoSoto** 2015-10-28 19:08 UTC

**Comment by LukeDefeo** [comment] 2015-10-29 11:33
I disagree this is a duplicate. I'm not complaining about the rebuild of all my other dependencies, while that is quite annoying.

The real issue is that it updates the version numbers of all of my other dependencys. This is very bad if I had stable versions of my other dependencies in my cart.reaolved. I want to be in control of update my dependencies on a more granular basis

**Comment by neilpa** [comment] 2015-10-29 15:15
Then specify an explicit version number in your `Cartfile` and not an approximate one using the `~>` operator.

**Comment by LukeDefeo** [comment] 2015-10-29 16:22
I know but this feels like a work around to the problem that the update command won't take any arguments

**Comment by DanielAsher** [comment] 2015-12-12 07:21
+1

**Comment by fumoboy007** [comment] 2019-03-14 17:31
+1 Did this ever get fixed?

**Comment by NachoSoto** [comment] 2019-03-14 18:39
This was implemented in https://github.com/Carthage/Carthage/pull/972. You can now do `carthage update XXX`.
