### ISSUE TITLE
Carthage hangs with Cartfile (version: 0.18.0 while 0.11.0 works)

### ISSUE THREAD

**Issue by ssarangi** [Carthage/Carthage#1567] opened 2016-11-10 06:39 UTC
* `carthage version`: 0.18.0 
* `xcodebuild -version`: 8.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no

**Cartfile**
```
github "ReactiveCocoa/ReactiveCocoa" "master"
github "ReactiveCocoa/ReactiveObjCBridge" "master"
github "ReactiveCocoa/ReactiveSwift" "1.0.0-alpha.1"
github "Anviking/Decodable"
github "AgileBits/onepassword-extension" "add-framework-support"
github "DaveWoodCom/XCGLogger" "swift_3.0"
github "raphaelcruzeiro/Cartography" "swift3"
github "Quick/Quick"
github "Quick/Nimble"
```

**Carthage Output**
```
± |master U:253 ✗| → carthage update --platform ios --no-use-binaries
*** Fetching Cartography
*** Fetching Nimble
*** Fetching XCGLogger
*** Fetching onepassword-extension
*** Fetching ReactiveObjCBridge
*** Fetching ReactiveCocoa
*** Fetching Quick
*** Fetching Decodable
*** Fetching Result
*** Fetching ReactiveObjC
*** Fetching ReactiveObjC
```

Happens even without using --no-use-binaries. Duplicate of issue #980 but it keeps on getting stuck at Fetching ReactiveObjC. Even clearing of caches didn't help.

**Comment by mdiep** [comment] 2016-11-10 13:19
Carthage is probably getting stuck because of all the branch versions. There's some weirdness with how that's handled that we're trying to sort out.

**Comment by ssarangi** [comment] 2016-11-10 14:31
@mdiep thanks for clarifying. Just fyi 0.11.0 works

**Comment by JetForMe** [comment] 2016-11-21 19:56
(Sorry, I also commented on an older, closed bug.)

I'm seeing hangs, as well, at various stages of running carthage update. Sometimes I get nothing at all, sometimes it checks out a repo or two, sometimes it makes it through a build. In all cases, interrupting it with ctrl-C and running it again lets it get farther along (it sometimes takes more than two invocations). Version 0.17.1.

My Cartfile is simple:

```
github "crossroadlabs/Regex" "1.0.0-alpha.1"
```

It has also happened with this Cartfile:

```
github "SwiftyJSON/SwiftyJSON"
```

(In other words, nothing special.)

**Comment by ikesyo** [comment] 2016-11-22 12:58
@JetForMe You may be hitting #1370, that was happening on 0.17.1 and fixed in 0.17.2. Updating to the latest 0.18.2 should fix your issue.

**Comment by getaaron** [comment] 2016-11-29 15:25
@ikesyo I'm seeing a similar issue (#1617) but I only see a release 0.18.1 (no .2)

**Comment by mdiep** [comment] 2017-01-18 12:53
I can't reproduce this with the above cartfile.

**Closed by mdiep** 2017-01-18 12:53 UTC
