### ISSUE TITLE
Unable to get pre-built binaries from GitHub Enterprise

### ISSUE THREAD

**Issue by gbegen** [Carthage/Carthage#971] opened 2015-12-05 03:55 UTC
I've created a release in my framework's GitHub Enterprise repository and attached a MyProject.framework.zip file as built by `carthage archive` as an asset to the release.

When I create a Cartfile that references this release of this project, Carthage still checks out and builds the project, instead of just downloading and using the pre-built binary.

Is there something about GitHub Enterprise that prevents the use of pre-built binaries with Carthage?

**Comment by mdiep** [comment] 2015-12-05 15:01
Are you referencing the project with the `github` syntax in your `Cartfile`? Is the project public or private on the enterprise server?

Pre-built binaries should work with GitHub Enterprise.

**Comment by gbegen** [comment] 2015-12-06 02:32
I am indeed using the `github` syntax. Carthage successfully clones and builds the project when I run `carthage update` or `carthage build`, but it does not download the pre-build binary, which has a filename of the form `MyProject.framework.zip`, and was built with `carthage archive`.

**Comment by cruinh** [comment] 2015-12-07 21:36
I seem to be having this exact same issue.  Can very easily reproduce by creating a brand new Xcode (7.1.1) project and adding this to a fresh Cartfile
github "uShip/Alamofire.git" ~> 3.1.3.1

carthage update still seems to build this fork of Alamofire.

**Comment by cruinh** [comment] 2015-12-07 21:40
...of course I figured out the issue 2 minutes after posting that.  I needed to edit the github Release to "attach" the zip file.  Not just upload it with the rest of the source code.  This requirement should probably be made explicit in the README.

@gbegen maybe you're having the same issue?

**Comment by gbegen** [comment] 2015-12-07 21:52
Nope. The MyProject.framework.zip file was definitely attached to the release with GitHub (Enterprise).

**Comment by mdiep** [comment] 2015-12-07 22:03
@gbegen Is your project a _public_ project or a _private project_ on your Enterprise instance? Can you clone a private project from your enterprise instance on the command line using HTTPS? (This information is helpful in knowing whether Carthage is able to use the authenticated API.)

**Comment by gbegen** [comment] 2015-12-09 21:35
@mdiep - This is a _public_ project.

After reading through the Carthage source code and some time taken to learn a bit of Reactive Cocoa, I discovered that my problem is twofold:
1. I had not provided the necessary authorization credentials to carthage for it to be able to use the GitHub API. There appear to be two ways to do this, either by setting the GITHUB_ACCESS_TOKEN environment variable to "{server}={api-token}" or by using `git credential fill`. I think this information should probably be added to the carthage README in the section about pre-built frameworks and perhaps some messaging added when carthage runs and cannot determine the credentials for the target GitHub server. 
2. My GitHub Enterprise installation is version 2.1 and the API to get a release by tag name, used by carthage, was introduced in version 2.2. Not sure if I can get my admin to update our installation any time soon. Would it make sense for carthage to fall back to getting all releases with the older API and searching through the response for the one release with the right tag name?

**Comment by mdiep** [comment] 2015-12-09 21:43
Thank you for digging into this and reporting back, @gbegen!

> I think this information should probably be added to the carthage README in the section about pre-built frameworks

Absolutely! Would you be interested in opening a pull request to add this information?

> and perhaps some messaging added when carthage runs and cannot determine the credentials for the target GitHub server.

Good idea. I opened #984 to track this.

> My GitHub Enterprise installation is version 2.1 and the API to get a release by tag name, used by carthage, was introduced in version 2.2. Not sure if I can get my admin to update our installation any time soon. Would it make sense for carthage to fall back to getting all releases with the older API and searching through the response for the one release with the right tag name?

We usually don't like to add code to deal with older versions of toolchain components. GitHub Enterprise 2.2 was released in April 2015, which was quite a while ago. Since binaries are a convenience and not a requirement for building, I don't think it makes sense to add a fallback. Sorry!

**Closed** 2015-12-15 02:39 UTC
