### ISSUE TITLE
No Shared Scheme After Adding A New Dependancy After One That Was Already Pulled Down

### ISSUE THREAD

**Issue by jcampbell05** [Carthage/Carthage#438] opened 2015-04-30 08:41 UTC
I have a bug where if I had a new entry to the Cartfile after a previous library I have ran `cartthage update` for it will fail to build this new dependancy telling me there are no schemes.

**Comment by mdiep** [comment] 2015-04-30 11:47
I'm not understanding what the issue is. Could you post an example Cartfile that reproduces the issue?

**Comment by jcampbell05** [comment] 2015-05-06 11:16
It's not one you can reproduce just by using a Cartfile. But I've had an issue where I've added a dependancy on Library A, and run `cart update`, then later on I add Library B to the bottom and I get a `No shared schemes.` issue after I `cart update`. If I move library B before library A in the cartfile it suddenly works again :)

**Comment by jspahrsummers** [comment] 2015-05-08 04:36
Could you please provide a complete example project, if just a `Cartfile` won't do it? It's hard for us to investigate and fix the issue without some way to reproduce it. :confused:

**Comment by jcampbell05** [comment] 2015-05-12 22:07
Here is my cartfile:

    github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.4"
    github "bolt"

**Comment by neilpa** [comment] 2015-05-13 01:58
Doesn't that second dependency produce an error? At a minimum you need `github "{owner}/{repo}"`

**Comment by jcampbell05** [comment] 2015-05-20 21:09
I just ran this now and seems like there is some sort of issue with signing and the new Xcode.

=== BUILD TARGET Box-iOS OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
        Check dependencies
(1 failure)

**Comment by jspahrsummers** [comment] 2015-05-21 16:54
As the error indicates, it sounds like you don't have an iOS code signing identity. If you are unable to install one, you can use `--platform Mac` to ask Carthage to only build Mac products.

**Comment by jcampbell05** [comment] 2015-05-21 16:58
I'm thinking we need to expose this error to the user so they don't have to use the `--verbose` flag :)

**Comment by jspahrsummers** [comment] 2015-05-22 17:15
That sounds like a separate bug report. :wink:

I'm going to close this out, because it sounds like the originally described issue is resolved.

**Closed by jspahrsummers** 2015-05-22 17:15 UTC
