### ISSUE TITLE
Carthage always fetch the original repo instead the forked one?

### ISSUE THREAD

**Issue by jfsagasti** [Carthage/Carthage#1204] opened 2016-03-22 19:21 UTC
Hi! I forked a repository and made some changes to it. Then, I specified my repo URL in the Carthage file, but when I run carthage update, it always fetches and tries to build the original one. Or maybe it's my repo after all, but it is not seeing latest changes.

Is this a bug or am I missing something? I'm using latest Carthage version (0.15.2). Thanks.

**Comment by jlawton** [comment] 2016-03-22 19:38
This sounds like a caching bug. Have you tried deleting the Carthage cache at `~/Library/Caches/org.carthage.CarthageKit`?

**Comment by jfsagasti** [comment] 2016-03-22 19:42
Yes, I tried that but it keeps cloning the original version (or an outdated version of my fork)...

**Comment by jtilleyj** [comment] 2016-03-23 07:00
I have seen this as well. It was introduced in version 0.15. When I installed 0.14 the latest commit was fetched.

**Comment by patricks** [comment] 2016-03-23 09:42
I have the same problem 😞

**Comment by patricks** [comment] 2016-03-23 09:49
I found a workaround.

Switching the repo in the `Cartfile` from:

`github "patricks/Swift-Prompts.git"`

to:

`git "https://github.com/patricks/Swift-Prompts.git" "master"`

works for me.

**Comment by jfsagasti** [comment] 2016-03-23 12:26
Thanks @patricks! That is the only workaround that worked for me (switching to a previous Carthage version didn't work)

**Comment by ikesyo** [comment] 2016-03-23 12:35
@jfsagasti If you are specifying a branch in your Cartfile, this may be the same as #1191 and should be fixed by #1202, I think.

**Comment by mdiep** [comment] 2016-03-23 19:51
I'm going to preemptively close this because it sounds like a duplicate of #1191.

**Closed by mdiep** 2016-03-23 19:51 UTC
