### ISSUE TITLE
Carthage build fails with iOS 7.1 simulator installed

### ISSUE THREAD

**Issue by erichoracek** [Carthage/Carthage#417] opened 2015-04-07 23:08 UTC
Steps to reproduce:

- Install the iOS 7.1 Simulator in Xcode 6.2
- Create a new Cocoa Touch Framework project in Xcode
- Run `carthage build --no-skip-current` in the directory that the Framework project was created in

You will receive the following build error:

```
CompileC ...
invalid architecture 'arm64' for deployment target '-mios-simulator-version-min=8.2'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

This is due to the fact that Carthage (as far as I can tell) is running the following command during `carthage build --no-skip-current`:

```
xcodebuild build -scheme Framework -sdk iphonesimulator
```

If you run the above command on your new framework project, you will see the same build error that is produced when you run `carthage build`.

As far as I can tell, the reason for this failure is that when no destination is specified in a build command, `xcodebuild` implicitly selects a destination simulator to build for. Since we have the iOS 7.1 Simulator installed, it is (for some reason) picked as the default destination, causing the above error to occur. However, if you select the latest simulator as the build destination via the command line:

```bash
xcodebuild build -scheme Framework -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 4s,OS=latest'
```

There is no build failure. The solution for this (as far as I can tell) would be to have Carthage allow for a `destination` option to be specified in addition to the existing `platform` and `configuration` options, or simply to not support Xcode installs that have pre-iOS 8 simulators installed.

**Comment by jspahrsummers** [comment] 2015-04-10 18:16
Good catch!

Looking at the manpage for `xcodebuild`, it looks like we could maybe pass `-destination 'generic/platform=iOS Simulator'`, or perhaps fit `OS=latest` in there somehow. The flag seems poorly documented, so I'm not exactly sure.

**Comment by pizthewiz** [comment] 2015-04-29 01:02
I've run into this with SwiftHTTP daltoniam/SwiftHTTP#83 and notably the iOS 7 Simulators are *not* installed.

**Comment by pizthewiz** [comment] 2015-04-29 18:17
And strangely after upgrading to Xcode 6.4 Beta 2 and activating its command line tools, SwiftHTTP builds just fine…

**Comment by Ben-G** [comment] 2015-07-20 21:50
Has anyone found a workaround for this issue? Besides building the library without carthage 😉

**Comment by sharpfive** [comment] 2015-07-21 14:32
Switching to XCode 6.4 (or just the 6.4 command line tools) fixed this for me. I haven't had a problem since.

**Comment by Ben-G** [comment] 2015-07-21 15:07
@sharpfive I unfortunately need Swift 2 for the dependencies in the affected project.

**Comment by ikesyo** [comment] 2015-08-05 13:14
I confirmed that passing ` -destination "generic/platform=iOS Simulator"` didn't work. :disappointed: We must pass a name or an id.

**Comment by mdiep** [comment] 2015-08-08 03:15
Has anyone filed a radar about this? It really seems like an 'xcodebuild' bug, especially given the documentation for `-destination`:

> -destination destinationspecifier
>           Use the destination device described by destinationspecifier.  **Defaults to a
>           destination that is compatible with the selected scheme.**

**Comment by ikesyo** [comment] 2015-08-12 01:30
Closed by #653.

**Closed by ikesyo** 2015-08-12 01:30 UTC
Labels: bug, build, help wanted

**Comment by auibrian** [comment] 2015-10-27 18:18
This is marked as closed but I'm seeing the same issue happening when building for Watch Simulator.

**Comment by kballard** [comment] 2015-10-27 18:21
In theory, it should be passing a destination requesting to build for a generic simulator (instead of one of the specific installed simulators).

**Comment by auibrian** [comment] 2015-10-27 18:23
I'm wondering if it has something to do with having multiple Xcodes installed, or multiple simulators perhaps. I have only just been able to reproduce the bug in xcodebuild after having found this issue.

**Comment by auibrian** [comment] 2015-10-27 19:24
On further investigation it appears that the machine I was experiencing failures on had no watch simulators set up at all. Which triggered the xcodebuild unsupported architecture bug.
