### ISSUE TITLE
v0.12 stuck executing `update`

### ISSUE THREAD

**Issue by andreyz** [Carthage/Carthage#1092] opened 2016-02-03 18:18 UTC
After successfully building 2 out of 6 frameworks from Cartfile the process hangs on seemingly forever (more than an hour for sure). 
I can see that two frameworks were built by tailing the xcode-build log output.  Any hints on what's going on?

**Comment by mdiep** [comment] 2016-02-03 18:21
Dupe of #940.

**Closed by mdiep** 2016-02-03 18:21 UTC
